### PR TITLE
Add trailing space as workaround for po4a problem.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by hansu** [comment]
What was the problem?

**Comment by petterreinholdtsen** [comment]
[Hans]
> What was the problem?

Same as in 47c6e0dfd41dfd41d25b5aeb455358cf9b125f8e.  This patch just
fixes some issues introduced after
47c6e0dfd41dfd41d25b5aeb455358cf9b125f8e.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
Is this ok for you if it goes in `docs-devel` ?

**Comment by silopolis** [comment]
Le mar. 12 avr. 2022 à 23:27, Hans ***@***.***> a écrit :

> Is this ok for you if it goes in docs-devel ?
>

Good for me

**Comment by petterreinholdtsen** [comment]
[Hans]
> Is this ok for you if it goes in `docs-devel` ?

Sure.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request merged**
