### PR TITLE
Changed an instance of HOME_FINAL to HOME_FINAL_VEL

### PR DESCRIPTION
**Pull request by JetForMe**

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
Hi @JetForMe, thanks for contributing to LinuxCNC!

This fix should really go in the 2.7 branch, can you move the commit there (maybe with `git checkout -b patch-1-2.7 origin/2.7; git cherry-pick patch-1`) and make a new PR?

**Comment by JetForMe** [comment]
I did this directly on github, but I can find a way to merge the change to 2.7. Are you saying it should _also_ be in 2.7, or only in 2.7 and not in master/2.8?

**Comment by andypugh** [comment]
You should make the change in 2.7 then it will (almost) automatically be merged upstream in to 2.8 and master

**Comment by mozmck** [comment]
I merged your PR on 2.7 so closing this one - Thanks!

**Pull request closed without merging**
