### PR TITLE
Remap IO M62-M68 2.6

### PR DESCRIPTION
**Pull request by zultron**
This patch, previously discussed at [emc-developers](https://sourceforge.net/p/emc/mailman/message/35146277/), enables remap of M62-M68.

The unit test exercises both python/NGC bodies and recursivity, and checks functionality of interp, status channel and HAL.

### CODE REVIEW

**Comment by zultron** [comment]
Whoops, meant to submit against 2.6; try again

**Comment by zultron** [comment]
Ah, the PR base can be changed, yay!

**Comment by jepler** [comment]
(the 2.6 branch isn't enabled for travis-ci at the moment.  I think the switch of base branch caused travis-ci to think it could build, but it can't because required scripts are missing whch led to the reported failure.)

**Comment by zultron** [comment]
Thanks, @jepler.  I pushed to glo; buildbot results [here][1]

[1]: http://buildbot.linuxcnc.org/buildbot/builders/0000.checkin/builds/4476

**Comment by jepler** [comment]
Pushed to master.  Since this requested to merge to 2.6, I don't think github will automatically close it, so closing manually.

**Pull request closed without merging**
