### PR TITLE
Python3 change debian/configure

### PR DESCRIPTION
**Pull request by phillc54**
prevent syntax error when running debian/configure

### CODE REVIEW

**Comment by rene-dev** [comment]
I already did this in my gtk3 branch, and Im working on packaging and dependencies for buster and focal.

**Comment by rene-dev** [comment]
if you are working with gtk3, or packaging, yes. You can look into the problem its having right now.

**Comment by rene-dev** [comment]
https://github.com/rene-dev/linuxcnc/runs/1141214421#step:4:12902

**Comment by havardAasen** [comment]
@rene-dev This is the limuxcmc branch in your own repo? are you accepting PR's?

**Comment by rene-dev** [comment]
Yes and yes. Its in my account because Im working with people that dont have access to the linuxcnc repo.

**Comment by andypugh** [comment]
Maybe it would be better to give them access to LinuxCNC? 
(Or, has been suggested, have _everyone_ use pull-requests to make changes)

**Comment by rene-dev** [comment]
I think about that. MK has a policy like this, I dont know how well it would work for linuxcnc.
@phillc54 Im closing this as its already fixed in my branch, which will hopefully be merged soon.
for some reason it still cant build the package.

**Pull request closed without merging**
