### PR TITLE
docs: misc updates while translating (smoe:docs29_mac_14)

### PR DESCRIPTION
**Pull request by smoe**
Opened my mac again and decided to push the active branch after a rebase to 2.9.

### CODE REVIEW

**Comment by hansu** [comment]
You have a  lot of unresolved merge conflicts in [tooldatabase.adoc](https://github.com/LinuxCNC/linuxcnc/pull/2235/files#diff-374d2b038b74dfbb9da218f7666ef9432ef0f97e5e0c4a7dd719c7db58b409cd)

**Comment by petterreinholdtsen** [comment]
The htmldocs build failed.

**Comment by hansu** [comment]
> The htmldocs build failed.

Yeah because of that I mentioned like

```
<<<<<<< HEAD
Tool data is conventionally described by a tool table file specified by an INI file setting:
[EMCIO]TOOL_TABLE=tooltable_filename.
A tool table file consists of a text line for each available tool describing the tool's parameters,
see <<sec:tool-table,Tool Table Format>>.

The tool database interface provides an alternative method for obtaining tool data
via a separate program that manages a database of tools.
=======
Tool data is conventionally described by a tool table file specified by an inifile setting: [EMCIO]TOOL_TABLE=tooltable_filename.
A tool table file consists of a text line for each available tool describing the tool's parameters, see <<sec:tool-table,Tool Table Format>>.
The tool database interface provides an alternative method for obtaining tool data via a separate program that manages a database of tools.
>>>>>>> 7c0463564a (docs: misc updates while translating)
```

**Comment by smoe** [comment]
@hansu - Ha!

**Pull request merged**
