### PR TITLE
pncconf: fix all-limit-home homing

### PR DESCRIPTION
**Pull request by phillc54**
All Limit Plus Home was not writing the correct homing configuration.

### CODE REVIEW

**Comment by andypugh** [comment]
Can you rebase against 2.8 if the fix is needed there?

**Comment by phillc54** [comment]
> Can you rebase against 2.8 if the fix is needed there?

I could but I am not sure of the workflow require to achieve it.

**Comment by andypugh** [comment]
Yes, please. Bug fixes belong in 2,8 and then will be merged up to master.

**Comment by phillc54** [comment]
closing and creating new PR on 2.8 branch.

**Comment by phillc54** [comment]
I have run into an issue that I am not sure how to resolve.

I need to add the  line:
`print("HOME_IS_SHARED = 1", file=file)`
The problem is that in master the print function is used `from __future__ import print_function` but in 2.8 is uses the print statement so the line needs to be:
`print >>file, "HOME_IS_SHARED = 1"`

I guess that I now need to create a separate PR for each branch?

**Pull request closed without merging**
