### PR TITLE
Add build rules for po4a based documentation translation

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
Use 'make translateddocs' to build the translations and 'make pofiles'
to update the POT and PO files.  'make postatus' show translation
statistics.  Run 'make manpages' before updating translations to make sure
the generated manpages are available for po4a.

Added code to copy images into translated adoc directories.

Added po4a as new build dependency.

Require 0 translated strings to generate files, to make sure the documents are
buildable even if nothing is unfuzzied yet.

Drop translated files from docs.xml and use the same list for all languages.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
This is the continuation of https://github.com/LinuxCNC/linuxcnc/pull/1356 which was closed by mistake when it was pulled into a feature branch for testing on the buildbot system.

**Comment by petterreinholdtsen** [comment]
I believe this is ready to go into production now.  The only unsolved issue is how to handle translated help texts, which can be solved at a later time.   I know @smoe and @silopolis is working on updated PO files for spanish and french, and we might want to wait for those before merging into master or a documentation branch.

**Comment by andypugh** [comment]
How do you want to do it? Straight in to Master, or into a docs/po4a testing branch?

**Comment by hansu** [comment]
Good question. We thought to master **after** Jérémies changes are merged to master.
But we can also have this in a test branch before.

**Comment by petterreinholdtsen** [comment]
[Hans]
> Good question. We thought to master **after** Jérémies changes are
> merged to master.  But we can also have this in a test branch before.

Are you talking about 
<URL: https://github.com/LinuxCNC/linuxcnc/pull/1702 >?

At least some of my changes should not conflict with his and could to in
before #1702.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
> Are you talking about <URL: #1702 >? At least some of my changes should not conflict with his and could to in before #1702. 

Yes. But with Jérémies changes the po files have to be generated again, so I thought it would be better to have them first in master.

**Comment by petterreinholdtsen** [comment]
[Hans]
> Yes. But with Jérémies changes the po files have to be generated
> again, so I thought it would be better to have them first in master.

Well, my reduced branch do not have the French and Spanish PO files any
more, so we can add them independent of my pull request. :)

My pull request only contain some nb translations, the rest of the PO
files included are empty.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
I am with Hans. Let's get @silopolis 's changes merged with master and from there you get shiny updated .po files and LinuxCNC then transitions to po4a. Technically I understand you are right but my brain finds this all complicated enough already.

**Comment by hansu** [comment]
>Well, my reduced branch do not have the French and Spanish PO files any
more, so we can add them independent of my pull request. :)

Yeah but wouldn't cause empty docs for the other languages?

**Comment by hansu** [comment]
Is this ok for you if it goes in `docs-devel` ?

**Comment by petterreinholdtsen** [comment]
[Hans]
> Is this ok for you if it goes in `docs-devel` ?

Sure, as long as docs-devel end up in master when we are ready. :)
-- 
Happy hacking
Petter Reinholdtsen

**Comment by silopolis** [comment]
Was thinking of providing initial _fr po file in the last commit of my fr_migration PR

**Comment by hansu** [comment]
As far as I understood, with this change to the Submakefile, the po files are generated from the existing adoc files if no po files are existing. So as long as we haven't commit any po files, this shouldn't affect your syncronization work, right?
So I'll merge it right now?

**Comment by silopolis** [comment]
Le mer. 13 avr. 2022 à 10:11, Hans ***@***.***> a écrit :

> As far as I understood, with this change to the Submakefile, the po files
> are generated from the existing adoc files if no po files are existing. So
> as long as we haven't commit any po files, this shouldn't affect your
> syncronization work, right?
> So I'll merge it right now?
>
Good for me !

**Comment by petterreinholdtsen** [comment]
[andypugh]
> How do you want to do it? Straight in to Master, or into a docs/po4a
> testing branch?

Up to you, really.  I am aiming for master, of course, but am happy to
get more exposure in a testing branch first as well. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by silopolis** [comment]
Le mar. 11 oct. 2022 à 09:10, petterreinholdtsen
***@***.***> a écrit :
>
> [andypugh]
> > How do you want to do it? Straight in to Master, or into a docs/po4a
> > testing branch?
>
> Up to you, really. I am aiming for master, of course, but am happy to
> get more exposure in a testing branch first as well. :)

Already merged, isn't it ?

**Comment by petterreinholdtsen** [comment]
[Jérémie Tarot]
> Already merged, isn't it ?

Yes, 2022-04-13 by Hans.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request merged**
