### PR TITLE
docs: intensive reformatting of gstate.adoc

### PR DESCRIPTION
**Pull request by smoe**
Quite an intense reformatting
 - removed explicit bold face in descriptions
 - arguments became part of left side of :: separator, other than return values
 - fixed indentation, removed empty lines
 - consistency in spelling

### CODE REVIEW

**Comment by hansu** [comment]
I think we should finish the Style Guide before doing such reformatting.

**Comment by petterreinholdtsen** [comment]
[Hans Unzner]
> I think we should finish the Style Guide before doing such
> reformatting.

I suspect such reformatting is a good exercise for knowing what to write
in the style guide.

But I would very much like to see the style guide move forward.  If
someone know how to get there, please update pull request #1530.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
>I suspect such reformatting is a good exercise for knowing what to write
in the style guide.

First I like the current formatting of the GStat messages overview.  And second I wouldn't change the formatting of such a central element just so spontaneous.

And it doesn't make sense to change something before you have a recipe how to change it.

I am also holding back some changes until we have decided how we should format pin lists and lists like this.

**Comment by hansu** [comment]
I gave it a try and build it. Here the comparison:
Current version:
Screenshot_2022-08-30_19-51-30

This PR:
Screenshot_2022-08-30_19-51-41


--> So IMHO it's a change to the worse. Less clear and consumes more vertical space.

**Comment by smoe** [comment]
You are right. This is worse. I am not sure why I change the tailing "-" behind those (return..)s. I'll reintroduce the "-"s. I typically just have problems with too many "+"s.

I am with Petter that we should know what to work for, style-guide wise.

**Comment by smoe** [comment]
Should look good again. What got me triggered was that the () syntax is used inconsistently for return values and arguments. And then I just did not like all those "*..*"s when the asciidoc "::" syntax does just that. Still, I hope that we come up with something better.

**Comment by smoe** [comment]
Undid almost all my changes, left a few simplistic ones.

**Comment by hansu** [comment]
I thought we finish first the style guide for this, but ok, let's merge this first.

**Pull request merged**
