### PR TITLE
Add another G71 endless loop test and a fix for it

### PR DESCRIPTION
**Pull request by havardAasen**
A stripped down version of the problem in #2844, code structure is copied from 'g71-endless-loop'. The test is marked as skipped, since it does not always terminates correctly.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
@andypugh Should this change go into 2.9 or master?

**Comment by andypugh** [comment]
I am happy for extra tests (which pass!) to go in 2.9. Especialliy if they relate to bug fixes which are also aimed at 2.9

**Comment by petterreinholdtsen** [comment]
[andypugh]
> I am happy for extra tests (which pass!) to go in 2.9. Especialliy if
> they relate to bug fixes which are also aimed at 2.9

How does your view relate to this patch?  A skipped test, that is.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by havardAasen** [comment]
I updated the branch and enabled the test. I also included a fix for the endless loop problem. I believe this fix is robust enough to handle all cases where the algorithm ended up in an endless loop.

Still targeting master, but there is no problem targeting 2.9, except that it is untested.

**Comment by fsabbatini89** [comment]
Test this and endless loop will happen: k-20 is ill formed. 
Already fixed in [#2907](https://github.com/LinuxCNC/linuxcnc/pull/2907)


```
G54 g95 g18 G21 G7 g61 g91.1

t02
g97 s350 m4
g0 x120 z4 m8


o110 sub 
g1 X79.995 Z0
g3 x83.9549 z-1.7176 k-20
g1 x95.25 z-47.4
g1 z-62
g1 x99 z-68
O110 endsub
;o15 call

G71 X104 Z5 Q110 D0 I1.5 R2 F0.3
g0 x200 z100
m30
```

**Pull request merged**
