### PR TITLE
Fix subs breaking when placed after main program 2.6

### PR DESCRIPTION
**Pull request by zultron**
RS274NGC-style subprograms were once allowed to be placed before or after the main program.  A regression snuck in with remap that disallowed subs following the main program.

This PR fixes subs following the main program, and adds a unit test.

### CODE REVIEW

**Comment by zultron** [comment]
Pushed to glo; I expect buildbot results to be [here][1]

[1]: http://buildbot.linuxcnc.org/buildbot/builders/0000.checkin/builds/4478

**Comment by zultron** [comment]
Looks like this passed the buildbot, except two builders that say `HAL: ERROR: version code mismatch`.

**Comment by cradek** [comment]
Thank you for this bugfix and test; I put it in 2.6.

**Comment by zultron** [comment]
Thanks, @cradek.  I see commit 2e52efef60793fea36df72c536ccc6b546cf5b19 in the 2.6 branch.

**Pull request closed without merging**
