### PR TITLE
Disable tooltips option in Gmoccapy

### PR DESCRIPTION
**Pull request by neilwhelchel**
GTK tooltips are really annoying when being used with a touch screen. I added a checkbox in the settings to disable them.
I am not aware of any way to globally disable them in GTK, so this walks the widgets and individually enables or disables them.
If someone is aware of a way to do this globally at runtime, please let me know and I will update the code accordingly.

### CODE REVIEW

**Comment by gmoccapy** [comment]
As far as I have seen, you do not disable the tooltips from the dynamically generated widgets, like DRO, Touch off button etc.

I will try to get this also in the code and add your one to the latest gmoccapy code asap.

Norbert

**Comment by andypugh** [comment]
Is this pull-request still needed, or did the changes go in to Gmoccapy by other routes?

**Comment by c-morley** [comment]
I'm pretty sure it wasn't included - Norbert has seemed to be MIA these days.

**Comment by gmoccapy** [comment]
I added also the dynamically created widgets to the hide tooltips widgets. 
and pushed the new changes to 2.8

https://github.com/LinuxCNC/linuxcnc/commit/8e28eab6bb75e08361f156acee260e9ec5d4a6dc

so I will close this one, as I have stolen the code and added some of my stuff to solve the issue.

Norbert

**Pull request closed without merging**
