### PR TITLE
added chinese translation for Getting Started

### PR DESCRIPTION
**Pull request by ButterflyTech**
I translated "Getting Started" doc to chinese, please review my commit.

### CODE REVIEW

**Comment by andypugh** [comment]
I have no way to know if the Chinese is correct, but assume that it is. 
Are you sure that you want this only in Master? I think there might be an argument for merging it to 2.8.

**Comment by ButterflyTech** [comment]
> I have no way to know if the Chinese is correct, but assume that it is.
> Are you sure that you want this only in Master? I think there might be an argument for merging it to 2.8.

yep, my mistake, I will take a new pull request to 2.8. thank you.

**Comment by ButterflyTech** [comment]
I create a new pr for 2.8: https://github.com/LinuxCNC/linuxcnc/pull/698

andypugh <notifications@github.com> 于2020年3月17日周二 上午8:01写道：

**Comment by andypugh** [comment]
Superseded and closed.

**Pull request closed without merging**
