### PR TITLE
fix up canterp handling

### PR DESCRIPTION
**Pull request by SebKuzminsky**

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
This change was motivated by the sim/axis/canterp.ini config failing to start when running from the debian package (it works fine with run-in-place).

The problem is that unlike `lib/` in our repo, our deb doesn't include `/usr/lib/libcanterp.so`, only `/usr/lib/libcanterp.so.0`, i guess since it gets mangled by the shared-library smarts in debhelper (which is understandable and reasonable):

~~~
root@bc75b5a04a79:~# dpkg -s linuxcnc-uspace | grep Version
Version: 1:2.9.0~pre1.210.g02c173d50

root@bc75b5a04a79:~# dpkg -L linuxcnc-uspace | grep /usr/lib/lib
/usr/lib/libcanterp.so.0
/usr/lib/liblinuxcnchal.so.0
/usr/lib/liblinuxcncini.so.0
/usr/lib/libnml.so.0
/usr/lib/libposemath.so.0
/usr/lib/libpyplugin.so.0
/usr/lib/librs274.so.0
/usr/lib/libtooldata.so.0

root@bc75b5a04a79:~# ls -la /usr/lib/lib*.so*
-rw-r--r-- 1 root root 1517856 Dec 23  2020 /usr/lib/libBLT.2.5.so.8.6
-rw-r--r-- 1 root root  329680 Dec 23  2020 /usr/lib/libBLTlite.2.5.so.8.6
lrwxrwxrwx 1 root root      22 Oct 29 14:12 /usr/lib/libarmadillo.so.11 -> libarmadillo.so.11.4.2
-rw-r--r-- 1 root root   69480 Oct 29 14:12 /usr/lib/libarmadillo.so.11.4.2
-rw-r--r-- 1 root root   22608 Jan  3 12:51 /usr/lib/libcanterp.so.0
lrwxrwxrwx 1 root root      17 Dec  1 10:28 /usr/lib/libdfalt.so.0 -> libdfalt.so.0.0.0
-rw-r--r-- 1 root root  528304 Dec  1 10:28 /usr/lib/libdfalt.so.0.0.0
-rw-r--r-- 1 root root   55320 Jan  3 12:51 /usr/lib/liblinuxcnchal.so.0
-rw-r--r-- 1 root root   39096 Jan  3 12:51 /usr/lib/liblinuxcncini.so.0
lrwxrwxrwx 1 root root      20 Dec  1 10:28 /usr/lib/libmfhdfalt.so.0 -> libmfhdfalt.so.0.0.0
-rw-r--r-- 1 root root  165984 Dec  1 10:28 /usr/lib/libmfhdfalt.so.0.0.0
-rw-r--r-- 1 root root  331168 Jan  3 12:51 /usr/lib/libnml.so.0
lrwxrwxrwx 1 root root      14 Dec  1 12:52 /usr/lib/libogdi.so.4 -> libogdi.so.4.1
-rw-r--r-- 1 root root  113096 Dec  1 12:52 /usr/lib/libogdi.so.4.1
-rw-r--r-- 1 root root  120928 Jan  3 12:51 /usr/lib/libposemath.so.0
-rw-r--r-- 1 root root   59568 Jan  3 12:51 /usr/lib/libpyplugin.so.0
lrwxrwxrwx 1 root root      28 Nov 20  2021 /usr/lib/libqscintilla2_qt5.so.15 -> libqscintilla2_qt5.so.15.
0.0
lrwxrwxrwx 1 root root      28 Nov 20  2021 /usr/lib/libqscintilla2_qt5.so.15.0 -> libqscintilla2_qt5.so.1
5.0.0
-rw-r--r-- 1 root root 3937216 Nov 20  2021 /usr/lib/libqscintilla2_qt5.so.15.0.0
-rw-r--r-- 1 root root 1831792 Jan  3 12:51 /usr/lib/librs274.so.0
-rw-r--r-- 1 root root  166176 Sep 23  2019 /usr/lib/libtclx8.4.so.0
-rw-r--r-- 1 root root   34816 Jan  3 12:51 /usr/lib/libtooldata.so.0
lrwxrwxrwx 1 root root      13 Dec  1 12:52 /usr/lib/libvpf.so.4 -> libvpf.so.4.1
-rw-r--r-- 1 root root  260368 Dec  1 12:52 /usr/lib/libvpf.so.4.1
~~~

This made me realize that canterp isn't anything like liblinuxcnchal.so or libposemath.so, which really are shared libraries.  No executable in linuxcnc-uspace.deb is dynamically linked against libcanterp.so.

~~~
root@bc75b5a04a79:~# ldd /usr/bin/genserkins 
        linux-vdso.so.1 (0x00007fffda3f2000)
        liblinuxcnchal.so.0 => /lib/liblinuxcnchal.so.0 (0x00007f6ce78d2000)
        libposemath.so.0 => /lib/libposemath.so.0 (0x00007f6ce78b3000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6ce77d4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6ce75f3000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6ce73d9000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6ce73b7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6ce78fc000)
~~~

**Comment by SebKuzminsky** [comment]
Looks like a packaging collision between linuxcnc-uspace and linuxcnc-uspace-dev, i'll debug it.

**Comment by petterreinholdtsen** [comment]
Look good to me, but not sure I understand the build rules.

**Comment by SebKuzminsky** [comment]
The build rule changes are all trying to fix the problem that makes the canterp.ini config not work when running from the debian package: we were incorrectly treating canterp as a library, which it's not.  It's more like our uspace realtime components: a shared object intended to be dlopened by one specific application (task, in this case), for use as an optional plugin module. 

The canterp Submakefile changes are threefold (maybe I should have made it 3 commits for clarity):
1. Build `../lib/linuxcnc/canterp.so`, not `../lib/libcanterp.so.0`.  This is because canterp is not a library, which makes the old name confusing.
2. Rename the internal variables so they don't make it seem like canterp is a library (`LIBCANTERPSRCS` became `CANTERPSRCS`).
3. Switch from `@` to `$(Q)` to optionally hide the build steps.  This is the convention used throughout the rest of the linuxcnc makefiles.  `make` is mostly silent because `$(Q)` expands to `@`; `make V=1` shows the build commands because `$(Q)` expands to the empty string.

The top-level Makefile changes are simpler (though it took me two commits to get it right): install canterp from the new place (`../lib/linuxcnc/canterp.so` instead of `../lib/libcanterp.so`), and then make sure it doesn't *also* get installed into the linuxcnc-uspace-dev deb by switching from a make-style pattern match to a glob (because in make, `../lib/%.so` matches `../lib/linuxcnc/canterp.so` since `%` does *text* matching, and doesnt know anything about the syntax of filesystem paths).

**Pull request merged**
