### PR TITLE
Added docs build rules for German (de) HTML and PDF.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by hansu** [comment]
Why not merge these two PRs?

**Comment by petterreinholdtsen** [comment]
The failing tests are due to bugs in the de.po files that have gone undetected until now.

**Comment by petterreinholdtsen** [comment]
I added a commit to fix the german issues.  These should be fixed in Weblate instead, and be removed from this pull request before it is merged into master, to avoid git conflicts on Weblate.

**Comment by hansu** [comment]
>msgid "images/encoder-counts-math.png"
>msgstr "images/encoder-zählt-math.png"

Haha that's why I mentioned some time ago to limit the scope of what is going into the documentation.pot...

>I added a commit to fix the german issues. These should be fixed in Weblate instead, and be removed from this pull request before it is merged into master, to avoid git conflicts on Weblate.

So why haven't you just done it in Weblate?

**Comment by hansu** [comment]
I corrected them in Weblate so you can remove that fix here and check if it builds.

**Comment by petterreinholdtsen** [comment]
I decided to ask @smoe to train the German translators instead of fixing all my self, hoping to avoid such issues in the future.

**Comment by smoe** [comment]
Builds. Thank you both.

**Comment by hansu** [comment]
I think it is more caused by using the automatic translation suggestions. If you look through them, everything looks fine, but it's easy to overlook that the filename is wrongly translated as well.

**Comment by petterreinholdtsen** [comment]
[Hans]
> I corrected them in Weblate so you can remove that fix here and check
> if it builds.

I'll do that as soon as the Weblate fixes make it into master. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
>I'll do that as soon as the Weblate fixes make it into master. :)

Ah, you are right :)

**Comment by petterreinholdtsen** [comment]
After merging from Weblate, it look like there is still one build breaking error in de.po that need to be fixed.

**Comment by hansu** [comment]
> After merging from Weblate, it look like there is still one build breaking error in de.po that need to be fixed.

Which one? All builds looks green ...

**Comment by smoe** [comment]
Fixed.

**Comment by petterreinholdtsen** [comment]
Pulled in the latest changes from Weblate, and now the German build work.

**Pull request merged**
