### PR TITLE
Improve searching LinuxCNC components from GNOME menu

### PR DESCRIPTION
**Pull request by dwrobel**
Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

### CODE REVIEW

**Comment by jepler** [comment]
I reverted this because it fails desktop-file-validate, which unfortunately is only performed during the package build.  036ffdb2745f52d75c2a56af563de0c0ee3585c2  http://buildbot.linuxcnc.org/buildbot/builders/4007.deb-precise-i386/builds/5428
```
    for F in debian/extras/usr/share/applications/linuxcnc-latency.desktop debian/extras/usr/share/applications/linuxcnc-gcoderef.desktop debian/extras/usr/share/applications/linuxcnc.desktop debian/extras/usr/share/applications/linuxcnc-gettingstarted.desktop debian/extras/usr/share/applications/linuxcnc-halmanual-fr.desktop debian/extras/usr/share/applications/linuxcnc-integratormanual-fr.desktop debian/extras/usr/share/applications/linuxcnc-manualpages.desktop debian/extras/usr/share/applications/linuxcnc-usermanual-fr.desktop debian/extras/usr/share/applications/linuxcnc-documentation.desktop debian/extras/usr/share/applications/linuxcnc-gettingstarted-fr.desktop debian/extras/usr/share/applications/linuxcnc-integratorinfo.desktop debian/extras/usr/share/applications/linuxcnc-pncconf.desktop debian/extras/usr/share/applications/linuxcnc-gcoderef-vi.desktop debian/extras/usr/share/applications/linuxcnc-gcoderef-fr.desktop debian/extras/usr/share/applications/linuxcnc-stepconf.desktop; do \
                    desktop-file-validate $F; \
            done
    debian/extras/usr/share/applications/linuxcnc-latency.desktop: error: value "cnc;linuxcnc;cncprog;benchmark" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-gcoderef.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc.desktop: error: value "cnc;linuxcnc;cncprog" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-gettingstarted.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-halmanual-fr.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-integratormanual-fr.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-manualpages.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-usermanual-fr.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-documentation.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-gettingstarted-fr.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-integratorinfo.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-pncconf.desktop: error: value "cnc;linuxcnc;cncprog;cncconfig" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-gcoderef-vi.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-gcoderef-fr.desktop: error: value "cnc;linuxcnc;cncdoc" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    debian/extras/usr/share/applications/linuxcnc-stepconf.desktop: error: value "cnc;linuxcnc;cncprog;cncconfig" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
    make: *** [install] Error 1
    dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```

**Comment by dwrobel** [comment]
>I reverted this because it fails desktop-file-validate, which unfortunately is only performed during the package build.

I'm also using it in fedora packaging with the verification and in my case:
```
$ desktop-file-validate debian/extras/usr/share/applications/*.desktop
$ echo $?
0
$ desktop-file-validate --help
Usage:
  desktop-file-validate [OPTION?] <desktop-file>...

Validate desktop entry files according to the Desktop Entry specification 1.1.
For information about this specification, see:
	http://freedesktop.org/wiki/Specifications/desktop-entry-spec

Help Options:
  -h, --help               Show help options

Application Options:
  --no-hints               Do not output hints to improve desktop file
  --no-warn-deprecated     Do not warn about usage of deprecated items
  --warn-kde               Warn if KDE extensions to the specification are used
```
Validator comes from the package version:
```
$ rpm -qf $(which desktop-file-validate)
desktop-file-utils-0.24-1.fc31.x86_64
```

As you can see it verifies the files against "Desktop Entry specification 1.1."
Would you please share what "Desktop Entry specification" version your tool is checking against?

**Comment by jepler** [comment]
The specific error shown above occurred on Ubuntu Precise.

The following supported Debian and Ubuntu versions failed:

4007.deb-precise-i386 | 4008.deb-precise-amd64 | 4009.deb-precise-rtai-i386 | 4014.deb-wheezy-rtpreempt-i386 | 4015.deb-wheezy-rtpreempt-amd64 | 4016.deb-wheezy-i386 | 4017.deb-wheezy-amd64 | 4018.deb-wheezy-rtai-i386 | 4019.deb-jessie-rtpreempt-i386 | 4020.deb-jessie-rtpreempt-amd64 | 4021.deb-jessie-i386 | 4022.deb-jessie-amd64
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Debian Jessie has package version 0.22-1 https://packages.debian.org/jessie/desktop-file-utils

```
jepler@babs:/tmp/desktop-file-utils-0.22$ ./src/desktop-file-validate --help
Usage:
  desktop-file-validate [OPTION?] <desktop-file>...

Validate desktop entry files according to the Desktop Entry specification 1.1.
For information about this specification, see:
	http://freedesktop.org/wiki/Specifications/desktop-entry-spec

Help Options:
  -h, --help               Show help options

Application Options:
  --no-hints               Do not output hints to improve desktop file
  --no-warn-deprecated     Do not warn about usage of deprecated items
  --warn-kde               Warn if KDE extensions to the specification are used
```9

https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/blob/master/NEWS#L37

**Comment by dwrobel** [comment]
@jepler Thank you for the comprehensive information.

>Newer versions apparently relaxed this requirement, but you'll need to respect it for old systems:

I also found in the [desktop entry specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) that:

>  the value of the key may be optionally terminated by a semicolon.

So, I added in https://github.com/LinuxCNC/linuxcnc/pull/880 the optional trailing semicolon so satisfy the older version of the `desktop-file-validate` tool.

**Pull request merged**
