### PR TITLE
Formatted README

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
<br>

*Please check the **[Preview]**.*

<br>
<br>

### Changes

- General formatting / spacing
- Added license badges
- Added quicklinks

<br>

*Might wanna adjust the quicklinks, since the website is down rn*
*I couldn't look for the documentation url and other useful links.*

<br>
<br>

### Repository Suggestions

- **Add Tags**

- ***[Disable Unused Tabs][Tabs]***:

  - `Projects`

<br>

[Preview]: https://github.com/ElectronicsArchiver/linuxcnc
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md

### CODE REVIEW

**Comment by andypugh** [comment]
The Build link should be http://linuxcnc.org/docs/stable/html/code/building-linuxcnc.html and docs should be http://linuxcnc.org/docs/stable/html/
However I suspect that an install link might be more useful than the build link (http://linuxcnc.org/docs/stable/html/getting-started/getting-linuxcnc.html)

The text formatting of the disclaimer looks odd to me.

**Comment by ElectronicsArchiver** [comment]
Will adjust the links later, thanks.

The disclaimer uses fullwidth characters and a code-block to emphasize the warning. In the original, everything was just bold and the 'Extremely' was less visible, so now the sections are more differentiable. I can adjust the spaces between the fullwidth word if you'd like.

**Comment by andypugh** [comment]
Sorry to be picky. But I am not sure about the change to docs/src/code/building-linuxcnc.adoc
That is the file used to build the file referred to. So on the web site that will be a circular link, I think.

**Comment by ElectronicsArchiver** [comment]
Right, will undo that~

**Comment by andypugh** [comment]
Still not sold on the character spacing. But I will merge it. (I want to work on the wording a little too)

**Pull request merged**
