### PR TITLE
Fix compile error with "configure --enable-toolnml"

### PR DESCRIPTION
**Pull request by heeplr**

### CODE REVIEW

**Comment by gmoccapy** [comment]
stuttgart meeting agrees this will be obsolete when @rene-dev is done with the sqlite tooltable.
anything tooltable related should not be a compiletime option.

**Comment by heeplr** [comment]
> anything tooltable related should not be a compiletime option.

It certainly shouldn't be a _broken_ compiletime option. This is just two lines fixing regression bugs that currently exist (unrelated to their future fate).

**Comment by c-morley** [comment]
Maybe whoever 'Stuttgart meeting' is - should not close this until the discussion is done.

**Comment by rene-dev** [comment]
In my opinion this can be entirely removed. Can anyone explain how this is used, or why it would be useful for anything?

**Comment by heeplr** [comment]
@rene-dev please refer to my explaination in the corresponding PR #2676 so we don't duplicate the discussion

**Comment by petterreinholdtsen** [comment]
Please rebase on top of latest master, so the CI jobs have a chance of succeeding.

**Comment by rene-dev** [comment]
I see that it should at least compile.
we are currently working a bunch of issues and PRs at the linuxcnc meeting in stuttgart. https://linuxcnc.org/2023/09/16/LinuxCNC-Meetup-in-Stuttgart/

**Pull request merged**
