### PR TITLE
adding new Icons for LinuxCNC and its manuals

### PR DESCRIPTION
**Pull request by AlexmagToast**
I reworked Chip a little and made themed Icons for different linuxcnc usecases.
apart from the original Chip holding a mill there are now also versions for Lathe, Lasercutter, Plasmacutter, Waterjet and Probeing. Chip also wears appropiate eyewear for the job. 

Also i created Chip holding a book and wearing reading glasses for the documentation. Below is the language written in that language.
One Icon was created for each Language currently supported by Linuxcnc.

Also i created a folder containing the souce files, i used to create the icons. There Text is still text, so it's easyer to change it if needed.

This was discussed here:
https://forum.linuxcnc.org/show-your-stuff/32672-linuxcnc-logo

submitted under the terms of GPL Version 2

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
[Alexander Richter]
> One Icon was created for each Language currently supported by
> Linuxcnc.

Incorrect language code?

> A debian/extras/usr/share/icons/hicolor/scalable/apps/linuxcnc_no.svg (0)

The language code handlet by LinuxCNC is 'nb' ('Norwegian Bokmål', not
'no' = 'Norwegian'. The 'no' language code is obsolete, and the codes to
use are 'nb' or 'nn').

--
Happy hacking
Petter Reinholdtsen

**Comment by andypugh** [comment]
> The language code handlet by LinuxCNC is 'nb' ('Norwegian Bokmål', not 'no' = 'Norwegian'

Fixed in 9d5b6554b827ff6c62c3a0419d07af533805e077

**Comment by hansu** [comment]
Very nice :+1: 
I only wonder why some of the language names begin with an uppercase letter and some not. Is that different from language to language?

**Comment by silopolis** [comment]
Awesome! 😍

**Pull request merged**
