### PR TITLE
change halscope to Gtk3

### PR DESCRIPTION
**Pull request by rene-dev**
Gtk2 is officially End of life. https://blog.gtk.org/2020/12/16/gtk-4-0/
This is the first step in merging GTK3 changes in master.

this closes https://github.com/LinuxCNC/linuxcnc/issues/864
Thanks a lot to @havardAasen 

The list in the halmeter and halscope now can be searched.

Im making this a separate PR, as unlike Norberts any my work on glade, gmoccapy and the other UIs this is already fully functional, and doesn't break any configurations, but you do need to install libgtk-3-dev.

this also changes CI version to ubuntu 18.04 as this is now what master requires according to
https://github.com/LinuxCNC/linuxcnc/pull/743/
and
http://wiki.linuxcnc.org/cgi-bin/wiki.pl?MinimumSoftwareVersions

### CODE REVIEW

**Comment by rene-dev** [comment]
Does anyone know why the packaging fails?

**Comment by havardAasen** [comment]
It's lintian that throws an error. It complains about the timestamp in
debian/changelog
The newest entry has an older timestamp then the previous entry.

tir. 18. mai 2021, 00:18 skrev Rene Hopf ***@***.***>:

**Comment by rene-dev** [comment]
ok, that has nothing to do with these change. the file is the same in master.

**Comment by rene-dev** [comment]
ah, this is probably related to ubuntu 18.04

**Comment by havardAasen** [comment]
I think so too.

Would it be possible to add a new changelog entry called "unreleased", with
a timestamp which always gets updated when a release has been made, or
merged into master? Perhaps have this as part of the release routine?

Developers would also have the possibility to update the changelog when
committing changes and fixes.

tir. 18. mai 2021, 22:13 skrev Rene Hopf ***@***.***>:

**Comment by rene-dev** [comment]
ah, fixed now. That would be a good idea, sadly I dont know anything about debian packaging, and how this is done properly.
I think the issue is that the changelog was added at a later date, because it wasnt done in time.

**Pull request merged**
