### PR TITLE
Make G7x code build on precise

### PR DESCRIPTION
**Pull request by jepler**
This makes it build on a freshly installed precise/uspace system.  No testing was performed.

### CODE REVIEW

**Comment by jepler** [comment]
@mark-v-d your comment would be appreciated.

**Comment by mark-v-d** [comment]
The conversion from "dkldkldf"s -> "dkldkldf" is incorrect, this will
cause linuxcnc to crash. This should be std::string("dkldkldf") instead,
which I also did in the follow-up patch.

Changing the 1i to std::complex<double>{0,1} is ok, I used a constexpr
in the follow-up patch.

Moving the initialisation of some members to the constructor is OK.

Removing the override is OK.

Replacing std::make_unique is OK.

**Comment by mark-v-d** [comment]
Replacing emplace with emplace_back is incorrect

If you can't use emplace, use insert. For example
        insert(n,std::unique_ptr<round_segment>(new round_segment(
                distance>0,(*p)->ep(),center,(*n)->sp())));

**Comment by mark-v-d** [comment]
I've just pushed your changes to my archive. I think that updates the g71_test branch
and builds on the buildbot. The version I pushed works for me.

**Comment by andypugh** [comment]
I think this one was superseded?

**Pull request closed without merging**
