### PR TITLE
Gmoccapy: fix gcode view issue (2.8)

### PR DESCRIPTION
**Pull request by hansu**
Fixes these three issues according to
https://forum.linuxcnc.org/gmoccapy/43045-after-saving-ngc-file-ask-for-do-you-want-to-exit-without-saving-the-changes
1. When editing a G-code file, a change was detected even when only the cursor changed.
2. After saving the changes, a warning for unsaved changes appeared again.
3. After creating a new file and 'save as', the save button was disabled.

### CODE REVIEW

**Comment by c-morley** [comment]
Does this not break the feature for non Gmoccapy code?

**Comment by hansu** [comment]
That's no problem, because only Gmoccapy used the 'change'-signal.

**Comment by c-morley** [comment]
How do you know that? There are custom screens out in the wild that we can not predict what code they use.
2.8 is legacy code. We try hard not to break production code.
I also thought gscreen used the changed feature - but maybe it uses a different mechanism.

**Comment by hansu** [comment]
Ah, you mean screens outside the LinuxCNC repository. I understand. I'll provide a solution without changing the interface. But for  the master branch we can have this solution, right?

**Comment by hansu** [comment]
> I also thought gscreen used the changed feature - but maybe it uses a different mechanism.

Gscreen directly polls the get_modified() function of the SourceViews text buffer.

**Comment by c-morley** [comment]
> Ah, you mean screens outside the LinuxCNC repository. I understand. I'll provide a solution without changing the interface. But for the master branch we can have this solution, right?

Yes. With released code one must be careful not to break code even if it was used wrong.
master branch one can deviate code much more, though I wouldn't break code without good reason.

**Comment by hansu** [comment]
Now without changing the interface of hal_sourceview :slightly_smiling_face:

**Comment by c-morley** [comment]
Thank you!

**Pull request merged**
