### PR TITLE
Fix iopl issue with kernel_lockdown (secure boot)

### PR DESCRIPTION
**Pull request by safarir**
This is my quick fix for issue #1272 

Please let me know if you have a better idea

Thank you

### CODE REVIEW

**Comment by jepler** [comment]
Thanks. The ci failed, but it was unclear why so I restarted it.

**Comment by rene-dev** [comment]
@jepler reasin it failed: https://github.com/actions/virtual-environments/issues/3287

**Comment by safarir** [comment]
Quick question, how will this fix be apply on the 2.7 and 2.9 branch. Is there some automatic merging happening somehow ? I could not find any instructions ...

**Comment by rene-dev** [comment]
It will be merged into master. I don't think 2.7 still receives updates.

**Pull request merged**
