### PR TITLE
Adds PORT pin type to hal.

### PR DESCRIPTION
**Pull request by curtdutt**
A HAL port pin is a hal pin that acts as a real time one way byte oriented data stream An output port on any component may be connected to an input port on any other component via a signal. Data written on the output pin becomes accessible to the input pin. A HAL port signal may link only a single writer and a single reader. A port buffers data with a user definable buffer size.

Includes:
	Documentation on how to use a port object.
	a ctypes wrapper for the hal api (pyhal.py)
	a test to exersice hal port code along with pyhal.py
	changes to allow halcmd to understand and manipulate ports.

### CODE REVIEW

**Comment by andypugh** [comment]
OK, let's see how this goes. 
It seems like a nice for the Mesa "stream" data type and the 7i73 LCD amongst other things.

**Comment by curtdutt** [comment]
Great thank you Andy,

and thanks to everyone else for their support and help over the last year.

I'll get the laser code pull request set up next.

**Comment by andypugh** [comment]
Buildbot isn't happy:
http://buildbot.linuxcnc.org/buildbot/builders/1301.rip-precise-rtai-i386/builds/5266
(click on stdio to see the compile error)

**Comment by curtdutt** [comment]
ok ill get it fixed first thing tomorrow.

why didnt,this show up in travis? is there a way i can reproduce this on
one of my machines?

**Comment by curtdutt** [comment]
Ok pull request for the fix created.

**Comment by andypugh** [comment]
> ok ill get it fixed first thing tomorrow. why didnt,this show up in travis?

Looking at the buildbot waterfall plot: http://buildbot.linuxcnc.org/buildbot/waterfall it looks like only the RTAI builds failed. It is possible (likely, even) that the Travis builds don't run on an RTAI kernel.

**Comment by andypugh** [comment]
Minor thing, but builds are showing a warning:
http://buildbot.linuxcnc.org/buildbot/builders/1402.rip-wheezy-rtpreempt-i386/builds/4368/steps/compile/logs/warnings%20%285%29

(And they are not wrong)

**Comment by andypugh** [comment]
Literally seconds of looking have not turnedup the sample code pull request. Did you create it?

**Comment by curtdutt** [comment]
I will do my best to get the pull request together ASAP. Stay tuned.

**Pull request merged**
