### PR TITLE
Adds G84/G74 Floating Tapping Cycles and Possibility to ignore Spindle_at_speed before feed move

### PR DESCRIPTION
**Pull request by terkaa**

### CODE REVIEW

**Comment by jepler** [comment]
I suggest moving the restores of the override state into the g74/g84-specific code:
d34932b97b2812d1246d67cccae44ccb66a2f73e

to behave properly under rs274 sai, the implementation of GET_EXTERNAL_xxx_OVERRIDE needs to be fixed: b624266abc220ef55b32bfe86a2cc4191077d879

**Comment by terkaa** [comment]
Issues should be fixed now

**Comment by terkaa** [comment]
It seems I still have some work with Expected test...
Tomorrow

**Comment by terkaa** [comment]
Fixed tests for these

**Comment by terkaa** [comment]
Still fixed 2 failing tests

**Comment by andypugh** [comment]
This has been hanging around a long time. 
Looking through the code it looks like G74 and G84 are now supported, can this ull request be closed?

**Pull request closed without merging**
