### PR TITLE
Merge 2.9 into master - conflicts

### PR DESCRIPTION
**Pull request by hansu**
The other conflics are easy to solve but here I am not sure which one is the correct wording:

`If present, local UI files` or `If present, local UI/QSS/python files`

I guess @c-morley should know that.

```
<<<<<<< HEAD
//FIXME Does that applies to .ui files only or handler.py and qss too ?
//FIXME How does overriding/inheritance actually works ?

If present, local UI files in the configuration folder will be loaded instead of the stock UI files.

Local UI files allow you to use your customized designs rather than the default screens.

QtVCP will look for a folder named _<screen_name>_ (in the launched configuration folder that holds the INI file).
=======
If present, local UI/QSS/python files in the configuration folder will be loaded instead of the stock UI files.

Local UI/QSS/python files allow you to use your customized designs rather than the default screens.

QtVCP will look for a folder named <screen_name> (in the launched configuration folder that holds the INI file).
>>>>>>> 2.9
```

### CODE REVIEW

**Comment by c-morley** [comment]
https://github.com/LinuxCNC/linuxcnc/commit/25e07f808af318ce5783e73105add4fe312b81b2#r102843546

**Comment by hansu** [comment]
@smoe: https://github.com/LinuxCNC/linuxcnc/commit/25e07f808af318ce5783e73105add4fe312b81b2#r102859688

**Comment by smoe** [comment]
What do you want me to do?

**Comment by hansu** [comment]
> What do you want me to do?

Not more as you already did. I only wanted to make sure that you get notified by that comment.

**Comment by hansu** [comment]
Thanks

**Pull request merged**
