### PR TITLE
Halshow: New features

### PR DESCRIPTION
**Pull request by hansu**
Time to introduce some new features...

- Added possibility to change the width of the tree view
- Can now add multiple pins from text selection
- (Added icon)

halshow_add_as_pins_m

#           ⇩

halshow_add_as_pins-2

- Added possibility to hide the tree view
   
    halshow_new_2

But I couldn't decide on whether to use a raised frame around the tree view or not. This is also possible:

halshow_frame_around

Just tell me what you think. i can adapt it.

### CODE REVIEW

**Comment by c-morley** [comment]
Sounds great! I have no strong opinion on the frame look.

**Comment by phillc54** [comment]
> Sounds great! I have no strong opinion on the frame look.

+1

**Comment by hansu** [comment]
You guys are a really great support to make a decision which design to use 😄 .
So if you have no strong opinion for one design (me either) - feel free to merge this if you like it.

**Comment by dwrobel** [comment]
@hansu This change seems to broke `halshow` for system-wide installation mode _(in my case from rpm)_:
```
$ halshow
couldn't open "/usr/lib64/tcl8.6/linuxcnc2.9.0/bin/halshow_icon.png": no such file or directory
    while executing
"image create photo applicationIcon -file [file join [file dirname [info script]] halshow_icon.png]"
    (file "/usr/lib64/tcl8.6/linuxcnc2.9.0/bin/halshow.tcl" line 37)
    invoked from within
"source /usr/lib64/tcl8.6/linuxcnc2.9.0/bin/halshow.tcl"
    (file "/usr/bin/halshow" line 2)
```
I couldn't find where the `halshow_icon.png` is referenced in `Makefile` to be installed:

```
$ git grep  -- halshow_icon.png 
tcl/bin/halshow.tcl:image create photo applicationIcon -file [file join [file dirname [info script]] halshow_icon.png]
```

**Comment by hansu** [comment]
@dwrobel can you please try with this branch: https://github.com/hansu/linuxcnc/tree/fix-iconpath ?

**Comment by hansu** [comment]
If you give me a hint how to install it, I can also test it. I always get this, even though I have never selected `--enable-run-in-place`:
```
Makefile:592: *** You configured run-in-place, but are trying to install.
For an installable version, run configure without --enable-run-in-place
and rebuild.
```

**Pull request merged**
