### PR TITLE
Added new tests/classicladder/estop/ check.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
This tests the estop behavour in classicladder, pressing an external estop button, checking estop activates, and then reset estop and ensure it clears.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
The test seem to be working, but I am not confident I am actually testing classicladder behaviour or just standard LinuxCNC behaviour.

**Comment by c-morley** [comment]
If you just want to test classicladder, why not got run it alone in a HAL script rather then running it with linuxcnc?
But i would think the most important things to test would be quite difficult - the GUI.
Do you know what you function would like to test?

**Comment by petterreinholdtsen** [comment]
[c-morley]
> If you just want to test classicladder, why not got run it alone in a
> HAL script rather then running it with linuxcnc?

Mostly because I do not know how to do that.  Also, I suspect using the
python DISPLAY approach allow for more complex test logic.

> But i would think the most important things to test would be quite
> difficult - the GUI.

Perhaps you can try to come up with a test for this, and put it next to
the estop test in tests/classicladder/?

> Do you know what you function would like to test?

My goal is to make sure classicladder have at least some tests executed
automatically to gain some confidence that
<URL: https://github.com/LinuxCNC/linuxcnc/pull/1657 > do not break
everything.  I believe the upgrade have waited long enough.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Trying to figure out if the test actually check the classicladder implementation, I removed the --nogui option in classicladder-estop.hal and modified the plc program to see if it would break the test.  First I changed some 'normally open' and 'normally closed' inputs to their opposite, without much luck, then then I removed some of the virtual wiring in the PLC, and this would indeed break the test.  This make me believe the test is actually exercising part of classicladder and thus testing what I intend it to test.

This make it believe it is ready to go into master, where there are currently not one test for classicladder in tests/.

**Comment by c-morley** [comment]
I though a HAL only test might be easier, but if you are successful with what you have that's great.
I don't know how to write GUI tests and only really understand the premise of our existing tests.

Testing the basic bit input to output is a fine start on successful testing.
I think I was was just thinking out loud that the parts that are mostly likely to have bugs are the hardest to write a test for.
some things come to mind to test:
-float value  to s32 value (I now wish I rounded them instead)
-function checks on the fancy elements
-modbus
-reasonable timer accuracy
-above related to servo period
-make sure adjusting the number of elements doesn't overlap others.


anyways as for the new classicladder, we should probably just push it into master now that there is a 2.9 branch - no test better them having more people using it.

**Comment by petterreinholdtsen** [comment]
[c-morley]
> I though a HAL only test might be easier, but if you are successful
> with what you have that's great.

I am at least somewhat successfull, but I am kind of flying blind here
with very superficial knowledge of classicladder while having fairly
good control over the test mechanics.

> I don't know how to write GUI tests and only really understand the
> premise of our existing tests.

It is possible, at least.  Feel free to check out the test-gui branch in
my github clone of linuxcnc for a sketch and example.

> Testing the basic bit input to output is a fine start on successful
> testing.

> I think I was was just thinking out loud that the parts that are
> mostly likely to have bugs are the hardest to write a test for.
> some things come to mind to test:
> -float value  to s32 value (I now wish I rounded them instead)
> -function checks on the fancy elements
> -modbus
> -reasonable timer accuracy
> -above related to servo period
> -make sure adjusting the number of elements doesn't overlap others.

Sound useful, but I must admin I do not understand what you are talking
about.  I so far just barely understand classicladder stuff, and have
not come across any of the concepts you list here. :)

> anyways as for the new classicladder, we should probably just push it
> into master now that there is a 2.9 branch - no test better them
> having more people using it.

Well, I believe automated unit tests are a lot better than throwing it
at surprised users, but I agree.  We should get it into master now and
write tests for any problems we discover, to ensure future upgrades
become easer and we can have confidence that classicladder functionally
stay inteact as we move forward.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by andypugh** [comment]
Lets put it in and see how it goes.

**Pull request merged**
