### PR TITLE
Uspace uid handling master

### PR DESCRIPTION
**Pull request by jepler**
This fixes the mint 18 dash euid problem (rebased onto master since other branch has conflicts when merged to master)

### CODE REVIEW

**Comment by jepler** [comment]
pcw confirms on irc that this fixed hm2_eth on his mint18 system too.

**Comment by jepler** [comment]
incorporated, but github won't figure it out because it was rebased before pushed.

**Comment by jepler** [comment]
@trasz I think this may be helpful for the freebsd port, it's in master branch now...

**Comment by trasz** [comment]
Thanks; I hope I'll be able to do some more porting work in a few weeks.

**Pull request closed without merging**
