### PR TITLE
Adds laser raster and vector control components.

### PR DESCRIPTION
**Pull request by curtdutt**
laserpower.comp - Scales laser output based upon velocity raster.comp - Controls laser power based upon preprogrammed bitmap data.

Includes associated sim configuraion to demonstrate laser component integration.

Includes basic test for raster component.

Teaches halcompiler about port pins.
     Adjusts pin component structure member names to prevent conflicts with preprocessor macros.

### CODE REVIEW

**Comment by andypugh** [comment]
Thanks for this

**Comment by petterreinholdtsen** [comment]
The test code call 'realtime start', which uses a binary not present in
Debian.  Also, the test leave behind a background process when it fail,
causing the test suite to fail.  I'm working on a patch to solve the
latter.

What is the 'realtime start' call supposed to do?  It do not seem to be
needed when I test it.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by andypugh** [comment]
os.system("realtime start") shouldn't be necessary anyway, the HAL file has the required "start" command. 

However LinuxCNC does have a "realtime" script, so it should work: https://github.com/LinuxCNC/linuxcnc/blob/master/scripts/realtime.in

**Comment by petterreinholdtsen** [comment]
[andypugh]
> os.system("realtime start") shouldn't be necessary anyway, the HAL
> file has the required "start" command.

Then it should be removed.

> However LinuxCNC does have a "realtime" script, so it should work:
> https://github.com/LinuxCNC/linuxcnc/blob/master/scripts/realtime.in

It is not found when runtest is executed on github, which is the reason
I noticed it.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request merged**
