### PR TITLE
Gmoccapy i18n 2.7

### PR DESCRIPTION
**Pull request by jepler**
This is like #323 but for 2.7.  @SebKuzminsky OK to merge, or would you prefer to see it in master only?  This is to support work like #319 which is targeted at 2.7.

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
If a suitable version of intltool is available on all our supported platforms, then this PR looks good to me.

**Comment by jepler** [comment]
At least a package called "intltool" is available everywhere.  I have not arranged to test this branch on buildbot, though.  Do you want me to?

**Comment by jepler** [comment]
I asked buildbot to build this.  I think it'll come up as http://buildbot.linuxcnc.org/buildbot/builders/0000.checkin/builds/5118 though that URL isn't live yet (another build is in progress).

**Comment by jepler** [comment]
@SebKuzminsky thanks to your work we got a green on buildbot at https://github.com/tpaviot/pythonocc-core -- how do you feel about merging now?

**Pull request merged**
