### PR TITLE
M98/M99 subprograms

### PR DESCRIPTION
**Pull request by zultron**
(Originally introduced in [emc-developers](https://sourceforge.net/p/emc/mailman/message/34577019/))

This patch implements subprograms as defined with a bare numbered
O-word, called with `M98` and returned from with `M99`.  This common
style of subprogram is used in Fanuc, Haas and other controllers.
## Implementation

In essence, `M98` and `M99` are O-words.  O-words are handled
specially compared to M- and G-words, both when being read
(e.g. parsed earlier in interp loop than other codes) and when being
executed (e.g. own translation unit with functions for searching and
seeking across g-code file blocks).  Therefore, they are implemented
next to other O-word code, and where possible they share the same read
and execute flow.  There is a major semantic difference compared to
traditional rs274ngc subroutines: Execution starts at the beginning of
the file and continues right into a program definition rather than
skipping past.  Such a program definition at the beginning of the
file is the 'main program', although not treated specially by the
interpreter, and `M98` may only call subprograms following the main
program.

In the interpreter's read phase, `M98` call and `M99` return are
handled in `read_o()` at the same time as O-words in `interp_read.cc`.
`M98` is handled much like `O call`.

During execution, `M98 P1` is quite similar to `O1 call`, and they
share the `Interp::execute_call()` function in `interp_o_word.cc`.
Still, `M98` must be distinguished with the special `call_type =
CT_NGC_M98_SUB` to signal to `execute_call()` and `unwind_call()` that
parameters `#1` through `#30` are global.  The call type is also used
to prevent programmers from mixing e.g. `O sub` with `M98` and `M99`.

When `M98` is followed by an L-word (repeat count), it maintains a
loop counter in the parent context `m98_loop_counter` field, and
special logic in `execute_call()` manages call return block location
for iteration.

An `M99` in the main program (top-level call stack) has a special
meaning.  There is no subprogram to return from, so instead it means
to skip back to the beginning of the file and resume execution; in
other words, loop endlessly over the program.  In this case, `M99` is
treated like an M-word handled by `read_m()`, and shares modal group 4
and `convert_stop()` with `M02` and `M30`.

The interpreter cannot handle endless loops because it would queue
canon commands indefinitely without a program end or a queue buster,
and never issue them to task for execution.  Therefore the interpreter
distinguishes the following two subcases of the `M99` endless loop:
- Task:  During real execution of a program, an `M99` in the top-level
  context is treated like a queue-buster.  The interpreter queue is
  flushed to motion (after queuing any link segments) before looping
  back to the program beginning.  Task enables this special behavior
  by calling `interp.set_loop_on_main_m99(true)`.
- SAI, preview, etc.:  When not actually executing, an `M99` in the
  top-level context is treated like an `M30`, program stop.  The
  assumption is that a single loop will be sufficient for
  non-execution use cases, such as to render a tool path preview or
  check the canon commands generated by a program.  This is the
  default behavior, also explicitly set by calling
  `interp.set_loop_on_main_m99(false)`.
## Fanuc and rs274ngc sub call coexistence

The syntax differences create no parsing ambiguities.  During
conversion the two styles share some code paths, where any differences
are handled by the O-word (or M-word) type and call style.

Additional checks ban mixing rs274ngc and Fanuc sub blocks within one
call/return cycle in hopes of reducing confusion arising from careless
mixing and the unintended side-effects of style differences.

If there is reason to disable Fanuc subroutines, do so by placing
`DISABLE_FANUC_STYLE_SUB = 1` in the `[RS274NGC]` section of the
`.ini` file.

### CODE REVIEW

**Comment by zultron** [comment]
Ugh, things keep changing out from under this patch.  I'll fix it later....

**Comment by zultron** [comment]
By the way, this patch depends on the fix in #150.

**Comment by zultron** [comment]
Wow, thing really *are* moving around under me....  This time it's 85210a33.  Trying once more to get a passing build....

**Comment by zultron** [comment]
Yay!  A pass on Travis.

**Comment by andypugh** [comment]
This has been hanging around for years. Do we currently think it is worth doing? 
(meta-question, do we care how Fanuc do things?)

**Comment by zultron** [comment]
Last I heard, @cradek didn't want it because of fears about maintenance, and @mozmck briefly expressed interest.

I thought the real value was in using output from CAM programs that don't have a special LCNC post-processor, but I haven't heard much clamor for the feature.

This feature has been in the PathPilot tree since I wrote it.

Anyway, if there's no interest in merging it, then just bin it.

**Comment by andypugh** [comment]
I have a feeling that CAM programs almost never output subroutines anyway, neither in LinuxCNC nor Fanuc style. Half of them don't even output curves...

**Comment by KimK** [comment]
Oops! Didn't mean to thumbs-up my own comment, I just wanted further information.

**Comment by rene-dev** [comment]
if its in PathPilot, it should be stable I guess? any good reason not to merge it?

**Comment by andypugh** [comment]
I guess it can only ever change existing behaviour if the G-codes are actually used. I think that the risk is small and the benefit is small, but bigger. :-)

**Comment by c-morley** [comment]
well since I see nobody refusing it, seem to have a maintainer, it's in pilotpath with no apparent problems, and master is has no signs of being released soon, I see no reason to leave this out at this time.
My 2 cents

**Comment by zultron** [comment]
@c-morley, thanks for the +1.

I'm happy to be the maintainer.  In order to do better in that regard, I just set the GitHub tracker prefs to "Watching" so that I get updates for all issues in my inbox.

**Comment by samcoinc** [comment]
I think this would be a good addition also.

**Comment by mozmck** [comment]
I am still interested and would probably use sometimes for looping a program.  Since we have a maintainer I would think that would help with @cradek's worry.  The only issue I see currently is that there is a conflict preventing merging with master.  I started to look at it and ran out of time - but it looked like it shouldn't be too hard to resolve.

**Comment by KimK** [comment]
The only thing I noticed was that in 
tests/interp/subs-follow-main/expected
and in 
tests/interp/m98m99/(various places)
that whenever 
N..... SET_G5X_OFFSET(1, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000)
or 
N..... SET_G92_OFFSET(0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000)
were mentioned, they seemed to be initializing with six values (XYZABC) 
instead of the anticipated nine (XYZABCUVW). 
But maybe tests/ only works with the original six values? 
If so, maybe a bug should be filed on tests/ ? 
I'll leave this to the experts to sort out.

**Comment by zultron** [comment]
@KimK, the `SET_G*_OFFSET` canon commands do indeed include the UVW axes.  That output is from the stand-alone interpreter, which is mainly used for testing purposes, and the author must've thought that showing the extra axes in the output wasn't valuable.  The axes are still being passed around behind the scenes, though, and are presumably honored by the interpreter used by task.  See these lines:

https://github.com/LinuxCNC/linuxcnc/blob/master/src/emc/sai/saicanon.cc#L248
https://github.com/LinuxCNC/linuxcnc/blob/master/src/emc/sai/saicanon.cc#L226-L227

In any case, this PR doesn't change anything in that area of the code.

**Comment by KimK** [comment]
OK John, excellent, thanks for explaining that. Well, we'll look forward to hearing when it's ready to merge, then? And this is going into master, can it be cherry-picked to 2.7? PathPilot is based on 2.7 now, right?

**Comment by zultron** [comment]
The current patchset is based on LCNC 2.7, but it's up to maintainers to decide on any merge's target branch.  Forward-merging should be trivial, unless master has any other large changes in interp that I'm unaware of.

As @KimK stated above, the feature could be disabled by default in configs.  That's an option maintainers may choose, and which may play into the choice of target branches.

**Comment by zultron** [comment]
What's left to do before this PR can be merged?  It has extensive unit tests, significant testing, interest from several in the community, a maintainer (me), and no identified issues.

Can a LinuxCNC GitHub organization member please comment here?  Thanks!

**Comment by c-morley** [comment]
If there are no objections by next weekend, i will merge this.

**Comment by zultron** [comment]
Thanks, @c-morley !

**Comment by mozmck** [comment]
I say go ahead!

**Comment by c-morley** [comment]
Thank you for your work, pledging to maintain it and patience on merging it.

**Comment by zultron** [comment]
Thanks, @c-morley.  I'll make good on that pledge.

**Pull request merged**
