### PR TITLE
BugFix: spindle dict item `override_enabled` should use underscore instead of dash

### PR DESCRIPTION
**Pull request by KurtJacobson**
This makes the `override_enabled` key consistent with the use of underscores elsewhere and with the docs.

### CODE REVIEW

**Comment by andypugh** [comment]
The HAL pins all use hyphens. 
I think I was following the wrong convention in the Python interface.

**Comment by KurtJacobson** [comment]
@andypugh You correctly used underscores on all the other dict items, you just missed that one.

**Comment by KurtJacobson** [comment]
Oops, looks like I need to change something in the tests too.

**Comment by KurtJacobson** [comment]
I have also tested axis, gmoccapy, gscreen, touchy and tklinuxcnc as well and all seem fine.

**Pull request merged**
