### PR TITLE
More changes performed while translating

### PR DESCRIPTION
**Pull request by smoe**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
This patch need a rebase to clean up branch conflict.

**Comment by smoe** [comment]
I just found that I could resolve conflicts via the Github GUI - nice!

**Comment by hansu** [comment]
You are creating merge conflicts by yourself... :smile:

**Comment by smoe** [comment]
Fixed.

**Comment by petterreinholdtsen** [comment]
I rebased the branch on master and merged it.  Thus closing as solved.

**Pull request closed without merging**
