### PR TITLE
Stat: fix mcodes attribute

### PR DESCRIPTION
**Pull request by Sigma1912**
- Fixes erroneous zero in last element of the stat.mcodes attribute by initializing the array with -1.
- Fixes broken spindle field in stat.mcodes attribute  

For discussion see:
https://github.com/LinuxCNC/linuxcnc/issues/3186

### CODE REVIEW

**Comment by Sigma1912** [comment]
Seems it's now failing the startup-state test.
 Failed: 
	/home/runner/work/linuxcnc/linuxcnc/tests/startup-state
Error: Process completed with exit code 1.

**Comment by Sigma1912** [comment]
Looks like the test expects the trailing zero in mcodes attribute, which is of course not correct. I'll have to modify 'startup-state':

```
+ rm -f sim.var
+ cp sim.var.pre sim.var
+ linuxcnc -r test.ini
Note: Using POSIX non-realtime
emc/tooldata/tooldata_common.cc, 304: Failed to open tool table file 'simpockets.tbl': No such file or directory
emc/tooldata/tooldata_common.cc, 304: Failed to open tool table file 'simpockets.tbl': No such file or directory
Traceback (most recent call last):
  File "/home/user/git/linuxcnc-master-official/tests/startup-state/./test-ui.py", line 273, in <module>
    assert(s.mcodes == (0, -1, 5, -1, 9, -1, 48, -1, 53, 0))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Note: Using POSIX non-realtime

```

**Comment by Sigma1912** [comment]
Ready, as far as I'm concerned.

**Comment by andypugh** [comment]
Thanks.

**Pull request merged**
