### PR TITLE
Fix qtvcp related typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.po,*.ts,./share,./docs/man/es,./configs/attic -L ans,doubleclick,dout,halp,parms`

### CODE REVIEW

**Comment by c-morley** [comment]
Sorry I didn't notice qtvcp_widgets.css - another generated file.

**Comment by luzpaz** [comment]
> Sorry I didn't notice qtvcp_widgets.css - another generated file.

What's the path to that file?

**Comment by c-morley** [comment]
Since it's a generated file, there is no path.

**Comment by luzpaz** [comment]
@c-morley sorry, the only .css file I modified was `share/qtvcp/screens/woodpecker/images/QTvcp Widgets_files/asciidoc.css`  shall I revert that?

**Comment by c-morley** [comment]
yes please.

**Comment by luzpaz** [comment]
Done in f5fa898

**Comment by c-morley** [comment]
Pushed to master. Thank you for your patience.

**Pull request closed without merging**
