### PR TITLE
Fix python shebang amibiguities for 'craftsman'

### PR DESCRIPTION
**Pull request by dwrobel**
Fixes the following WARNING/ERRORs:

  *** ERROR: ambiguous python shebang in
  /usr/share/doc/linuxcnc/examples/sample-configs/sim/craftsman/craftsman_toolchange:
  #!/usr/bin/python. Change it to python3 (or python2) explicitly.

  *** ERROR: ambiguous python shebang in
  /usr/share/doc/linuxcnc/examples/sample-configs/sim/craftsman/craftsmancnc:
  #!/usr/bin/env python. Change it to python3 (or python2) explicitly.

  *** WARNING: ./usr/share/doc/linuxcnc/examples/sample-configs/sim/craftsman/easygui.py
  is executable but has no shebang, removing executable bit

  *** ERROR: ambiguous python shebang in
  /usr/share/doc/linuxcnc/examples/sample-configs/sim/craftsman/vfd_spindle:
  #!/usr/bin/python. Change it to python3 (or python2) explicitly.

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

### CODE REVIEW

**Comment by dwrobel** [comment]
It was detected when creating `rpm` package for Fedora.

**Comment by petterreinholdtsen** [comment]
[Damian Wrobel]
> It was detected when creating `rpm` package for Fedora.

I recommend fixing the fedora build like we did for Debian, see
debian/rules.in.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by dwrobel** [comment]
>see debian/rules.in.

Could you be a little bit more specific?

**Comment by petterreinholdtsen** [comment]
[Damian Wrobel]
>>see debian/rules.in.
>
> Could you be a little bit more specific?

Do you mean you failed to notice the use of PYTHON=/usr/bin/python3 in
the build rules?  Or did I misunderstand the question?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
See also #1318 and #1316.

**Comment by dwrobel** [comment]
>I recommend fixing the fedora build like we did for Debian, see
debian/rules.in.

IMHO, whatever you fixed `for Debian` means it is not fixed properly - as you're forcing every other _(non Debian based)_ Linux distribution to address this issue again and again.

>Do you mean you failed to notice the use of PYTHON=/usr/bin/python3 in
the build rules?

AFAIK, whatever you assigned to `PYTHON` in `rules.in` is entirely irrelevant to what will be executed when you would try to run e.g.:
```
$ /usr/share/doc/linuxcnc/examples/sample-configs/sim/craftsman/craftsmancnc
```
as this is the `shebang` to decide about it.

**Comment by petterreinholdtsen** [comment]
You might find 'grep -r '#!.*PYTHON' src' illuminating.  Best of luck
with your approach.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by silopolis** [comment]
Le lun. 22 août 2022 à 22:35, Damian Wrobel ***@***.***> a
écrit :

> It was detected when creating rpm package for Fedora.
>

Where are those packages built?
Could packaging code be merged here?

**Comment by dwrobel** [comment]
>You might find 'grep -r '#!.*PYTHON' src' illuminating.  Best of luck with your approach.

@petterreinholdtsen I'm under impression that we're talking about two different things.

>See also https://github.com/LinuxCNC/linuxcnc/pull/1318 and https://github.com/LinuxCNC/linuxcnc/pull/1316.

The issue is not related to above ones.

Please download the latest http://buildbot.linuxcnc.org/dists/buster/scratch-rtpreempt/binary-amd64/linuxcnc-uspace_2.9.0~pre0~fix.deb.build.again~56102451b_amd64.deb unpack the `usr/share/doc/linuxcnc/examples/sample-configs/sim/craftsman/craftsmancnc` file and you might notice that it contains the following shebang:
```
#!/usr/bin/env python
```
which is wrong because it should point to `python3`. This is what I'm trying to address in this PR.

**Comment by dwrobel** [comment]
> Where are those packages built?

They are built on Fedora Copr where you could find more information - https://copr.fedorainfracloud.org/coprs/dwrobel/linuxcnc/.

>Could packaging code be merged here?

It's rather not ready for that. But everyone can use the `.spec` file to build the `rpm`.

**Comment by petterreinholdtsen** [comment]
[Damian Wrobel]
> @petterreinholdtsen I'm under impression that we're talking about two
> different things.

And I get the impression that you do not understand that we are talking
about the same thing, you do not read the pointers I provide to give
insight into why we are talking about the same thing, and my suggested
readings to see why your proposal most likely will be shut down.  My
proposal to do the same was shut down less then half a year ago.

>> See also https://github.com/LinuxCNC/linuxcnc/pull/1318 and
>> https://github.com/LinuxCNC/linuxcnc/pull/1316.
>
> The issue is not related to above ones.

They really are.  They are different proposals to solve the exact same
problem, with associated information on how the different proposals were
handled.

> Please download the latest
> http://buildbot.linuxcnc.org/dists/buster/scratch-rtpreempt/binary-amd64/linuxcnc-uspace_2.9.0~pre0~fix.deb.build.again~56102451b_amd64.deb
> unpack the
> `usr/share/doc/linuxcnc/examples/sample-configs/sim/craftsman/craftsmancnc`
> file and you might notice that it contains the following shebang:

So the build system need to be adjusted to rewrite yet another script
during installation, like the rest of them.  I am sure such patch will
be accepted.

-- 
Happy hacking
Petter Reinholdtsen

**Review by jepler — APPROVED** [review]
thanks.

**Pull request merged**
