### PR TITLE
Preparatory docs-devel rebase on master (nosquash mix)

### PR DESCRIPTION
**Pull request by silopolis**
Only resolved conflicts but didn't checked all mods...
Went quite gently
I have tried to fix sync at the same time when pulling in edits from master
but may have missed some :/
Now to find what's lost or broken...

### CODE REVIEW

**Comment by smoe** [comment]
What you are doing is beyond me. Personally, I would just go and merge. Squash some redundant commits if you like but this project has other problems than a fragmented git history.

**Comment by silopolis** [comment]
* All mods to docs/ checked with
  ```git whatchanged -p a5ac97acb9cf7960b7ae685355bd798f8aa5dfd5.. docs```
* Only doubt remaining is with Submakefile as commits and reverts make the
patch harder to the eyes
* Remaining conflicts (why ?) resolved on GH
Let's wait for CI to spit errors in my face...

**Comment by hansu** [comment]
It makes not really sense to have this as a PR, so I close this.

**Comment by silopolis** [comment]
> It makes not really sense to have this as a PR, so I close this.

More than dropping it, after 9 month of hard work, whereas it brings you a checked merge at the click of a button !

**Comment by petterreinholdtsen** [comment]
[Jérémie Tarot]
> More than dropping it, after 9 month of hard work, whereas it brings
> you a checked merge at the click of a button !

While I feel you frustration regarding the lack of progress, I suspect
this might be based on a misunderstanding.  I assumed Hans was going to
use your and mine branches as input to replace the branch used in 
<URL: https://github.com/LinuxCNC/linuxcnc/pull/1713 >, not throw away
both our rebasing demonstrations.

Personally I suspect your branch is a better end result, as you actually
looked at the adoc content, which I did not.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
The plan was to rebase and then squash some of the commits to have a more clean history of docs-devel. If I merge this PR, this would add more commits so it would result totally in the opposite of the goal.

**Comment by petterreinholdtsen** [comment]
[Jérémie Tarot]
> * All mods to docs/ checked with
>   ```git whatchanged -p a5ac97acb9cf7960b7ae685355bd798f8aa5dfd5.. docs```
> * Only doubt remaining is with Submakefile as commits and reverts make the
> patch harder to the eyes
> * Remaining conflicts (why ?) resolved on GH

Not sure I understand which Submakefile change you are talking about.

Is this the expected difference?

% git diff silopolis/docs/docs-devel-rebase-nosquash docs-devel docs | diffstat 
 Submakefile                                |    2 -
 config/core-components.adoc                |   10 ++---
 config/ini-config.adoc                     |    9 ++---
 config/python-interface.adoc               |   15 ++------
 drivers/mb2hal.adoc                        |   11 +++---
 gcode/m-code.adoc                          |   32 +++++++----------
 gcode/tool-compensation.adoc               |   70 +++++++++++++--------------------------
 gui/gladevcp.adoc                          |    2 -
 gui/gmoccapy.adoc                          |    8 ++--
 gui/mdro.adoc                              |    1 
 gui/qtdragon.adoc                          |   13 ++-----
 gui/qtvcp-widgets.adoc                     |    6 +--
 hal/halshow.adoc                           |   53 ++++++++++++-----------------
 plasma/images/qtplasmac_conversational.png |binary
 plasma/qtplasmac.adoc                      |   30 +++-------------
 15 files changed, 101 insertions(+), 161 deletions(-)
%

I kind of expected there to be no difference, but perhaps these are
changes done in master and not merged into docs-devel?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by silopolis** [comment]
Hi,

Le mar. 11 oct. 2022 à 09:03, petterreinholdtsen ***@***.***>
a écrit :

> % git diff silopolis/docs/docs-devel-rebase-nosquash docs-devel docs |
> diffstat


May be I don't understand again but, AFAIR, this was closed long ago and
dropped in favor of @hansu 's merge

**Comment by hansu** [comment]
I also don't understand why you dig in these old PR's...

**Pull request closed without merging**
