### PR TITLE
Added new version of Raspberry Pi4 and Raspberry Pi 400

### PR DESCRIPTION
**Pull request by elovalvo**
Added new version of Raspberry Pi4 and Raspberry Pi 400
Added also different version of 3B and 3B+
https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

### CODE REVIEW

**Comment by andypugh** [comment]
Do you think that this should be in Master, or in 2.8 too?

**Comment by elovalvo** [comment]
In both versions.
However Thomas J Powderly pointed out a small flaw.
I'm fixing this and will reload the updated version.

**Comment by andypugh** [comment]
Can you base the updated version on 2.8? It makes things a bit less convoluted.

**Comment by elovalvo** [comment]
ok. Now update version 2.8

**Comment by elovalvo** [comment]
> 
> 
> Can you base the updated version on 2.8? It makes things a bit less convoluted.

https://github.com/LinuxCNC/linuxcnc/pull/1044

Did I make the change correctly?

**Comment by andypugh** [comment]
We will merge this in to Master from 2.8, so closing this one.

**Pull request closed without merging**
