### PR TITLE
Avoiding configure-modified files in source tree

### PR DESCRIPTION
**Pull request by smoe**
Addressing https://github.com/LinuxCNC/linuxcnc/issues/1618

I admit not to have tested this locally, but if this builds then it should just be fine.

### CODE REVIEW

**Comment by smoe** [comment]
My changes may raise some eyebrows.  Everything is fine if just debian/rules or dpkg-buildpackage is used. However, the manual step to copy config.* elsewhere from the local disk is not yet described in the documentation.

What I should not have added in this PR is that I changed "fakeroot debian/rules binary" to a mere "dpkg-buildpackage". I am bit surprised that this worked. The benefit I was after is that lintian can be invoked on the .changes file which checks the source tree and then all the .debs afterwards.

**Comment by smoe** [comment]
@SebKuzminsky , could you please have a look since I am touching the .github/CI?

**Comment by dwrobel** [comment]
> My changes may raise some eyebrows. Everything is fine if just debian/rules or dpkg-buildpackage is used. However, the manual step to copy config.* elsewhere from the local disk is not yet described in the documentation.

Please review the alternative approach https://github.com/LinuxCNC/linuxcnc/pull/1625, which doesn't change anything in the manual build steps. It is also not debian/dpkg specific.

**Comment by smoe** [comment]
From a first glance at it that regular autoconf/automake setup of #1625 is a better approach, indeed.

**Pull request closed without merging**
