### PR TITLE
PncConf - add Tip for home sequence

### PR DESCRIPTION
**Pull request by zz912**
I made another configuration for machine.
I started numbered home_sequence from 0 as usual.
Problem was, that first axis was tandem (Z1, Z2).
It caused a problems:
https://github.com/LinuxCNC/linuxcnc/issues/2616

After reviewing the documentation:
http://linuxcnc.org/docs/2.9/html/config/ini-homing.html#sec:homing-section
I found out that it is possible to start the number home_sequemce from the number 1 (-1). So that someone doesn't have the same problems as me, I edited PncConf.
I added: (If the first axis is a tandem, start from number 1)
image
Please take this as a suggested solution only. It would be ideal to check if the axis is not tandem and warn the user if 0 is filled in.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
[zz912]
> So that someone doesn&#39;t have the same problems as me, I edited
> PncConf.  I added: (If the first axis is a tandem, start from number
> 1)

I do not know the code, but suspect this change should be squashed into
one commit and rebased on the 2.9 branch, as it seem like a useful thing
to have in the next stable release.  @andypugh, what do you think?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by andypugh** [comment]
Yes, whatever solution is settled on, it belongs in 2.9.

**Comment by c-morley** [comment]
Thank you for the pull request.
I think  #2660 covers this problem yes?

**Comment by zz912** [comment]
You're right.

**Pull request closed without merging**
