### PR TITLE
Execute finish in py remap lcnc

### PR DESCRIPTION
**Pull request by zultron**
A couple of folks have asked for reentrant python remap functions, or generators, where `yield INTERP_EXECUTE_FINISH` returns control to task, and the next read/execute cycle returns control back to the remap function.  This is useful for complex remaps, such as tool changers that need to coordinate G code motion with external HAL components.

@mhaberler put in all the basic infrastructure to do this in the original remap implementation.  These patches are just a few tweaks to get it working again, plus a unit test.

### CODE REVIEW

**Comment by zultron** [comment]
Assuming the project is interested in merging this fix, should the PR be against the master branch (as here) or 2.6, where remap was introduced?

**Comment by jepler** [comment]
@zultron 2.6 and 2.7 are mature branches, and so should only receive very safe fixes for things that are clearly regressions.  Personally, I wouldn't try to do this in any branch older than master.

**Comment by jepler** [comment]
Buildbot is working now, you will be able to view results at http://buildbot.linuxcnc.org/buildbot/builders/0000.checkin/builds/4456

**Comment by cradek** [comment]
@zultron Thank you for your continuing work on remap.

**Pull request merged**
