### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [LinuxCNC/LinuxCNC Documentation](https://hosted.weblate.org/projects/linuxcnc/linuxcnc-docs/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by smoe** [comment]
@petterreinholdtsen I don't see it. Something is wrong with the Spanish from what I gather, but I failed to find the initial error message.

**Comment by petterreinholdtsen** [comment]
I have been unable to spot the error with the Spanish translation too.

**Comment by smoe** [comment]
Just to say something positive - the transferred translations of French documents has worked - I just needed to jump a couple of dozen assignments into the "translations with edits" and every second is usable as it is. So, with a bit of an effort it should be possible to have at least the introductory bits back in French. But this is on the French-speaking community, not on me, even though I feel somewhat responsible to have contributed to the disappearance of the previous French documentation. A major blocker IMHO is the bad latency of weblate - if there is some money to speed that up, then we should likely invest into that.

**Comment by petterreinholdtsen** [comment]
I've tried to track down the Spanish build problem, and am starting to
suspect the problem is not with Spanish, but with the English
documentation too.  Not quite sure why it only trigger with Spanish, but
suspect it is simply the first PDF being built.

I discovered the new file code/writing-tests.adoc was not listed in
po4a.cfg, causing it to be missing for all translations and thus
unavailalbe to be referenced to in the rest of the documentation.  This
was an easy fix and is already in master.

Next, the problem seem to be that Master_Developer.adoc refer to files
refering to files not included by Master_Developer.adoc, which result in
dangling Docbook cross references which break the PDF build.  This seem
to be the result of new cross references in the English original text in
concert with the fact that we build several subsets of the adoc files.
Not quite sure how to best solve this, nor if my analysis is correct,
but thought it best to mention my findings so far.  I've tried adding
more includes to docs/src/Master_Developer.adoc for the build to work,
but it quickly need to include every file because of the cross
referencing.  Suspect a different approach is needed.  Perhaps remove
some cross references instead?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
I might have found the build breaking error in the Spanish translation.  "common/images/emc2-intro.png" was translated to "common/images/emc2-intro.*" in Weblate.  I flagged it as 'fuzzy' in Weblate and the build succeeded.

**Comment by hansu** [comment]
> I might have found the build breaking error in the Spanish translation. "common/images/emc2-intro.png" was translated to "common/images/emc2-intro.*" in Weblate. I flagged it as 'fuzzy' in Weblate and the build succeeded.

Nice!

**Pull request merged**
