### PR TITLE
Test clang builds on github to detect when it break.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
Related to #2212 and #2213, and would make it possible to discover clang build failures early.

**Comment by NTULINUX** [comment]
Is it possible to add ubuntu-latest or Jammy (Jammy Jellyfish) / 22.04? It's a bit more in-sync, I love this PR though! Focal / 20.04 is on only Clang 10 from 2 years ago, 5 versions behind.

**Comment by petterreinholdtsen** [comment]
I leave it to others to decide whoch Ubuntu versions to build on.  I do not have an opinion there.

**Comment by SebKuzminsky** [comment]
This is great.  

It might make sense to do `rip-and-test-clang` in docker, so you can choose a newer Ubuntu (and/or Debian) distro to run it on.

**Comment by petterreinholdtsen** [comment]
[Sebastian Kuzminsky]
> This is great.

Time to merge?

> It might make sense to do `rip-and-test-clang` in docker, so you can
> choose a newer Ubuntu (and/or Debian) distro to run it on.

Note, the clang errors reported were also triggered in clang 11.0, so
for this error it is not need for a newer Ubuntu.

--
Happy hacking
Petter Reinholdtsen

**Pull request merged**
