### PR TITLE
twopass.tcl: add support for personalities (kernel module parameters)

### PR DESCRIPTION
**Pull request by ikcalB**
Signed-off-by: Florian Kerle <flo.kerle@gmx.at>

### CODE REVIEW

**Comment by jepler** [comment]
@ikcalB I have pushed a branch to git.linuxcnc.org that merges this commit to master and then adds a small test of the new functionality.  this is branch LinuxCNC:jepler/master/ickalb-tp-personalities which should appear here on github shortly.

@SebKuzminsky I assume you are reluctant to take this for a branch like 2.6 that is in stable release mode, so for now my goal is to merge this only to master branch, not to older branches.  Let me know if you feel otherwise. Since I would want to test this functionality, it would also require backporting these commits, or else converting the test to something that runs full LinuxCNC to get the twopass function.

~~~~
37e6fc4 testsuite: basic test of twopass
29d5c45 halrun: If an inifile is specified, run it as twopass
ed79921 halcmd: add "twopass" version as executable script
~~~~

**Comment by SebKuzminsky** [comment]
@ikcalB Is the lack of this functionality in 2.6 a problem for you or anyone you know of?

**Comment by ikcalB** [comment]
@jepler thank you!

@SebKuzminsky I'm not aware of anyone else reporting this problem - though I am sure, some ppl using twopass and personalities have wondered why using both together breaks their setup, hence have taken a workaround. Afaik if somone is required to use twopass, one cannot use personalities if he'd like to.

**Comment by SebKuzminsky** [comment]
Let's put it in master, we can backport it if someone needs it in a stable branch.

**Comment by ikcalB** [comment]
Agreed. Closing this for now

**Comment by jepler** [comment]
No need to create a fresh PR, I merged this one to our master branch.  Thanks!

**Pull request closed without merging**
