### PR TITLE
2.9 g92 fix

### PR DESCRIPTION
**Pull request by Sigma1912**
See https://github.com/LinuxCNC/linuxcnc/issues/2743

Summary:
This reverts https://github.com/LinuxCNC/linuxcnc/commit/26aeab962d82a8249275e98089bff37a9e342845
due to issue https://github.com/LinuxCNC/linuxcnc/issues/2743

Fixes the original issue of missing indication of active G92 offsets after an abort (the issue originally to be fixed by the reverted commit above)

Disables automatic activation of persistent G92 offset values on startup

Fixes missing G92/G52 reset on M2,M30 after M2,M30 as described in the RX274NGC standard:
https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=823374

RS274NGC_m2 

See https://github.com/LinuxCNC/linuxcnc/issues/2744

### CODE REVIEW

**Comment by Sigma1912** [comment]
Not sure why the checks keep failing on most of my PRs

**Comment by andypugh** [comment]
It's probably not you. Let me investigate.

**Comment by andypugh** [comment]
Tests are passing on the buildbots and my test machine, I will try re-running the tests on this PR.

**Comment by Sigma1912** [comment]
It is indeed me. I was not aware that this non-compliance with the standard seems to be built into the tests.
I'm retracting this as this would probably require a more engaged discussion.

**Pull request closed without merging**
