### PR TITLE
Fix typos in configs/ subdirectory

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.po,*.pot,*.svg,*.ts,./.git/logs,./share,./docs/man/es,./configs/attic,*_fr.*,*_es.*,README_es,./src/hal/classicladder -L ans,ba,bu,bulle,componentes,currenty,doubleclick,dout,dum,extint,faktor,fo,fpr,halp,ihs,inout,inport,parm,parms,ro,ser,te,tey,ue,ure,wille,wont,wonte`

### CODE REVIEW

**Comment by luzpaz** [comment]
Overlaps with #2218

**Comment by smoe** [comment]
@luzpaz , the fixes are all good. Many thanks! IMHO the patch should go to 2.9 not to master.

**Comment by hansu** [comment]
I agree. And next time when you run codespell, please exclude "*.po,*.pot" to avoid accidentally changing of those files.

**Comment by smoe** [comment]
The patch was not affected from the .po/.pot inclusion, luckily, but yes, @luzpaz, this causes major headaches to sync back with Weblate, so @hansu was referring to your command line only.

**Comment by luzpaz** [comment]
I'm confused, `*.po,*.pot` were there first to file extensions to be omitted, since they are generated by the translation software. 

I'll take the opportunity to ask if I could submit typo changes for `.adoc` files ? (not in this PR, a separate one)

**Comment by luzpaz** [comment]
@smoe shall i make the patch against https://github.com/LinuxCNC/linuxcnc/tree/2.9 then ?

**Comment by hansu** [comment]
>I'm confused, *.po,*.pot were the first 2 file extensions to be omitted, since they are generated by the translation software.

Sorry, I didn't realize that "-S" stands for skip, so please ignore my comment 😇.

>I'll take the opportunity to ask if I could submit typo changes for .adoc files ? (not in this PR, a separate one)

Yes please, why not.

>@smoe shall i make the patch against https://github.com/LinuxCNC/linuxcnc/tree/2.9 then ?

Exactly.

**Comment by luzpaz** [comment]
Screenshot_20230627_184608

Wait..so 2.9 isn't rebased on top of master

**Comment by hansu** [comment]
No, 2.9 will never be rebased on master, but it will be merged into master regularly.

**Comment by luzpaz** [comment]
Closed in favor of #2548 made against 2.9 branch

**Pull request closed without merging**
