### PR TITLE
Fix #865, '"crazy move" when pressing STOP button / ESC'

### LINKED ISSUE #865: "crazy move" when pressing STOP button / ESC
1. load a reasonably complex g-code file (torus.png)
 2. run program
 3. interrupt while doing plunge

## This is what I expected to happen:

Motion is aborted

## This is what happened instead:

Feed or rapid move to some pseudo-random location

## It worked properly before this:

unsure.

## Information about my hardware and software:

Tested on RPI4 with linuxcnc 2.9 pre 8756d78d648d77c68952d1737f632d2eaea83cae

### PR DESCRIPTION
**Pull request by zultron**
This fixes #865.  It includes a test for the problem, and the top commit explains the problem:

```
LCNC [issue #865][1] found a race condition where an abort during
readahead resulted in unintended motion.  The `emcTaskAbort()`
function appears to be responsible for aborting interp, since it runs
`emcTaskPlanClose()`, but that by itself doesn't flush readahead
segments.

When `emcTaskStateRestore()` restored state from the `3D_Chips.ngc`
test program, executing `G64P.1`, the resulting `SET_MOTION_CONTROL_MODE()`
canon call ran `flush_segments()`, causing the unwanted motion to be
queued.

This patch fixes the problem by calling `emcTaskPlanReset()` alongside
`emcTaskPlanClose()` in `emcTaskAbort()`.  For good measure, it also
adds the call in a couple of other places alongside
`emcTaskPlanClose()` where the purpose is obviously to abort and clear
out interp and all queue.

[1]:  https://github.com/LinuxCNC/linuxcnc/issues/865

```

### CODE REVIEW

**Comment by zultron** [comment]
Thanks to @rmu75 for finding and reporting this, plus finding a good fix for it.

Thanks to @andypugh for giving me enough hints to reproduce it:  the `3D_chips.ngc` file is special, since it is very long and contains the needed `G64`, and the "having enuf logs collected" hint was also crucial.

Thanks to @pcw-mesa and @jepler for the bisect.  I don't know how you managed to tickle it reliably enough for a bisect, but you did indeed find the commits that tickled this bug for the first time.

While I'm at it, thanks to @robEllenberg for state tags!

**Comment by zultron** [comment]
Was submitting this PR against the `2.8` branch correct?

**Comment by zultron** [comment]
> Was submitting this PR against the `2.8` branch correct?

I originally thought it's not needed in `2.8` because the original report was triggered by state tags, only in master.  However, #241 and #393 both appear to be the same problem, except triggered by `ON_ABORT_COMMAND`, so perhaps it should even be applied to `2.7`?

**Comment by andypugh** [comment]
Does your new test pass or fail on 2.8 without the fix? 
(I can test myself later, but am at work now)

**Comment by zultron** [comment]
> Does your new test pass or fail on 2.8 without the fix?
> (I can test myself later, but am at work now)

It passes on 2.8 without the fix.  It would probably be easily copied and adapted so that it failed with `ON_ABORT_COMMAND` in 2.8, though, if the theory that #241, #393, #579 are the same problem.

**Comment by zultron** [comment]
> It passes on 2.8 without the fix. It would probably be easily copied and adapted so that it failed with `ON_ABORT_COMMAND` in 2.8, though, if the theory that #241, #393, #579 are the same problem.

Ah ha!  I copy'n'pasted the test and added an `ON_ABORT_COMMAND` to the `.ini` file, and reproduced that problem.  It turns out that problem was indeed fixed by @mozmck's and @robEllenberg's commit rev. b353bd3.

I think this patch is like belt & suspenders on top of that one, taking care of the problem in task's abort, rather than more narrowly within interp.  Should I resubmit the PR against the 2.7 branch?

**Comment by zultron** [comment]
Last bit of info:  My fix doesn't fix the `tests/abort/on_abort_command-crazy-move`, so it's NOT belt & suspenders.

That test is included in this PR as well.  I think we can safely close out those open, related issues.

**Comment by mozmck** [comment]
I would like to see these fixes in 2.7, but that's up to Seb ultimately I think.

**Comment by zultron** [comment]
> I would like to see these fixes in 2.7, but that's up to Seb ultimately I think.

Most importantly, your commit b353bd30 went into 2.7.  The `tests/abort/on_abort_command-crazy-move` test from this PR confirms it (including failing without b353bd30, right on!); this test isn't critical, but there's an argument for putting it into 2.7 for completeness.

The other fix and test are only tickled by state tags.  I believe it's still a bug in the pre-state tags code; it's just there wasn't anything to tickle it before then, and I'm pretty certain nothing new will be introduced to 2.7 that would tickle it in the future.

Then, up to @SebKuzminsky to err on the side of pedantism or on the side of letting sleeping dogs lie.  I'm good either way.

**Comment by mozmck** [comment]
Ah, I see - that makes sense then.  Thanks for all the work!

**Comment by jepler** [comment]
Thank you so much!  Please confer with release managers and find out what other branches we would like this on.  @SebKuzminsky ?

**Comment by rmu75** [comment]
Thanks for fixing this. I didn't really find this problem, andypugh alerted #linuxcnc-devel of a message on the user list, and I just tried to reproduce...
I don't remember/find the original reporter at the moment.

**Comment by SebKuzminsky** [comment]
@zultron Please prepare a PR for 2.7 and i'll make another bugfix release.

**Pull request merged**
