### PR TITLE
Fix race condition executing MDI during queue busters

### PR DESCRIPTION
**Pull request by zultron**
An MDI command that happens to be executed when another MDI command is
waiting on `INTERP_EXECUTE_FINISH` will be directly issued instead of
queued up for later.  This causes a lot of bad stuff to happen later.

### CODE REVIEW

**Comment by zultron** [comment]
The failure demonstrated:
https://travis-ci.org/LinuxCNC/linuxcnc/builds/161767905

**Comment by jepler** [comment]
Is this problem only exposed by "Enable remap of M62-M68"?  Or is that just making it easier to demonstrate?  (I'm trying to understand why 4410e41 is in this PR)

**Comment by zultron** [comment]
@jepler, I discovered it while running that test.  It was just convenient to trim it down.  Also, the timing seems to be pretty picky, and I wasn't able to get it working even that reliably with other scripts.

I'll try just switching out the M66 remap for M400.  I think that should work, and should eliminate the question about the other PR.

**Comment by zultron** [comment]
Failure without the M66 recursive remap:
https://travis-ci.org/LinuxCNC/linuxcnc/builds/161786792

**Comment by zultron** [comment]
This one looks like it's on its way to success.  PR title & description edited.  Thanks!

**Pull request merged**
