### PR TITLE
Nurbs g5 g6 xyz

### PR DESCRIPTION
**Pull request by jjjjjf**
I integrated the code from Lo Valvo and Drago for G6.2 and extended it from plane XY to planes YZ and ZX and tested it with sim.axis/axis_mm.ini.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
This seem to break the tests/interp/compile test.

**Comment by jjjjjf** [comment]
In the test (debian:buster) cannon.hh is included as (see line 2034)
       In file included from /usr/include/linuxcnc/canon.hh:21,
This is not my version.
cannon.hh has changes.
New:
struct NURBS_CONTROL_POINT {  // type for NURBS control points 
...

How do I run this test on my local development machine?
Joachim

**Comment by jjjjjf** [comment]
I found /tests/interp/compile/test.sh
use-rs274.cc:17:10: fatal error: Python.h: not found

Joachim

**Comment by petterreinholdtsen** [comment]
[jjf]
> How do I run this test on my local development machine?

After building the source, I use 'scripts/runtests tests/interp/compile'
to run one individual test.

Do you have suggestions how to improve 
<URL: http://linuxcnc.org/docs/devel/html/code/writing-tests.html > to
make it easier to write and run tests?
-- 
Happy hacking
Petter Reinholdtsen

**Comment by jjjjjf** [comment]
Petter thanks very much. I am a newbie here.
I have done:
changed the file tests/interp/compile/use-rs274.cc
no compile errors.
no linking errors

But still no success.
The new function NURBS_G5_FEED() is not executed.
I have to look into this.

Joachim

**Comment by petterreinholdtsen** [comment]
I notice all tests succeed now.  This is good.  Do you believe the code is ready to be merged?

Where are the new G-codes documented?  Should they be mentioned in the manual?  Are they part of the RS 274?

**Comment by jjjjjf** [comment]
Am 28.01.23 um 14:21 schrieb petterreinholdtsen:
> I notice all tests succeed now. This is good. 
Thanks for your help.

> Do you believe the code is ready to be merged?
Yes. Maybe someone else can test it.

> Where are the new G-codes documented? 
To be done.

Here are the two papers from Lo Valvo et al.
http://wiki.linuxcnc.org/cgi-bin/wiki.pl?NURBS

There are examples for G5 and G6 from La Valvo (a little bit modified by me):
https://github.com/jjjjjf/linuxcnc/tree/nurbs_G5_G6_xyz/nc_files/nurbs

Should they be mentioned in the manual?
Yes. To be done.


Are they part of the RS 274?
I do not know.

Joachim

**Pull request merged**
