### PR TITLE
Avoid '*' turning to <strong> in HTML.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by hansu** [comment]
Does this provoke a bug in po4a? It just sounds a bit weird as in https://github.com/LinuxCNC/linuxcnc/pull/1677 these characters were changed the other way around.

**Comment by petterreinholdtsen** [comment]
Nope.  It produces the wrong HTML output from a2x.  But I did discover it via the reformatting from po4a.

**Comment by petterreinholdtsen** [comment]
You can see the incorrect formatting in https://github.com/LinuxCNC/linuxcnc/blob/master/docs/README.adoc .

**Comment by hansu** [comment]
And `''` makes is italic where it supposed to be a monospace font  which  `` does

**Pull request merged**
