### PR TITLE
2.8 docs: removed 26 warnings, fixed images included in man page

### PR DESCRIPTION
**Pull request by hansu**
- Removed nearly all warnings of doc generation that came up to stderr except 
 ` troff: ./man9/bldc.9:460: suppression limit registers span more than one page;` 
@andypugh Can we ignore that because the reason is the long table?

- I found a way to embed images in the man files so that they are shown in HTML and PDF

### CODE REVIEW

**Comment by andypugh** [comment]
I would love to be able to get rid of all warnings. Let me see if I can do something in the troff to quieten that one.

**Comment by hansunzner-kt** [comment]
Unfortunately I found two other warnings in the build log (but not that one above :thinking: )
```
2021-02-06T17:53:25.1103590Z asciidoc: WARNING: plasmac-user-guide.txt: line 409: missing section: [sect5]
2021-02-06T17:55:32.9051252Z man1/xhc-whb04b-6.1:746: warning [p 165, 1.9i]: can't break line
```
And do you have an Idea why the images are not correctly converted to png by groff? 
I assume that is the reason why they are not shown on the webserver. In the PDF version they are displayed correctly.
```
2021-02-06T17:55:27.4036395Z Calling `psselect -q -p2 /tmp/groff-ps-gW5qIx /tmp/groff-ps-8FDugQ
2021-02-06T17:55:27.4037134Z Formatting toggle2nist.9 as HTML
2021-02-06T17:55:27.4038047Z ' returned status 32512
2021-02-06T17:55:27.4039759Z Calling `pnmcut 150 417 462 138 < /tmp/groff-page-9IPsZb | pnmcrop -quiet | pnmtopng -background rgb:f/f/f -transparent rgb:f/f/f > ../man/images/toggle2nist.ps.png
2021-02-06T17:55:27.4040851Z ' returned status 32512
```

On my system that worked well.
On the webserver they are shown as 0 bytes: http://linuxcnc.org/docs/2.8/html/man/man9/toggle2nist.9.html

**Comment by hansu** [comment]
Unfortunately I found two other warnings in the build log (but not that one above :thinking: )
```
2021-02-06T17:53:25.1103590Z asciidoc: WARNING: plasmac-user-guide.txt: line 409: missing section: [sect5]
2021-02-06T17:55:32.9051252Z man1/xhc-whb04b-6.1:746: warning [p 165, 1.9i]: can't break line
```
And do you have an Idea why the images are not correctly converted to png by groff? 
I assume that is the reason why they are not shown on the webserver. In the PDF version they are displayed correctly.
```
2021-02-06T17:55:27.4036395Z Calling `psselect -q -p2 /tmp/groff-ps-gW5qIx /tmp/groff-ps-8FDugQ
2021-02-06T17:55:27.4037134Z Formatting toggle2nist.9 as HTML
2021-02-06T17:55:27.4038047Z ' returned status 32512
2021-02-06T17:55:27.4039759Z Calling `pnmcut 150 417 462 138 < /tmp/groff-page-9IPsZb | pnmcrop -quiet | pnmtopng -background rgb:f/f/f -transparent rgb:f/f/f > ../man/images/toggle2nist.ps.png
2021-02-06T17:55:27.4040851Z ' returned status 32512
```

On my system that worked well.
On the webserver they are shown as 0 bytes: http://linuxcnc.org/docs/2.8/html/man/man9/toggle2nist.9.html

**Comment by andypugh** [comment]
The only one that I undrstand is the "missing section". You get that when the docs have more than 4 levels of sub-heading.

**Pull request merged**
