### PR TITLE
Changed udev rules to only grant access using TAG+="uaccess"

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
This grant access to users logged in locally via the console.

Remove access using read or write file permissions for everyone or the plugdev group.

### CODE REVIEW

**Comment by smoe** [comment]
Would prefer to assess the effects on our community in a 2.10 branch and have this backported if successful. Remote execution may be a thing.

**Comment by andypugh** [comment]
Do the devices in question operate via device events? Are those forwarded by ssh (etc) to HAL? 
I think that it would be an odd thing to expect to work, and anyone doing that would be at liberty to edit the udev rules to make it work (if it can)

**Comment by petterreinholdtsen** [comment]
[andypugh]
> Do the devices in question operate via device events? Are those
> forwarded by ssh (etc) to HAL?

No.  The device events from the kernel to udev, which are affected by
the udev rules, are only used to create the device files in /dev/.

> I think that it would be an odd thing to expect to work, and anyone
> doing that would be at liberty to edit the udev rules to make it work
> (if it can)

The change make sure 'console users', ie users logged in on the machine
using local terminals or X get access, but not 'remote users' ie users
logged inn via ssh, telnet, rdf or similar.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by andypugh** [comment]
I am struggling to think of a problem scenario. These are devices that pass events in to HAL (via USB HID) so need to be plugged in to the controller. What could anyone possibly do with remote access to them? They only do anything with _physical_ access to twirl the knobs

**Pull request merged**
