### PR TITLE
G7x precise mk2

### PR DESCRIPTION
**Pull request by jepler**
This builds on the code in #686 to achieve compatibility with the compiler on precise.

### CODE REVIEW

**Comment by jepler** [comment]
@mark-v-d any concerns about the changes introduced by this patch?  
b809e50  in particular.

**Comment by mark-v-d** [comment]
Looks OK, except for flip_state{}. Empty braces means default
initialisation, which is an indeterminate value for int. So that should
be flip_state{0}.

**Comment by mark-v-d** [comment]
Same for finish{}, which must be finish{0}

**Comment by mark-v-d** [comment]
Ignore my remarks, that is c++03

**Comment by andypugh** [comment]
Code details aside, we now seem to have clean(ish) compiles on all platforms. 
However I am seeing problems with the tests, as is the buildbot. 

My test machine is running an experimental RTAI kernel, so might not be representative. But I am getting one failed runtest with 2.8 and 115 fails (113 pass) with master. 
I am investigating, but could you run the tests (./scripts/runtests ) on your dev system to see what you get? It takes about 15 minutes to run all tests.

**Comment by andypugh** [comment]
OK, that's a good sign. I will have a look with a preempt-rt system and do some git bisecting to see what is going on.

**Pull request merged**
