### PR TITLE
Correcting typo that breaks INI file PATH

### PR DESCRIPTION
**Pull request by 6XoCtujg2C0gne**
This change is to correct a typo that breaks the SUBROUTINE_PATH variable in docs and other usage. The ";" character effectively terminates the PATH at that point. The remaining line(s) or PATHs are ignored at this point.

### CODE REVIEW

**Comment by andypugh** [comment]
Are you sure about these commits? I suspect that the *_rc files shoulsn't be there? Also, I think that .po files may be generated files?

**Comment by petterreinholdtsen** [comment]
[Andy Lewis]
> This change is to correct a typo that breaks the SUBROUTINE_PATH
> variable in docs and other usage. The &quot;;&quot; character
> effectively terminates the PATH at that point. The remaining line(s)
> or PATHs are ignored at this point.

The docs/po/ files should not be modified as part of changes to other
files.  Any changes to those should be in separate commits, potentially
synchronized with updates on hosted.weblate.org.

Please drop that part of the patch.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by 6XoCtujg2C0gne** [comment]
I’ve dropped all except the one file:  docs\src\gui\qtdragon.adoc

**Comment by petterreinholdtsen** [comment]
I suspect this was the relevant change:

```
diff --git a/docs/src/gui/qtdragon.adoc b/docs/src/gui/qtdragon.adoc
index f17771fa4b..afa68cfc77 100644
--- a/docs/src/gui/qtdragon.adoc
+++ b/docs/src/gui/qtdragon.adoc
@@ -214,7 +214,7 @@ These paths will need to be adjusted to point to the actual files on your system
 [source,{ini}]
 ----
 [RS274NGC]
-SUBROUTINE_PATH = :~/linuxcnc/nc_files/examples/ngcgui_lib:~/linuxcnc/nc_files/examples/ngcgui_lib/utilitysubs; \
+SUBROUTINE_PATH = :~/linuxcnc/nc_files/examples/ngcgui_lib:~/linuxcnc/nc_files/examples/ngcgui_lib/utilitysubs: \
 ~/linuxcnc/nc_files/examples/probe/basic_probe/macros:~/linuxcnc/nc_files/examples/remap-subroutines: \
 ~/linuxcnc/nc_files/examples/ngcgui_lib/remap_lib
 ----
```

**Comment by andypugh** [comment]
I just fixed it directly in Github: f62ad0656c15091c917b58be8d0ef81d1ebc77ff

**Comment by 6XoCtujg2C0gne** [comment]
Thanks Andy.

Regards,
Andy

Jul 10, 2024 8:38:22 AM andypugh ***@***.***>:

**Pull request closed without merging**
