### PR TITLE
Feature/spindle sync jitter fix

### PR DESCRIPTION
**Pull request by rene-dev**
fix for #164

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
I made a throw-away integration branch containing this PR merged into master, and I ran @robEllenberg's recipe (from #164) for showing the Z-velocity jitter (using the sim/axis/axis.ini config).  Here is the result:
spindle-sync-jitter-481-saa

For reference, here's the result from the current tip of master with the quantized spindle encoder commits from this PR cherry-picked in (same config):
spindle-sync-jitter-quant-encoder-saa

So, while I agree that master has a lot of Z-velocity jitter during this spindle-synced move, I don't see the proposed PR making the situation better.  Am I missing something here?

**Comment by samcoinc** [comment]
It has been a while since I have played with this branch but I think there is an extra pin that needs to be set.

This was from rob
   - Add a HAL pin, motion.spindle-tracking-gain (range 0.0 to 1.0) to
   control how aggressive position tracking is. 1.0 is stock behavior, 0.0 is
   no position tracking.

IIRC I was playing with .5
sam

**Comment by SebKuzminsky** [comment]
There is no new hal pin in this PR.

**Comment by samcoinc** [comment]
hmm - this is what I had been testing
feature/spindle-sync-overhaul-2.7-rebase
 
from robs..
https://github.com/robEllenberg/linuxcnc-mirror/tree/feature/spindle-sync-overhaul-2.7-rebase

Are there a lot of differences?  The last commits on robs are from Nov 07, 2017
This is confusing (for me)..

sam

**Comment by SebKuzminsky** [comment]
This is confusing for me too.  @rene-dev can you explain this PR to me?

**Comment by rene-dev** [comment]
whoops, I think I picked the wrong branch. It was supposed to be the real fix mentioned above.

**Comment by rene-dev** [comment]
according to rob, there is more to it. He will collect

**Pull request closed without merging**
