### PR TITLE
document some more methods and variables in `linuxcnc` python module

### PR DESCRIPTION
**Pull request by SebKuzminsky**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
Is this related to TODOs in docs/src/hal/halmodule.adoc?

**Comment by SebKuzminsky** [comment]
This PR is for the [`linuxcnc` module](http://linuxcnc.org/docs/devel/html/config/python-interface.html), it has nothing to do with halmodule.

**Comment by smoe** [comment]
The patch is beyond me but looks sufficiently harmless to just have it accepted. Just to bikeshed a litttle bit, is E-Stop or E-stop the preferred spelling? In the remaining documentation we have tried to use E-stop whenever it is not all in caps or part of a pin name, but this was just an ad hoc gut-based decision.

**Comment by SebKuzminsky** [comment]
This PR adds some in-module documentation, e.g.:
~~~
$ python3 -c 'import linuxcnc; print(linuxcnc.stat.task_state.__doc__)'
Current Task state.  Possible values:
    STATE_ESTOP: E-Stop is active.
    STATE_ESTOP_RESET: E-Stop is reset (cleared) but machine is off.
    STATE_OFF: Same as STATE_ESTOP_RESET, this one is not used.
    STATE_ON: Machine is out of E-Stop and is powered on.
~~~

I do a lot of my python testing in `ipython3`, and I find having this kind of doc available there helps a lot.

I have no opinion on the capitalization of [Ee]-[Ss][Tt][Oo][Pp].

**Comment by smoe** [comment]
Then `E-stop` :) But no need for this PR, want to grep -r on the source tree for these kind of changes.

**Pull request merged**
