### PR TITLE
Add the preselection of the parallel ports.

### PR DESCRIPTION
**Pull request by nicokid**
Added a control in Stepconf to search for the parallel ports present.

### CODE REVIEW

**Comment by c-morley** [comment]
This does not look merge-able as is. I can't see where your parport work is.
Can you rebase your work on current master, so your work is on top?

**Comment by nicokid** [comment]
> This does not look merge-able as is. I can't see where your parport work is.
> Can you rebase your work on current master, so your work is on top?

Hi,
I'm currently bogged down with git (as usual). No chance to rebase:
```
First, rewinding head to replay your work on top of it...
Applying: Remove some comments
Using index info to reconstruct a base tree...
M	src/emc/usr_intf/stepconf/axisa.glade
M	src/emc/usr_intf/stepconf/axisu.glade
M	src/emc/usr_intf/stepconf/axisv.glade
M	src/emc/usr_intf/stepconf/axisx.glade
M	src/emc/usr_intf/stepconf/axisy.glade
M	src/emc/usr_intf/stepconf/axisz.glade
M	src/emc/usr_intf/stepconf/base.glade
M	src/emc/usr_intf/stepconf/build_HAL.py
M	src/emc/usr_intf/stepconf/build_INI.py
M	src/emc/usr_intf/stepconf/finished.glade
M	src/emc/usr_intf/stepconf/main_page.glade
M	src/emc/usr_intf/stepconf/options.glade
M	src/emc/usr_intf/stepconf/pages.py
M	src/emc/usr_intf/stepconf/pport1.glade
M	src/emc/usr_intf/stepconf/pport2.glade
M	src/emc/usr_intf/stepconf/spindle.glade
M	src/emc/usr_intf/stepconf/start.glade
M	src/emc/usr_intf/stepconf/stepconf.py
Falling back to patching base and 3-way merge...
Auto-merging src/emc/usr_intf/stepconf/stepconf.py
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/stepconf.py
Auto-merging src/emc/usr_intf/stepconf/start.glade
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/start.glade
Auto-merging src/emc/usr_intf/stepconf/pages.py
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/pages.py
Auto-merging src/emc/usr_intf/stepconf/options.glade
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/options.glade
Auto-merging src/emc/usr_intf/stepconf/main_page.glade
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/main_page.glade
Auto-merging src/emc/usr_intf/stepconf/finished.glade
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/finished.glade
Auto-merging src/emc/usr_intf/stepconf/build_INI.py
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/build_INI.py
Auto-merging src/emc/usr_intf/stepconf/build_HAL.py
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/build_HAL.py
Auto-merging src/emc/usr_intf/stepconf/base.glade
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/base.glade
Auto-merging src/emc/usr_intf/stepconf/axisz.glade
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/axisz.glade
Auto-merging src/emc/usr_intf/stepconf/axisx.glade
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/axisx.glade
Auto-merging src/emc/usr_intf/stepconf/axisv.glade
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/axisv.glade
Auto-merging src/emc/usr_intf/stepconf/axisu.glade
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/axisu.glade
Auto-merging src/emc/usr_intf/stepconf/axisa.glade
CONFLICT (content): Merge conflict in src/emc/usr_intf/stepconf/axisa.glade
error: Failed to merge in the changes.
Patch failed at 0001 Remove some comments
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```
Do you know a way (that works) to reset everything?
Nicola.

**Comment by andypugh** [comment]
git rebase --abort will get you back to where you were. 

According to https://github.com/LinuxCNC/linuxcnc/pull/844/files only 6 files are changed by your work, so clearly the history since this patch was created has got in the way.

What might work is interactive merge. I think if you merge your work in to master, squashing all the things you meant to do into one commit, and skipping all the other stuff, you might end up with a single3 mergeable commit. 

At the moment the diff is 43MB!

**Comment by nicokid** [comment]
> git rebase --abort will get you back to where you were.
Yes I know I have already tried it but it does not solve the rebase problem.
I don't think it's possible to fix my repository. I would like to understand if it is possible to reset it and start over.
Thanks.

**Comment by nicokid** [comment]
I think I managed to reset everything. Now I try a new pull request.
Excuse me.
Nicola.

**Pull request closed without merging**
