### PR TITLE
Fix kmod rtai build

### PR DESCRIPTION
**Pull request by jepler**
@NTULINUX
Closes: #2011

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I suspect this pull request should close issue #2011.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by NTULINUX** [comment]
Thanks, I'll give this a test soon!

**Review by petterreinholdtsen — APPROVED** [review]
The set of changes look good to me, but I believe the commit message of https://github.com/LinuxCNC/linuxcnc/pull/2012/commits/a38317509386425cf2778f87ecf512caec9eadf0 should be changed to include 'fixes #2011' to add a link to the relevant issue and automatically close this issue when the change is merged.

**Review by NTULINUX — APPROVED** [review]

**Review by NTULINUX — APPROVED** [review]

**Review by NTULINUX — APPROVED** [review]

**Comment by NTULINUX** [comment]
Didn't mean to approve 3 times, didn't know all you had to do was review one commit. I approved each commit and then the two files afterward, sorry about that. Builds fine now!

**Pull request merged**
