### PR TITLE
Reduce use of sprintf, strcpy and strcat

### PR DESCRIPTION
**Pull request by rene-dev**
jeplers https://github.com/LinuxCNC/linuxcnc/pull/495 but for 2.8

### CODE REVIEW

**Comment by andypugh** [comment]
I think that the compiler actually checks if you do anything with the return value of snprintf. 
Otherwise it gives the "possible truncation" warning.

**Comment by rene-dev** [comment]
Its actually right about the warning, but at least with this patch it doesn’t write to unallocated memory. Im trying to find a sane way of silencing it.

**Comment by andypugh** [comment]
Just to avoid duplication of work, I am running through all the truncation warnings. 
So let me know if you are further along than me :-)

**Comment by rene-dev** [comment]
I also ran https://clang-analyzer.llvm.org/ to find more potential problems.
it generates a html report file. some of them I already fixed.

**Pull request merged**
