### PR TITLE
Fix some major bugs in xhc-whb04b-6 user component

### PR DESCRIPTION
**Pull request by jasenk2**
1. There is wrong code for LEAD position of feed rotary switch.
2. There was major mistake in parse procedure Pendant::processEvent values are tested against button codes for invalid code but object is send as null to actual Pendant::processEvent so segfault coredump was produced

### CODE REVIEW

**Comment by andypugh** [comment]
I think that this pull-request has gone wrong? It can't be necessary to change 377 files to fix one driver? 
Which commit contains the actual fixes?

**Comment by alkabal** [comment]
Hi

What did you want to do with LEAD ?

**Comment by alkabal** [comment]
If you are right for the patch, the readme.md need also to be edited. (i have check your 2.8 branch from your fork)

I will try to test your patch asap.

**Comment by alkabal** [comment]
https://forum.linuxcnc.org/10-advanced-configuration/32516-whb04b-6-manual-pulse-coder

here we can found another value for lead, so really need to do another check.

**Comment by jasenk2** [comment]
Sory, but whole different branch here is the actual commit it's onli in one
file and 4 changes and 3 line added
https://github.com/jasenk2/linuxcnc/commit/93288bc26ad67de814b7a9ff303e9e169b5d182d

На ср, 29.04.2020 г. в 11:51 andypugh <notifications@github.com> написа:

**Comment by jasenk2** [comment]
Hi, i have closed old request and open new one, see it

На ср, 29.04.2020 г. в 17:02 jasen kolev <jasenk2@gmail.com> написа:

**Pull request closed without merging**
