### PR TITLE
fix configs/apps/gladevcp: update to gtk3

### PR DESCRIPTION
**Pull request by Sigma1912**
Probably not the most used examples but since they are referenced in the GladeVCP documentation it would be nice if they are at least functional.
'sourceview' and 'animated backdrop' still not 100% functional but at least they load ok.

### CODE REVIEW

**Comment by hansu** [comment]
> 'sourceview' and 'animated backdrop' still not 100% functional but at least they load ok.

Doesn't look like a huge thing to get also the `_set_line function` compatible with GtkSourview 3. Or am I wrong?
Would be nice if we could have this complete.

**Comment by Sigma1912** [comment]
Alright :) 
I'll be back with another one.

**Comment by andypugh** [comment]
Is this superceded by moving to GtkSourceview4 ?

**Comment by Sigma1912** [comment]
I'm afraid I don't know what moving 2.9 to GtkSourceview4 means for GUIs that use GTK3. I would expect @hansu to be more aware of the consequences.

Note, the current PR is over here:
https://github.com/LinuxCNC/linuxcnc/pull/3090

**Comment by hansu** [comment]
> Is this superceded by moving to GtkSourceview4 ?

No,  "Both GtkSourceView 3 and GtkSourceView 4 depend on GTK 3."

**Pull request closed without merging**
