### PR TITLE
debian/configure: Drop outdated support for rtai and xenomai

### PR DESCRIPTION
**Pull request by jepler**
There are no packaged rtai or xenomai kernels available.

This does NOT drop support for building with src/configure.

It can be restored if there are ever properly packaged rtai or xenomai kernels again.

### CODE REVIEW

**Comment by andypugh** [comment]
I am a little confused by the assertion that there are no RTAI packages. 
http://www.linuxcnc.org/dists/buster/base/binary-amd64/
Has kernel and RTAI application  packages.

**Comment by rene-dev** [comment]
oh, I thought rtai was non-functional on buster.

**Comment by andypugh** [comment]
It's complicated. Less than 1% of the time it crashes the kernel on exit. Which means that it can't reliably make it through runtests. 
But it is perfectly usable if you can accept that problem.

**Comment by jepler** [comment]
Please feel free to revert this change if you like.  (xenomai should still go away though)

**Pull request merged**
