### PR TITLE
Plasma primer tweaks

### PR DESCRIPTION
**Pull request by andypugh**
I was reading the plasma primer and spotted a few typos and such. 

Note that I have had no luck with changing the size of the first two images. I left my edits in as markers, but they don't work.

### CODE REVIEW

**Comment by phillc54** [comment]
Thanks Andy. I am not sure what is going on with the images, I assumed 50% was 50% of the page width. I just reverted them to 400 and they look OK on HTML but I haven't tried PDF. I will check that out tomorrow.

**Comment by phillc54** [comment]
I have just pushed some resized images. They seem to build on the docs OK locally.

**Comment by andypugh** [comment]
I don't know why, but the pull request has ended up as against master. 
There were other things in the PR, such as start/spark in the Blowback section and re-phrasing of what is in which version of LinuxCNC (state-tags has been merged, Plasmac is in 2.8)

**Comment by phillc54** [comment]
I did see the changes you made but didn't use anything from this PR, I only pushed the resized images. Did I do something wrong?

**Comment by andypugh** [comment]
I was anticipating that you might look through the changes and see if you concurred with them. Then either make changes, or leave things as they are, if that is what the doc is meant to say. 
For example it is possible that a 30mm sheet might have 100mm or warp. I have not used a Plasma. In fact I was reading the primer to learn more about it.

**Comment by phillc54** [comment]
I had a quick scan through and it looked OK to me, I will see if Rod can have a look, this was his baby.

**Comment by rodw-au** [comment]
I've had a look at  this and  am generally happy on the assumption the grammar used in the colonies should defer to the mother country :)

I made these comments while reviewing:
111 should only be
227 amazing, great work - Andy thanks for tackling state tags after 5+ years, I'm sure more pr's will be required to use the data! Is Cam's feedrate being pulled from state tags?

I'm sorry I don't have a source any more  about the 100mm warpage on 30mm stock but I think it should stay at 100mm becasue I have observed > 50mm  on 2mm mild steel while cutting. Therefore 10mm is insignificant. Stefan (thefabricator03) has shown  photos of thinner offcuts with  something close to 100mm warpage.

Please note this is an evloving document and will require ongoing revisions as we learn more about the project. eg. I am working on two different projects/components which when deployed will require updates to the docs.

**Comment by andypugh** [comment]
I merged a different way

**Pull request closed without merging**
