### PR TITLE
Update ClassicLadder to 0.8.10

### PR DESCRIPTION
**Pull request by havardAasen**
This is an update of ClassicLadder, to version 0.8.10, released in late 2010. Still quite old and only GTK 2. The most important change is that all drawing is done with Cairo, that's needed for the change to GTK 3, it also includes a new toolbar and the possibility to use the mouse scroll, that feature is backported from 0.9.113.

I also removed the `--config` flag, this has been marked as deprecated at least since LinuxCNC 2.6.

The upstream version includes a log feature, which I haven't enabled (all relevant code is commented out), it should be easy enough to enable it if we decide to.

I've looked at the latest release, 0.9.113, this release works with both GTK 2 and 3, but a lot has happened in the last ten years and it's not so easy to juggle the things we need and what we don't want, still, it would be nice if we managed to include part of it.

This pr is marked as a draft for three reasons:
- Update documentation
- More testing, especially with modbus (haven't been able to test this myself
- Upstream also included a new variable which I'm uncertain of, `VAR_SYSTEM` which partly collides with our `VAR_ERROR_BIT`.  The changelog entry for 0.8.5 mentions:
> New system variables %Sxxx and %SWxxx : %S0 is the classic 1Hz flash, always usefull...
> And %SW0, %SW1 & %SW2 for BCD time, date & day of week.
> %S10 is set per the modbus master if error of communication (EMC principle), in the future I've planned

### CODE REVIEW

**Comment by smoe** [comment]
I found upstream's GitHub repository on https://github.com/MaVaTi56/classicladder . Just asking - if I prepare a Debian package of upstream's classicladder, would that in some way help the transiton of what LinuxCNC depends on? If not then there is no point, obviously :)

**Comment by c-morley** [comment]
Can we not adjust the var list to not collide with VAR ERROR  bit?
Great work by the way!

**Comment by hansu** [comment]
> I found upstream's GitHub repository on https://github.com/MaVaTi56/classicladder . Just asking - if I prepare a Debian package of upstream's classicladder, would that in some way help the transiton of what LinuxCNC depends on? If not then there is no point, obviously :)

But for the latest version there seems to be some limitations regarding RT:

>RTLinux/RTAI will no more work since v0.9.015 (objects memory allocation of project datas after
  project size configuration loaded, done each time and not only at startup for first project loaded)

**Comment by silopolis** [comment]
Hi

Le jeu. 10 mars 2022 à 09:03, Hans ***@***.***> a écrit :

> I found upstream's GitHub repository on
> https://github.com/MaVaTi56/classicladder . Just asking - if I prepare a
> Debian package of upstream's classicladder, would that in some way help the
> transiton of what LinuxCNC depends on? If not then there is no point,
> obviously :)
>
>
I've been wishing we had a clean and stable interface with upstream and use
it directly instead of embedding it in our tree. Having it packaged
seperatly would surely be a start and even a pre-requisite now that we're
in Debian.

But for the latest version there seems to be some limitations regarding RT:
>
> RTLinux/RTAI will no more work since v0.9.015 (objects memory allocation
> of project datas after
> project size configuration loaded, done each time and not only at startup
> for first project loaded)
>
> And this comes to support another wish of mine which is that PLC feature
would be provided by a pluggable interface where one could choose between
ClassicLadder, OpenPLC,... As long as a module is available for
integration.

I'd love to hear about guru's and others' technical and integration point
of view about this.

I also see this as a possibly big vector of interaction with communities of
related softwares and hardwares.

TY
Jérémie

**Comment by c-morley** [comment]
`would be provided by a pluggable interface where one could choose between
ClassicLadder, OpenPLC,... As long as a module is available for
integration.`

You want a plug-able interface for different software PLCs?
That is what HAL is.
It allows you to load and connect different programs software I/O data.
I don't think I understand.

**Comment by andypugh** [comment]
Losing the RT interface looks like a blocking issue for our applications. So it seems that 0.9.015 is out of the question. 

0.8.10 as mentioned in the PR presumably still works with realtime.

How hard is this looking?

**Comment by smoe** [comment]
My comment was not meant to block anything, I was just happy to have found a potential future project :) I can likely speak for @silopolis that he did not meant to block anything either.

**Comment by c-morley** [comment]
IMHO we should not put this in 2.9

**Comment by havardAasen** [comment]
ClassicLadder now defaults to GTK 3.

Since the last push (25 days ago), I have sorted out quite a few things, mostly small things but I saw that I had removed a lot of our specific code changes. They are now back inn.

I'm not a heavy CL user, but for the things I have tried it does what it's supposed to do.
This is mostly a backport, which has been modified with LinuxCNC specific patches, but there is a lot of code changes in here, and the possibility for subtle bugs is possible.

**Comment by hansu** [comment]
Nice that it is now running on Gtk3! Do you think it is ready to be tested in master?

**Comment by havardAasen** [comment]
I would have preferred if someone with a larger or more complex classicladder setup would test it first, and if nothing breaks, it's good to go. My own tests doesn't cover enough of the program to be 100% confident.

Then it's only to decide if we want it in the 2.9 release or not.

**Comment by samcoinc** [comment]
I have a few pretty complicated ladders I could test.  (tool changer with
barcoded tools and pallets..)

Where is this repository?

**Comment by rene-dev** [comment]
I know nothing about CL, but In my experience with linuxcnc things if we dont merge it now, it will forever be sitting in this branch, and no one will ever test it or know if it works. best way is to merge it, and see what breaks. Probably best to announce it on the ML.

**Comment by havardAasen** [comment]
> I have a few pretty complicated ladders I could test. (tool changer with barcoded tools and pallets..) Where is this repository?

I believe it's possible to fetch PR's, if not, repo  https://github.com/havardAasen/linuxcnc/ and the branch `haava/classicladder_v0.8.10`

**Comment by andypugh** [comment]
To try out this pull-request locally:
````
git fetch origin pull/1657/head:pr1657
git checkout pr1657
git log
make
````

**Comment by havardAasen** [comment]
@samcoinc Did you get a chance to test this repository?

**Comment by samcoinc** [comment]
I have not yet - sorry.  Got busy making parts this weekend.

**Comment by havardAasen** [comment]
@SebKuzminsky @andypugh How is the plan for releasing 2.9? The last suggestion I read on the mailing list, was for a stable release in sync with Debian Bookworm, late January or early February 2023.
If that's the case, this PR might still be included, if we don't delay much longer.

**Comment by andypugh** [comment]
I have been thinking about a 2.8.3 release, but things are rather up-in-the air in my personal life right now (I am fine, but my mum isn't) so I can't really commit to anything time-consuming in the medium term.

**Comment by c-morley** [comment]
I notice if I scroll to a second panel, as soon as I move the mouse it scrolls back to the first one.
Do you see this?
mint 20

**Comment by c-morley** [comment]
scrolling while editing is not right.
I can't edit the coils or switches numbers.

**Comment by havardAasen** [comment]
> I notice if I scroll to a second panel, as soon as I move the mouse it scrolls back to the first one. Do you see this? mint 20

The way I read the description, I can't replicate this on Debian 10 with MATE

> scrolling while editing is not right. 

Agreed, will look into this. Noticing that the latest upstream also has the same issue.

> I can't edit the coils or switches numbers.

That's actually quite bad. Not sure whats best/fastest, latest upstream has a new UI to choose variables, it's quite nice and easy to use.

I also noticed another issue. Playing with `configs/sim/axis/classicladder/demo_sim_cl.clp`. When I modify a timer block, if I change `Preset` value, the GUI temporary updates, but when you hit 'ok' the GUI reverts back to the old value, looks like the new value is the one being used. This behavior is in the current CL version in LinuxCNC, the version in this branch and in latest upstream.

**Comment by havardAasen** [comment]
This fixes editing of coils and switches.
I got a fix for scrolling while editing as well, but it's not as elegant as had hoped for. I asked upstream what he thinks about the fix.

**Comment by c-morley** [comment]
when I select the bottom panel (scroll or pick) if I move the mouse left or right, the upper panel goes into focus.
mouse up and down seems fine.

**Comment by c-morley** [comment]
Well hmm. if I'm on the left side,  then mouse up down moves the focus up. weird.

**Comment by c-morley** [comment]
Entry of bits and timers are confirmed fixed.
Might I suggest we allow lower case entry of variables?
It's annoyed me forever.

**Comment by havardAasen** [comment]
> Well hmm. if I'm on the left side, then mouse up down moves the focus up. weird.

I'll look into installing Linux Mint in  a vm and test this out. I know that Andy reported something similar in the mailing list, not as severe and it was against Halscope, but it's GTK and Linux Mint.  <https://www.mail-archive.com/emc-developers@lists.sourceforge.net/msg22196.html>

> Entry of bits and timers are confirmed fixed. Might I suggest we allow lower case entry of variables? It's annoyed me forever.

Is it this you mean? That the variable should match case-insensitive?
var

Or is t the `%B0` variable you want to write as `%b0`?

**Comment by c-morley** [comment]
the %B0 variable I want to write as %b0

**Comment by smoe** [comment]
@petterreinholdtsen  and me are going to prepare some automated tests for classicladder and if those work also on this branch then would rather think positively of merging. @c-morley - would that be a way forward? (this is a close as it gets to a collective post during our Open Mike session looking at old PRs)

**Comment by c-morley** [comment]
my conser with merging is really only about how soon the release of 2.9 is..
unfortunately we did not discuss 2.9 release much - at least what I could understand from the meeting..

Its a catch-22, all the bugs won't be found untill it gets in a more exercised branch, yet IMHO it's not ready to be released to the broad public in a release. (though I have not checked it recently)
I just don;t want it merged to master then 2.9 is released a month later before most of the bugs are found.

**Comment by smoe** [comment]
With hindsight, the patch should have been accepted immediately since it turns out we had all those months to test it. But we did not know that. And we still do not know that. @andypugh , waddayathink, do we have enough time to find the putative not-so-obvious problems with 0.8.10 prior to the release? If so, then I tend to think that @c-morley just gave a green light for a merge.

I have no idea about how complete the coverage of the tests can be that we hope to come up with. Our strategy was to look at what is stated in the documentation and transform that into tests that should be executable and have the same output in 0.8.9 and 0.8.10. Heck, and maybe we can come up with something educational by ourselves, too.

**Comment by silopolis** [comment]
Le mar. 9 août 2022 à 02:10, Steffen Möller ***@***.***> a
écrit :

> With hindsight, the patch should have been accepted immediately since it
> turns out we had all those months to test it. But we did not know that. And
> we still do not know that. @andypugh <https://github.com/andypugh> ,
> waddayathink, do we have enough time
>

Do we know Debian's release planning and specifically testing freeze date?
What are the chances for us to release before freeze?
Debian freeze period would be an added testing and bug squashing period.

I have no idea about how complete the coverage of the tests can be that we
> hope to come up with. Our strategy was to look at what is stated in the
> documentation and transform that into tests that should be executable and
> have the same output in 0.8.9 and 0.8.10. Heck, and maybe we can come up
> with something educational by ourselves, too.
>

Maybe Phil ***@***.***) could help us with this... I'll get in touch
with him.

**Comment by petterreinholdtsen** [comment]
https://release.debian.org/ got some key dates.

PS: I notice the current pull request got conflicts and is unmergable.

**Comment by silopolis** [comment]
Le jeu. 25 août 2022 à 11:41, petterreinholdtsen ***@***.***>
a écrit :

> https://release.debian.org/ got some key dates.
>

So end of year/jan 2023 at most look like good targets for 2.9 as @andypugh
expressed in #1899

**Comment by c-morley** [comment]
If you really want this in by the end of the year it needs to go in real soon to shake out bugs.

**Comment by petterreinholdtsen** [comment]
Now with 2.9 forked from master, I suspect it is time to merge this into master to get it ready for the 2.10 release.  But the branch have merge conflicts.  Any chance to fix them?

**Comment by havardAasen** [comment]
Resolved conflicts.

**Comment by petterreinholdtsen** [comment]
[Håvard]
> Resolved conflicts.

Thank you very much.

I've been trying, unsuccessful so far, to write some scripts in tests/
to verify that ClassicLAdder keep working after the upgrade.  Do you
have any clues how to test it?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Håvard]
> I'll admit that I haven't given this much thought. When I did my
> manual testing, I used some of the examples in
> `src/hal/classicladder/projects_examples/`, and verified that they
> functioned the same way as before, not sure if those, or something
> similar could be used for testing, at least the basic.

I would be happy to help with the test script mechanics.  Perhaps you
can ping me on the #linuxcnc-devel IRC channel (libera.chat) and we can
see what we can figure out together?

I'll have a look at the examples.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Håvard]
> I'll admit that I haven't given this much thought. When I did my
> manual testing, I used some of the examples in
> `src/hal/classicladder/projects_examples/`, and verified that they
> functioned the same way as before, not sure if those, or something
> similar could be used for testing, at least the basic.

I had a look, but did not get any wiser.  How did you verify their
function?  Perhaps it can be scripted with halcmd or some custom python
script.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
The theoretical computer scientists love their automata. My idea was to only test a particular subset of possible automata, i.e. those that "halt". HAL itself does not halt and I have not yet found a pin (a very dangerous pin that is) that would make it exit. This would need another pin to also set an exit value. If we have that, then we could basically come up with ClassicLadder scripts. Adding pins that know how to read from stdin and others that write to stdout, we can test them.

 

From what I have understood so far, whenever HAL is run, it is meant to run forever. But that means that any HAL file testing ClassicLadder would never terminate.

 

Best,
Steffen


 

Gesendet: Dienstag, 15. November 2022 um 16:57 Uhr
Von: "petterreinholdtsen" ***@***.***>
An: "LinuxCNC/linuxcnc" ***@***.***>
Cc: "Steffen Möller" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [LinuxCNC/linuxcnc] Update ClassicLadder to 0.8.10 (PR #1657)


 

[Håvard]
> I'll admit that I haven't given this much thought. When I did my
> manual testing, I used some of the examples in
> `src/hal/classicladder/projects_examples/`, and verified that they
> functioned the same way as before, not sure if those, or something
> similar could be used for testing, at least the basic.

I had a look, but did not get any wiser. How did you verify their
function? Perhaps it can be scripted with halcmd or some custom python
script.

**Comment by petterreinholdtsen** [comment]
I wrote a simple test in
<URL: https://github.com/petterreinholdtsen/linuxcnc/tree/test-classicladder-estop >
which seem to limp along.  Not sure it actually is using classicladder,
but hope it is involved in the estop machinery.  Can we do better?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Petter Reinholdtsen]
> Not sure it actually is using classicladder, but hope it is involved
> in the estop machinery.  Can we do better?

I sure hope so, but am happy to tell that I managed to get the test
working and submitted it as PR #2156 for inclusion in master.  I hope we
can add some more tests, but at least we got one working test.

I tested it with this pull request, and the test was succesful.  So at
least some parts of this pull request is working.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request merged**
