### PR TITLE
 2.8 some little fixes in docs

### PR DESCRIPTION
**Pull request by Hans470**
See https://github.com/LinuxCNC/linuxcnc/issues/996

### CODE REVIEW

**Comment by andypugh** [comment]
Just to check, you think that these should go in to 2.8?

**Comment by Hans470** [comment]
Yes

**Comment by andypugh** [comment]
Thanks.

**Comment by andypugh** [comment]
Can you look in on the buildbot in an hour or so and check that the docs build went cleanly?

**Comment by Hans470** [comment]
Hmm a little thing in the PDF generation may went wrong.
But why are the contents on the webserver not updated yet? Is that not done automatically?
```
Formatting manual pages as PDF
....
man9/toggle.9:18: .sy request not allowed in safer mode
man9/toggle.9:18: can't open `3.eps': No such file or directory
man9/toggle2nist.9:30: .sy request not allowed in safer mode
man9/toggle2nist.9:30: can't open `4.eps': No such file or directory
	| ps2pdf - ../docs/LinuxCNC_Manual_Pages.pdf
```

**Comment by andypugh** [comment]
The docs on the web server update automatically, but only if the compilation succeeds. 
It looks like something went wrong. 
http://buildbot.linuxcnc.org/buildbot/builders/0000.checkin/builds/7544
I have tried to force a rebuild, but I don't know how to force a branch (using the IRC buildbot chatbot)

**Comment by andypugh** [comment]
Do the docs build cleanly for you? I rather assumed that you had tested that before submitting the pull request. 
(./configure --enable-build-docs=pdf,html )

**Comment by Hans470** [comment]
I just cloned the current 2.8 (after that merge) into a clean directory and made a build.
There were even lots of other warnings that don't belong to my changed parts.
But the HTMLs and PDFs were generated correctly.
[build_stdout.log](https://github.com/LinuxCNC/linuxcnc/files/5874525/build_stdout.log)
[build_stderr.log](https://github.com/LinuxCNC/linuxcnc/files/5874524/build_stderr.log) (sorry for the partly german messages)

**Comment by andypugh** [comment]
Yes, there are hundreds of warning messages. I actually managed to get rid of all of them and get an all-green build last year. Briefly.

**Comment by Hans470** [comment]
Hmm seems like we have a new task...
But the question is, which warnings are real warnings and which depens on my system. E.g. some missing latex packages that are not covered by the configure script. 
Do you also get rid of the messages like `Cannot convert '.....png' to pdf` ?

**Comment by andypugh** [comment]
As I recall the png-to-pdf thing is only a problem on some OS versions. 
I rather wish that we could switch to using asciidoctor-pdf, as that makes the PDFs in a single step and also makes the Chinese docs properly.

**Comment by Hans470** [comment]
But what exactly causes the buildserver not to update the webserver cannot really be determined?

**Comment by andypugh** [comment]
When I edited the info about the Pi images a day or two ago, the changes showed up about an hour later. 

You _can_ tell what has gone wrong by looking at the buildbot grid: http://buildbot.linuxcnc.org/buildbot/grid
The branch is at the top, and you want to see a green, or at least only yellow 2000.docs build. 
If you can click on the box to look at the log.

**Comment by Hans470** [comment]
Hmm whatever causes the buildserver not to update the webserver - after your commit my changes are on the webserver.
Strange...
And on the grid view I can only see the last 5 builds, so nothing to debug the regarding 2.8 build.

**Comment by andypugh** [comment]
Is it possible that the new stylesheet is changing "-" to a hyphen? 
(ie, ASCII 2D to E2 88 92)
Compare the LinuxCNC Wiki URL in my locally-made version here:
http://www.bodgesoc.org/sendkeys.1.html
To the one here:
http://linuxcnc.org/docs/2.8/html/man/man1/sendkeys.1.html

This same problem has appeared in many places in the docs. It is especially troublesome where it leads to invalid HAL pin names. For example in:
http://linuxcnc.org/docs/2.8/html/man/man1/halui.1.html
Where all the HAL pin names are invalid.

**Comment by hansu** [comment]
I have no idea why that happens. It only adds the line
` <link rel="stylesheet" href="../../asciidoc.css" type="text/css" /> <link rel="stylesheet" href="../../linuxcnc.css" type="text/css" />`
 to the `<head>`-section.

My local build produces no hyphens, see here: 
[halui.1.html.tar.gz](https://github.com/LinuxCNC/linuxcnc/files/6090503/halui.1.html.tar.gz)

**Comment by andypugh** [comment]
No, mine does not create hyphens either, which makes it a rather tricky thing to try to fix.

**Comment by hansu** [comment]
Yes the same as with the empty images (https://github.com/LinuxCNC/linuxcnc/pull/1068#issuecomment-774645683) :-/

**Pull request merged**
