### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [LinuxCNC/LinuxCNC](https://hosted.weblate.org/projects/linuxcnc/linuxcnc/).

It also includes following components:

* [LinuxCNC/LinuxCNC/Gmocappy](https://hosted.weblate.org/projects/linuxcnc/gmocappy/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by dsa-t** [comment]
Commits by @gfghjjk (https://hosted.weblate.org/user/xXx/#changes) for Russian translation should be reverted. These are machine-translated, and replace correct translations without understanding the terminology or context.

**Comment by petterreinholdtsen** [comment]
[dsa-t]
> Commits by @gfghjjk (https://hosted.weblate.org/user/xXx/#changes) for
> Russian translation should be reverted. These are machine-translated,
> and replace correct translations without understanding the terminology
> or context.

Are you on IRC?  Sound like something we would like to do a more
interactive discussion about how to handle.  I believe xXx on Weblate is
IlyaKw on IRC.  Did you talk to him about this?  How do you know they
are machine translated?

Note, I do not understand a word Russian.  I only try to help with the
translation framework in this regard.  I assume you already found the
presentation on <URL: https://linuxcnc.org/docs/devel/html/ru >.

Filtering out translations done by a specific person is not going to be
trivial, it is easier to revert back to a time before the person started
translating.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Petter Reinholdtsen]
> I believe xXx on Weblate is IlyaKw on IRC.

This was based on me believing there was only one person interested in
and active with translating to Russian.  I was just told by IlyaKw that
he do not konw who xXx is.

I guess this mean there are at least three persons interested in the
Russian translation, xXx, IlyaKw and dsa-t.  It would be best if you
could work out how to handle the Russian translation among yourself, as
you understand the langauge a lot better than me.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by dsa-t** [comment]
I'm not especially interested in contributing to LinuxCNC translations since I don't use it. I'm just reporting about the damage this user is causing to various projects. I'm not in the IRC.

See some examples of seemingly correct translations being replaced with machine ones. A human (who knows some terminology) wouldn't write like that:
https://hosted.weblate.org/translate/linuxcnc/linuxcnc/ru/?checksum=7bf6e0114fa62e16
https://hosted.weblate.org/translate/linuxcnc/linuxcnc/ru/?checksum=7f7be0d15d68818e

Also see that user accepting a translation for Tor VPN "Circuits" with "Racing Tracks":
https://hosted.weblate.org/translate/tor/tor-vpn/ru/?checksum=27a2b1aa0330fc56

**Comment by petterreinholdtsen** [comment]
I created an open issue to put the topic higher on the radar of the developers, see https://github.com/LinuxCNC/linuxcnc/issues/2667 .

**Comment by andypugh** [comment]
The first example does strike me as wrong, it seems to translate "Home" literally as "House" for example.

**Comment by dsa-t** [comment]
If I would be using LinuxCNC, the original translations by @aystarik look more correct.

In the first case:
Hand wheel == MPG == РГИ
https://darxton.ru/catalog_section/generatory-impulsov-ruchnye-mpg/

**Comment by petterreinholdtsen** [comment]
[dsa-t]
> I'm not especially interested in contributing to LinuxCNC translations
> since I don't use it. I'm just reporting about the damage this user is
> causing to various projects. I'm not in the IRC.

Thank you for the heads up.  I've tried to email xXx to see what he go
to say, and will try to follow up on this to see what the Russian
speaking LinuxCNC community recommend we do about this.

The change set since before xXx started contributing to the Russian
translation via Weblate is 2080 lines long since commit
cac8149badd9a295dde4a803c282f997de380eef for src/po/gmoccapy and 12906
lines long since commit 00d5f25386b1b5d02b7d940837fe5f1eef8600f3 for
src/po.  He did not contribute to docs/po/ as far as I can tell.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Petter Reinholdtsen]
> I've tried to email xXx to see what he go to say, and will try to
> follow up on this to see what the Russian speaking LinuxCNC community
> recommend we do about this.

I decided to block xXx from contributing to LinuxCNC translations on
Weblate until I hear from him, to avoid making any revertion task any
larger.

I see IlyaKw has been updating at least some of the translations done by
xXx, no idea if it made it better or worse, but hope for the latter.  I
suspect this mean it is easier to update than to revert moving forward.
-- 
Happy hacking
Petter Reinholdtsen

**Pull request merged**
