### PR TITLE
Fix tests in state tags

### PR DESCRIPTION
**Pull request by zultron**
@andypugh has test-merged the state tags work into master and reported test failures.  This should fix them.

Also silence a compiler warning.  (This ought to be filed as a separate PR to mainline branches.)

### CODE REVIEW

**Comment by zultron** [comment]
- The `g64` test fix follows aa4d20b9
- The `motion-logger` test fix follows bf873146
- I'm not sure yet why the `m98m99` failures

**Comment by zultron** [comment]
- The `m98m99` failures are explained by the 314669b4 commit log

**Comment by zultron** [comment]
Updated commit log to document **why** the changes.

**Comment by andypugh** [comment]
Thanks for this.

**Comment by andypugh** [comment]
There are three places where the code refers to "NAX_ARITY" and I am fairly sure I have already seen a commit float past that fixed some of them. 
I would guess that the cleanest fix would be to cherry-pick this to master, then add another commit to fix the other two? (to make this branch easier to merge back to master)

**Comment by phillc54** [comment]
I just gave it a try and all runtest passed except startup-gcode-abort

**Pull request merged**
