### PR TITLE
Changed translated documentation build rules to generate file lists

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
Instead of listing each individual translated document in Submakefile,
generate the lists from the files on disk.

Renamed LinuxCNC_Developer_Manual.pdf to LinuxCNC_Developer.pdf,
LinuxCNC_User_Manual_fr.pdf to LinuxCNC_User_fr.pdf and
LinuxCNC_HAL_Manual_fr.pdf to LinuxCNC_HAL_fr.pdf to be able to
generate PDF file name directly from AsciiDoc file name.

Removed Master_Integrator_es.adoc as it was only including non-existing
files.

### CODE REVIEW

**Review by jepler — COMMENTED** [review]
This seems like a good start. I noticed there are curently ".desktop" files that also refer to at least some of the document PDFs, which are renamed here. Do the desktop files need to be updated as well?

**Comment by petterreinholdtsen** [comment]
Yes, fixed.  I am also unsure why the htmldocs test fail, hope to find a fix for it.

**Comment by petterreinholdtsen** [comment]
Found a fix for the htmldocs issue.  One file was incorrectly listed in DOC_SRCS_FR instead of DOC_SRCS_EN, and another file was incorrectly included in git.

**Review by jepler — APPROVED** [review]
Thanks. 

A future PR could consider moving "Master_foo.adoc" to LinuxCNC_foo.adoc", and simplify, I suppose.

I wonder if there's a path to making DOC_SRCS_EN generated, by using a $(filter-out) of all the language-specific files.

**Comment by petterreinholdtsen** [comment]
[Jeff Epler]
> A future PR could consider moving "Master_foo.adoc" to
> LinuxCNC_foo.adoc", and simplify, I suppose.

Yeah.

> I wonder if there's a path to making DOC_SRCS_EN generated, by using a
> $(filter-out) of all the language-specific files.

Once we move to po4a, there will be no translated adoc files in the
source, only PO files.

--
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
And what about merging LinuxCNC_User_fr.pdf and LinuxCNC_HAL_fr.pdf to LinuxCNC_Documentation_fr.pdf ?
Then it would be more consistent compares to the other PDF files.

```
LinuxCNC_Developer_es.pdf
LinuxCNC_Developer.pdf
LinuxCNC_Documentation_es.pdf
LinuxCNC_Documentation.pdf
LinuxCNC_Getting_Started_es.pdf
LinuxCNC_Getting_Started_fr.pdf
LinuxCNC_Getting_Started.pdf
LinuxCNC_HAL_fr.pdf  <----
LinuxCNC_Integrator_fr.pdf
LinuxCNC_Integrator.pdf
LinuxCNC_Manual_Pages.pdf
LinuxCNC_User_fr.pdf <----
```

**Comment by petterreinholdtsen** [comment]
[Hans]
> And what about merging LinuxCNC_User_fr.pdf and LinuxCNC_HAL_fr.pdf to
> LinuxCNC_Documentation_fr.pdf ?  Then it would be more consistent
> compares to the other PDF files.

I do not see the point now, as the migration to po4a will remove them
completely and ensure all translations stay consistent with the English
edition all the time.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
Okay the po4a solution will be much better and makes this superfluous :)

**Pull request merged**
