### PR TITLE
English anchors

### PR DESCRIPTION
**Pull request by smoe**
The build failure of https://github.com/LinuxCNC/linuxcnc/pull/1356 has its roots in the _fr files, so I though I should start with them. grepped for all that is somewhere enclosed by [[ .. ]]s and then counted in how many files this is found. This gives a list like:
```
...
fig:Outil-Positions-1-2-3-4:3
fig:Outil-Positions-5-6-7-8:3
sec:Orientations-des-outils-de-tour:2
cha:Cinematique:1
cap:Bipod-setup:1
sec:Forward-transformation:2
sec:Inverse-transformation:1
cha:Regulation-PID:1
cha:Reglages-de-pas-a-pas:1
cha:Concepts-pour-utilisateur:2
cha:linuxcnc-user-introduction:3
sec:Comment-Fonctionne-LinuxCNC:1
fig:Interface-graphique-AXIS:1
...
```
The number after the colon indicates the number of files (not the number of occurrences) that this anchor is found in. Anything with a number larger than 1 needs to be checked of po4a covers the file with the anchor and preferably be changed to the English variant to be future-proof.

One problem with https://github.com/LinuxCNC/linuxcnc/pull/1356 was that the gcodes and/or mcodes did not make it through po4a, with _fr and _en differing in the anchor naming scheme. This PR should fix that.

This PR is a continuation of https://github.com/LinuxCNC/linuxcnc/pull/1516. Please accept that first.

### CODE REVIEW

**Comment by smoe** [comment]
The filenames are changed such that all translated files have the same filename as the original plus their language identifier added with an underscore as separator. The qtvcp_* files do not have many translations, but they will get them via po4a. I have taken some freedom to rename these files to qtvcp-*.

**Comment by smoe** [comment]
@silopolis -  I'll eventually get this to build again :) The annoying bit is that I am likely to produce conflicts with what you are currently curating since the structure of anchor names in the _fr files is rather different from the _es and _en files. The "easiest" may be that you send a PR with whatever you have once the "changes.." PR was merged and I then rebase on that.

**Comment by smoe** [comment]
@silopolis - you can take over from here with your _fr changes. And then, well, this will be tedious again, but we .po generation needs to be redone.
@silopolis  - since this likely will just be the two of us, maybe we do not need the ultimate style guide upfront? I suggest that you just do whatever _fr file you are working on in a darn good way and then I learn from that file? Or ping me about it whenever you want to discuss that.

**Comment by silopolis** [comment]
I told JT I'll give a quick shot at its Mesa tools translations. Friend needed a tool for its 7i80 and JT immediately started working on it.

Depending on the amount of work, I'll translate the 7i80 tool and then I'll rename and start the rebasing of my translate-po4a branch on this...

**Comment by andypugh** [comment]
I re-ran the checks and the conflicts still exist.

**Comment by smoe** [comment]
@andypugh - rebased and it still builds!

**Pull request merged**
