### PR TITLE
BarWidgetr fix missing cfg dir 'touchy'

### PR DESCRIPTION
**Pull request by tjtr33**
Mistake : delted touchy dir when trying to delte dir tomp
So i grabbed a cioy of touchy dir form masterm copied to local repo
added all the gile
commit, push and now new PR

### CODE REVIEW

**Comment by tjtr33** [comment]
What is the copnflict? Of course my push has a new lib/pyvcp_widgets.py
Thats where master has it and I push a new version.

**Comment by andypugh** [comment]
I am a bit confused by these PRs. Can you tell me what the current situation is, which are live, and which have been  supeceded?

**Comment by smoe** [comment]
This looks like quite an effort but was a bit overwhelming for me, too :)
@tjtr33 , I suggest to rebase your developments to the current master branch and maybe squash all those commits into one that should be reviewed together.

**Comment by andypugh** [comment]
Closing this, I think it has been overtaken by events. Feel free to re-open if you disagree.

**Pull request closed without merging**
