### PR TITLE
strncpy -> rtapi_strlcpy for string termination

### PR DESCRIPTION
**Pull request by smoe**
Stuttgart LinuxCNC attempt to address compiler warnings.

Using rtapi_strlcpy to always have 0-terminated strings.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
"libnml/buffer/shmem.cc:318:10: error: ‘rtapi_strlcpy’ was not declared in this scope"

Missing include file?

**Comment by gmoccapy** [comment]
linuxcnc stuttgart meeting (norbert not to blame) says merge when CI passes. eventually convert to std::string.

**Comment by petterreinholdtsen** [comment]
The std::string proposal came up in https://github.com/LinuxCNC/linuxcnc/pull/1922 too.  How can we decide if we want to move towards std::string or not?

**Comment by smoe** [comment]
Some tests are failing:
```
Running test: ./tests/twopass-personality
Running test: ./tests/twopass
Running test: ./tests/uspace/spawnv-root
Runtest: 259 tests run, 257 successful, 2 failed + 0 expected, 1 skipped
Failed: 
	./tests/motion-logger/mountaindew
	./tests/remap/remap-io
```
Let's see if that also happens for other PRs or if I have indeed messed something up.

**Comment by petterreinholdtsen** [comment]
I rebased the change on top of the 2.9 branch, and did some minor
cleanup.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request merged**
