### PR TITLE
(`statetags` branch) Restore G61/G61.1/G64 state after abort

### PR DESCRIPTION
**Pull request by zultron**
This PR is against the `statetags` branch as part of #134

- Restore motion mode and G64 tolerances after abort; fix for issue #177
  - Also convert G64 tolerances at G20/G21
  - Also save/restore naive CAM tolerance at indexing and canned cycles
- Make G64 tolerances available via python `status.settings[3:5]`
- Add regression test demonstrating #177 and testing this work
- Fix a couple of bugs in the `statetags` tree

### CODE REVIEW

**Comment by zultron** [comment]
...the Travis CI build failed because of an unrelated error:
```
configure: WARNING: The LinuxCNC binary you are building may not be
distributable due to a license incompatibility with LinuxCNC (some portions
GPL-2 only) and Readline version 6 and greater (GPL-3 or later).
```

**Comment by jepler** [comment]
The travis-ci build bug should be fixed by 5ce31592ef904e7f9b37691357cb86e62c667100.  If this branch is from before that commit (it appears to be) then travis-ci builds will fail.  it should not block acceptance of this PR, though I encourage to arrange for travis-ci or buildbot to test the result of merging this with master before it is accepted.

**Comment by zultron** [comment]
Thanks for the hot tip, @jepler.  The build is passing.

**Comment by zultron** [comment]
@robEllenberg

**Comment by c-morley** [comment]
@zultron Hey Is this still relevant? i would like to get staetags rolling again.

**Comment by gmoccapy** [comment]
Will this be merged soon? I hope so.

Norbert

**Comment by andypugh** [comment]
I guess there is no reason not to merge this to Statetags?

**Pull request merged**
