### PR TITLE
Phillc54/pncconf

### PR DESCRIPTION
**Pull request by phillc54**
2b3cbf8 starts home sequences at 1 and uses comboboxes to input home sequences. This is a response to [Issue: 2616](https://github.com/LinuxCNC/linuxcnc/issues/2616) and [PR: 2621](https://github.com/LinuxCNC/linuxcnc/pull/2621)

95b5804 validates that home sequences start at 1 and are sequential. It is a bit sketchy in that it does call save(base) which has been called previously.

### CODE REVIEW

**Comment by c-morley** [comment]
I wonder if we could make a validate function in pncconf.py and call it here ()from pncconf.py line 330 or so:


    def buid_config(self):
        base = self.build_base()
        self.validate_database() : <<<< here
        self.d.save(base)
        #self.write_readme(base)
        self.INI.write_inifile(base)
        self.HAL.write_halfile(base)`

**Comment by phillc54** [comment]
That does make more sense. I hope this is what you had in mind...
It now shows a dialog listing any changes and should be easy enough to add any other validation checks.

**Comment by c-morley** [comment]
Thanks Phill - that looks good.

**Comment by zz912** [comment]
Hello,

I tested to see if the new PncConf would work with an old configuration where some axis had a home sequence of 0. It worked fine.

Then I try to configure X X2 Y Z Z2 kinematics.
PNCconf-home_sequence-001

It is actually XYZ kinematics with tandem joints. It offered me 4 home sequence options instead of 3.
PNCconf-home_sequence-002

I tried to create a bad sequence on purpose 1, 3, 4. Fortunately, PncConf fixed it for me.
PNCconf-home_sequence-003

**Comment by c-morley** [comment]
This would adjust the combobox (in pages.py):

    def base_finish(self):
        machinename = self.w.machinename.get_text()
        self.d.machinename = machinename.replace(" ","_")
        self.w.window1.set_title(_("Point and click configuration - %s.pncconf ") % self.d.machinename)
        self.d.axes = self.w.axes.get_active()
        if self.d.axes == 0: self.d.available_axes = ['x','y','z','s']
        elif self.d.axes == 1: self.d.available_axes = ['x','y','z','a','s']
        elif self.d.axes == 2: self.d.available_axes = ['x','z','s']

        # adjust home sequence model
        model = self.w.xhomesequence_store
        model.clear()
        for count, i in enumerate(('1','2','3','4')):
            if count == len(self.d.available_axes)-1:
                break
            else:
                model.append((i,))
``

**Comment by phillc54** [comment]
Is [this](https://github.com/LinuxCNC/linuxcnc/pull/2660/commits/5d98464929b29f6a8b61c1ab5233d8f2e17b83c2) OK?

**Comment by c-morley** [comment]
Ahh yes of course that's the right way :)

**Comment by phillc54** [comment]
Thanks Chris, I had intended to look at this when I got back home today and you saved me a bit of work.
Is this OK to merge now?

**Comment by c-morley** [comment]
No problem Phill.
Thanks to zz912 testing.
I think merging would be good. Andy is getting close to releasing it seems.

**Comment by zz912** [comment]
Hello,

I hope I won't be unpopular.

I configured X Y Z Z2 A kinematics.
PNCconf-home_sequence-004

It is actually XYZA kinematics with one tandem joints. It offered me only 3 home sequence options instead of 4.
PNCconf-home_sequence-005

The bigger problem is that the sheet for the A axis has disappeared.

**Comment by phillc54** [comment]
Well that is strange, it is working for me:
Screenshot 2023-10-02 at 3 26 45 pm

**Comment by zz912** [comment]
Could you send me your *.pncconf ?

Here is mine:
[test-home_sequence-002.pncconf.txt](https://github.com/LinuxCNC/linuxcnc/files/12779659/test-home_sequence-002.pncconf.txt)

**Comment by c-morley** [comment]
Looks like you created a XYZ machine but added a A axis stepgen.
make a XYZA machine

**Comment by phillc54** [comment]
Yours is XYZ only.
Screenshot 2023-10-02 at 3 37 35 pm

Here is mine:
[plasma_table copy.pncconf.txt](https://github.com/LinuxCNC/linuxcnc/files/12779685/plasma_table.copy.pncconf.txt)

**Comment by zz912** [comment]
It works for me now. I apologize for the confusion.

**Comment by phillc54** [comment]
No worries at all, thank you for your testing.

**Pull request merged**
