### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [LinuxCNC/LinuxCNC Documentation](https://hosted.weblate.org/projects/linuxcnc/linuxcnc-docs/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by smoe** [comment]
@hansu @petterreinholdtsen  - this PR of weblate also built.

**Comment by hansu** [comment]
Why couldn't you wait until we get a solution to get rid of that mass of commits as I said yesterday???
I didn't marked it as draft just for fun!

**Comment by petterreinholdtsen** [comment]
[Hans]
> Why couldn't you wait until we get a solution to get rid of that mass
> of commits as I said yesterday???

Mostly because I did not understand that it was a problem, and did not
notice you said so. I failed to find you on IRC and send you a Signal
message when I started, to give you a heads up.  It took several hours
from I started looking at it until I completed the merge.

> I didn't marked it as draft just for fun!

Is there some way to figure out who marked a PR as draft?  I tried to
figure it out, but found no indication that it was not done by mistake.

If we want to hide from git the fact that several translators worked in
sequence, we can rebase and squash while resolving a lot of squash
conflicts, but I fail to see that the advantages of such hour long
effort, a slightly prettier git history, outweigh the effort spent to do
so.

While I was working, the weblate lock disappeared.  No idea why, and
no-one on IRC have commented on it so far.  I have relocked to make sure
I can sync weblate before we get any new conflicts there.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
>mostly because i did not understand that it was a problem,

Not a problem but >70 commits without source changes doesn't really help to keep the overview of changes.  

>and did not notice you said so.   

Ok then i can completely step out of the meetings. Maybe you would like to host the next one?

> I tried to figure it out, but found no indication that it was not done by mistake.

What about this?
grafik

**Comment by petterreinholdtsen** [comment]
[Hans]
> Not a problem but >70 commits without source changes doesn't really
> help to keep the overview of changes.

Every commit had source changes to files in docs/po/.  The issue was
that two people translated german strings one after the other, causing
many commits to order the changes.

> Ok then i can completely step out of the meetings. Maybe you would
> like to host the next one?

It was probably more me stepping out of the meeting to handle kids, and
missing some parts because of distractions.  Sorry about that.  I am
happy to host meetings.

> What about this?
> grafik

No idea why, but that information fragment do not show up in my github
view.  I digged further, and found it hidden in a collapsed screen.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
Sorry, was not aware of it either, and me pinging you has not helped. It seems like there is a problem with how weblate handles the editing of suggestions. Do you know how I can reach out to translators?

**Pull request merged**
