### PR TITLE
Gmoccapy stop button / fix in translation

### PR DESCRIPTION
**Pull request by hansu**
-  disable stop button in gmoccapy when idle/stopped
- enable scrolling in gcode when paused
-  fix some translations, see https://github.com/LinuxCNC/linuxcnc/issues/1111

### CODE REVIEW

**Comment by gmoccapy** [comment]
The Pause button sensitive state has been fixed with https://github.com/LinuxCNC/linuxcnc/commit/2c72a5680846b01cae1ffb573abad47644cd9355

**Comment by gmoccapy** [comment]
The translation errors have been corrected with https://github.com/LinuxCNC/linuxcnc/commit/d42e994987120b859b7cb280c08dff66a9900e49

**Comment by gmoccapy** [comment]
As far as I can see, all required stuff has been solved now. I am sorry I did solve them with individual pushes, but this way it is clearer to see what have been solved which way.

Hans, please report if this can be closed now.

**Comment by jepler** [comment]
Closing based on comments from @gmoccapy — Please feel free to open a new PR if additional changes are needed!  Thank you.

**Comment by hansu** [comment]
As it is related to #1111 I wanted to close this if Norbert did the changes also in 2.8, what he wanted to do (see https://github.com/LinuxCNC/linuxcnc/issues/1111#issuecomment-841521274).

**Pull request closed without merging**
