### PR TITLE
Docs typos

### PR DESCRIPTION
**Pull request by smoe**
As usual, something spotted while translating.

Please kindly confirm my interpretation "neither between" in docs/src/drivers/hal_gpio.adoc line 57.
Admittedly this PR was mostly motivated as a technical excercise to work with WSL.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I assume you are talking about this sentence: The pin names are case-sensitive and there must be no spaces in the strings, neither between the comma-separated pins lists of the "=" signs.

I would write "no spaces in the string, nor between the comma-separated pins" instead myself.  No native speaker, so not sure if it truly better.

**Comment by hansu** [comment]
Both is fine I guess.
We can also write:

(3) 
`The pin names are case-sensitive and there must be no spaces in the strings, not even between the comma-separated pins lists of the "=" signs.`

or

(4)
`The pin names are case-sensitive and there must be neither spaces in the strings, nor between the comma-separated pins lists of the "=" signs.`

But I would prefer (1) (Steffens version) or (2) (Petters version).

**Comment by smoe** [comment]
Heya, please then ("either" of you, pun intended) merge my request since this saves time, is apparently good enough, and closest to the original.

 




But I would prefer (1) (Steffens version) or (2) (Petters version).

**Comment by hansu** [comment]
I agree :)

**Pull request merged**
