### PR TITLE
English anchors more beautifications

### PR DESCRIPTION
**Pull request by smoe**
Stuff that I thought could have some wait in my local repository until I came across getting-started/pncconf_fr.adoc and its images that should be in config/ together with its counterparts from other lingos.

### CODE REVIEW

**Comment by smoe** [comment]
This was rebased on https://github.com/LinuxCNC/linuxcnc/pull/1670, was a few patches only.

**Comment by smoe** [comment]
The _fr documentation got a bit confused over all the files I moved between directories and somehow the anchors in stepconf_fr.adoc did not make into the check.  My answer now is to cut any exception that _fr is doing to the builds so what builds for _en should also work for _fr. Well, I am writing this while the build is still running.

**Comment by smoe** [comment]
@silopolis I admittedly guessed that you may have done something like that but was a bit desperate with the error message that did not want to disappear :) We should to get our efforts merged. The questions is - how. 

I could merge what you have but would prefer if you go through master. How would you like the following approach:
 * you rebase your po4a branch to the current master 
 * you prepare a diff against master into something like po4a_fr_20220324.patch
 * you remove the po4a scripts of @petterreinholdtsen  from that patch
 * from master, not the po4a branch, you branch of with a new "changes_to_prepare_FR_for_po4a"-branch 
 * you apply that patch and commit
 * you get it to build, commit and push for a PR
 * I merge your effort with mine with this branch

And then it may be time to recap what remains to be done.

Best,
Steffen

**Comment by smoe** [comment]
This builds for me.

**Comment by smoe** [comment]
@hansu , @petterreinholdtsen , @silopolis , it builds. No idea why it now builds, but it builds. It took so long since I had removed some more all-English files that only existed because of the anchors. I also removed quite a few anchors that are not referenced anywhere. I only hope that these simplifications are indeed as helpful to get po4a going as I expect them to be. My reasoning was that anything that is not existing we also do not need to keep in sync for the po4a generation.

Something unexpected I did was, after a discussion with @petterreinholdtsen about using the underscore only to separate the language tag, to rename the docs/src/Master_Documentation etc documents to have a hyphen, i.e. it is Master-Documentation etc now. The only exception to this rule that I am aware of is in the man pages since there are binaries with an underscore. 

@silopolis, please have a look at what I have done. I hope that you, and @petterreinholdtsen,  like this enough to consider this as a target to merge your _fr/po4a changes with. Secondo me, we can then have our first iterations of .po file generations.

@petterreinholdtsen , I had given it some thoughts and liked the idea to have separate .po files for each subfolder of the documentation. How do you think about this? My motivation is to have some (presumed more important) fragments of the documentation translated earlier than others, and (more importantly) to have translators assign themselves to those areas where they feel to have some expertise.

Cheers,
Steffen

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> @silopolis, please have a look at what I have done. I hope that you,
> and @petterreinholdtsen, like this enough to consider this as a target
> to merge your _fr/po4a changes with. Secondo me, we can then have our
> first iterations of .po file generations.

I believe it should go in separtely from my translate-po4a branch,
either before or after it.  It will cause conflicts with my branch
because the po4a.cfg file list all the English originals and I removed
the old translated files, but it a trivial modification.

> @petterreinholdtsen , I had given it some thoughts and liked the idea
> to have separate .po files for each subfolder of the
> documentation. How do you think about this? My motivation is to have
> some (presumed more important) fragments of the documentation
> translated earlier than others, and (more importantly) to have
> translators assign themselves to those areas where they feel to have
> some expertise.

Great idea, and I tried, but the required feature is not implemented in
my version of po4a.  It is the "In split mode, allow to group several
files within the same POT file."  feature in po4a version 0.65.  I thus
believe it is something we should look at later, when we no longer need
to build with older po4a versions.

--
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
@petterreinholdtsen - It should definitely go in before your's since the only purpose of this effort is to help your po4a cause by removing differences between languages and by removing parts that are not translated :)

I am tempted to suggest to update the po4a package of ours, then :)

**Comment by silopolis** [comment]
Le ven. 25 mars 2022 à 12:52, petterreinholdtsen ***@***.***>
a écrit :

> [Steffen Möller]
> > @silopolis, please have a look at what I have done. I hope that you,
> > and @petterreinholdtsen, like this enough to consider this as a target
> > to merge your _fr/po4a changes with. Secondo me, we can then have our
> > first iterations of .po file generations.
>
> I believe it should go in separtely from my translate-po4a branch,
> either before or after it. It will cause conflicts with my branch
> because the po4a.cfg file list all the English originals and I removed
> the old translated files, but it a trivial modification.
>

Then let's merge all pending mods into master, then I'll merge my _fr/po4a
work there too. After that, we *freeze* docs in master until po4a/weblate
toolchain is in place and running. Finally, as suggested by @smoe, we fix
and push languages one after the other.


> > @petterreinholdtsen , I had given it some thoughts and liked the idea
> > to have separate .po files for each subfolder of the
> > documentation. How do you think about this? My motivation is to have
> > some (presumed more important) fragments of the documentation
> > translated earlier than others, and (more importantly) to have
> > translators assign themselves to those areas where they feel to have
> > some expertise.
>
> Great idea, and I tried, but the required feature is not implemented in
> my version of po4a. It is the "In split mode, allow to group several
> files within the same POT file." feature in po4a version 0.65. I thus
> believe it is something we should look at later, when we no longer need
> to build with older po4a versions.
>

If we were to split po files, I'd surely prefer having one per file, or one
per Master* than one per directory as this last option doesn't make sense
to me 🤔

**Comment by smoe** [comment]
Motivation to split are:
 * match with translator's expertise
 * have an earlier feeling of success when something approaches the 95% translation
 * we do not have all the pressure upfront to sync all the files between es/fr and en, but then again, it is not _that_ bad.

**Comment by silopolis** [comment]
Le jeu. 24 mars 2022 à 13:10, Steffen Möller ***@***.***> a
écrit :

> @silopolis <https://github.com/silopolis> I admittedly guessed that you
> may have done something like that but was a bit desperate with the error
> message that did not want to disappear :) We should to get our efforts
> merged. The questions is - how.
>
> I could merge what you have but would prefer if you go through master.
>
So do I, putting master in a linted, po4a migration ready state for all
langs always seemed the better way to me.

How would you like the following approach:
>
>    - you rebase your po4a branch to the current master
>    - you prepare a diff against master into something like
>    po4a_fr_20220324.patch
>    - you remove the po4a scripts of @petterreinholdtsen
>    <https://github.com/petterreinholdtsen> from that patch
>    - from master, not the po4a branch, you branch of with a new
>    "changes_to_prepare_FR_for_po4a"-branch
>    - you apply that patch and commit
>    - you get it to build, commit and push for a PR
>    - I merge your effort with mine with this branch
>
> How's that better than branching from master and cherrypicking from my
po4a branch ?


>
> And then it may be time to recap what remains to be done.
>
> Maybe twice 😅

**Comment by smoe** [comment]
@SebKuzminsky , I mentioned it above, I have changed the LinuxCNC_* etc files to LinuxCNC-Development/LinuxCNC-Documentatation/LinuxCNC-Getting-Started/LinuxCNC-Manual-Pages. Is that ok with you? @petterreinholdtsen, you do not really care, right for po4a, or do you?  The movitaton was to have the language suffices separated by an underscore and not use the underscore elsewhere, but I should not have embedded this in this PR. Shall I undo this?

**Comment by silopolis** [comment]
Le ven. 25 mars 2022 à 15:20, Steffen Möller ***@***.***> a
écrit :

> Motivation to split are:
>
>    - match with translator's expertise
>    - have an earlier feeling of success when something approaches the 95%
>    translation
>    - we do not have all the pressure upfront to sync all the files
>    between es/fr and en, but then again, it is not *that* bad.
>
> I'm all in on all points !
Then let's have a po per adoc file !?

**Comment by smoe** [comment]
>How's that better than branching from master and cherrypicking from my
> po4a branch ?

I presume it is pretty much the same thing, just manual.

**Comment by smoe** [comment]
> I'm all in on all points !
> Then let's have a po per adoc file !?
Not sure. Looks a bit weird in Weblate? Also, many files seem a bit short.

**Comment by smoe** [comment]
@hansu , this is what @silopolis ' po4a "match the _en and _fr files"-branch should rebase on. In principle this would be something for the docs-devel-branch, except that @petterreinholdtsen 's branch removes the _es and _fr files, so we cannot continue the update of the .po files in said docs-devel-branch.

I am not 100%ish sure about how to then continue. Someone needs to redo the _es and _fr .po file generation. @petterreinholdtsen , is that you or me? Also, someone needs to prepare the _es and _fr files for this. @silopolis, is that you? I suggest that I stop working on the po4a bits until I hear from either of you to work through some next step with me. That way I do not confuse anyone.

@hansu , if you do not mind too much, please accept this PR for master again. My work then stops here.

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> I am not 100%ish sure about how to then continue. Someone needs to
> redo the _es and _fr .po file generation. @petterreinholdtsen , is
> that you or me?

It is you.  I focus exlusively at the build system at the moment, and am
perfectly happy to use the previously generated PO files and handle the
rest of the translation work on weblate.  Nothing against a PO file
update before we move to weblate, just not something I will spend time on.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
Touchy_es was surprisingly close to the original. Good it is back. Thanks again.

**Comment by hansu** [comment]
Now ready for merge?

**Comment by smoe** [comment]
Once it builds, yes, please. I just hope there wasn't another reference to something non-existing.

**Comment by hansu** [comment]
Nice, Thank you!

**Comment by smoe** [comment]
@hansu - great, many thanks for your review!
@silopolis - now it's about getting your changes to *_fr.adoc in and in particular all the reverse-translations to _en merged.

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> @SebKuzminsky , I mentioned it above, I have changed the LinuxCNC_*
> etc files to
> LinuxCNC-Development/LinuxCNC-Documentatation/LinuxCNC-Getting-Started/LinuxCNC-Manual-Pages. Is
> that ok with you? @petterreinholdtsen, you do not really care, right
> for po4a, or do you?  The movitaton was to have the language suffices
> separated by an underscore and not use the underscore elsewhere, but I
> should not have embedded this in this PR. Shall I undo this?

I would like for you to delay such improvements until after we get the
po4a build patch merged into master, as it will affect both po4a.cfg and
Submakefile, and instead help me figure out why the po4a build branch is
failing on github and not when I build locally.  Note I do not expect
the changes to be more than simple string substitutions, so no big
deal. :)

Please, lets wait with the most restructuring until po4a is in master.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request merged**
