### PR TITLE
Add HAL-OUT pin "gmoccapy.ignore-limits-active"

### PR DESCRIPTION
**Pull request by srdco**
Adds HAL-OUT pin "gmoccapy.ignore-limits-active." Activated when "Ignore Limits" checkbox is clicked and ignore limits is OK'd and activated by GMOCCAPY. Useful for notifying PLC/hardware that ignore limits is active without adding a physical ignore limits (override limits) button.

Signed-off-by: Timothy Snowden <timothy@solidrock-ent.com>

### CODE REVIEW

**Comment by srdco** [comment]
Not sure why Travis CI failed? I didn't add anything that should have depended on any new packages. Works just fine on my RIP install (2.7.8).

**Comment by jepler** [comment]
@srdco I'll look at the travis-ci failure.  I believe it's not connected to your PR and should not block it from being accepted.

**Comment by jepler** [comment]
@srdco Due to other changes, the travis-ci build now passes.

@gmoccapy can you please test this patch and see whether it is appropriate?  I tried to test it, but even when I could toggle the state of the "ignore limits" checkbox, it appeared the HAL value was not changing.

**Comment by srdco** [comment]
Hmmm... I haven't checked with the latest updates because the machine I have this on is not on an internet network, but it is working beautifully on a build that was current as of February.

**Comment by gmoccapy** [comment]
body {font-family: 'monospace';}I will do asap.

Norbert
Von meinem Fonepad gesendet
Jeff Epler  schrieb:@srdco Due to other changes, the travis-ci build now passes.
@gmoccapy can you please test this patch and see whether it is appropriate?  I tried to test it, but even when I could toggle the state of the "ignore limits" checkbox, it appeared the HAL value was not changing.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LinuxCNC/linuxcnc","title":"LinuxCNC/linuxcnc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/LinuxCNC/linuxcnc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jepler in #237: @srdco Due to other changes, the travis-ci build now passes.\r\n\r\n@gmoccapy can you please test this patch and see whether it is appropriate?  I tried to test it, but even when I could toggle the state of the \"ignore limits\" checkbox, it appeared the HAL value was not changing."}],"action":{"name":"View Pull Request","url":"https://github.com/LinuxCNC/linuxcnc/pull/237#issuecomment-300778476"}}}
I will do asap.NorbertVon meinem Fonepad gesendetJeff Epler <notifications@github.com> schrieb:@srdco Due to other changes, the travis-ci build now passes.
@gmoccapy can you please test this patch and see whether it is appropriate?  I tried to test it, but even when I could toggle the state of the "ignore limits" checkbox, it appeared the HAL value was not changing.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LinuxCNC/linuxcnc","title":"LinuxCNC/linuxcnc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/LinuxCNC/linuxcnc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jepler in #237: @srdco Due to other changes, the travis-ci build now passes.\r\n\r\n@gmoccapy can you please test this patch and see whether it is appropriate?  I tried to test it, but even when I could toggle the state of the \"ignore limits\" checkbox, it appeared the HAL value was not changing."}],"action":{"name":"View Pull Request","url":"https://github.com/LinuxCNC/linuxcnc/pull/237#issuecomment-300778476"}}}

**Comment by gmoccapy** [comment]
This has already been solved and implemented with 
gmoccapy 1.5.7 (linuxcnc 2.7)
gmoccapy 2.2.3 (linuxcnc 2.8)

Can somebody delete this pull request?

Norbert

**Comment by srdco** [comment]
Unless I'm missing something, I believe that the changes you are referencing, Norbert, allow an ignore-limits pins to be set by an external command.
This commit exposes that status of IGNORE-LIMITS via a hal-pin in order for other hardware/PLC to always know when IGNORE-LIMITS is active.

**Pull request closed without merging**
