### PR TITLE
Master: revert addition of broken config 

### PR DESCRIPTION
**Pull request by Sigma1912**
this reverts the changes made by these 4 commits:

https://github.com/LinuxCNC/linuxcnc/commit/dd88dc51dc00f8b4beeba2d1d994fbe592fcf1c5
https://github.com/LinuxCNC/linuxcnc/commit/5c3aa31e1c769c738d82aff4f01a235fdbe4f3b9
https://github.com/LinuxCNC/linuxcnc/commit/5fea6903773e42d0f9d7f561496d001543d16fc8
https://github.com/LinuxCNC/linuxcnc/commit/6e84469f5968b97bc01bf71555d15131b7407eea

and restores pyvcp_widgets.py to the last commit before these changes.

Reasons:

1. most of these commits have no meaningful commit message
2. adds two new folders to prominent places (ie root and configs directories) without following the established directory structure (eg using the authors username as folder name)
3. contain absolute paths from the authors local machine
4. author who pushed these has not replied to legitimate questions about these commits and the username seems unknown to GitHub, so it is unlikely that any messages are reaching the individual behind these commits.
5. trailing white space in the code
6. the config fails on load due to inappropriate absolute paths used

 On a personal note I find it rather surprising that after 9 months and two new folders in prominent places this has apparently not attracted the attention of any of the other contributors with push rights to this project. If I were to file a PR like this I would be blown right out of the water and rightly so.

Thanks.

### CODE REVIEW

**Comment by smoe** [comment]
I looked at the commits and am also a bit surprised. Was this a direct commit?

**Comment by hansu** [comment]
It looks like all are from https://github.com/LinuxCNC/linuxcnc/pull/2756

I also agree that the "lib/grfx" looks weird and also the sim config should not be in a user's folder.

**Comment by Sigma1912** [comment]
Note that 'grfx' is not in the 'lib' folder, it's a new root folder. I would also like to point out that there have been questions about this 8 months ago by another member:
https://github.com/LinuxCNC/linuxcnc/commit/5c3aa31e1c769c738d82aff4f01a235fdbe4f3b9

**Comment by hansu** [comment]
>Note that 'grfx' is not in the 'lib' folder, it's a new root folder. 

Oh...

Have you checked the functionality if we could benefit from that?

**Comment by andypugh** [comment]
Sorry, this is clearly my fault for not looking carefully at the commits. (or, more specifically, at where the files were going)
I was trying to tidy things up loose ends prior to the 2.9.2 release at the time, and obviously didn't give this enough attention.
Partly this was because it came from a long-term LinuxCNC contributor, Thomas  Powderley

**Comment by hansu** [comment]
The config is not working (even when adapting the paths like /home/tomp/linuxcnc-barwidgets/grfx/ ...) and there is no description provided for the config picker.

So I agree to revert those commits.

**Comment by hansu** [comment]
@tjtr33 Feel free to come with a new Pull Request when you cleaned this up a little bit and provide a working configuration (with description). Thanks!

**Comment by tjtr33** [comment]
Hello,
please remove/revert/obliveratee
_all_ of my code/commits
whatever those are in GitSpeak
I have asked many time to remove my code
and was very surprised my last efforts 
left content in the linuxcnc project
I cannot see the keyboard well enough to fix this
( macular degeneratttion)
Please make it all go away
nobody wants it anyway
TomP/tjtr33
Thx Andy fir trying to clean it up
but please just toss it all into the bit bucket

**Comment by hansu** [comment]
@tjtr33 Sad to hear that. But do you have some screenshots to see the functionality of your created widgets to see if they are worth doing some rework and integrating them?

**Comment by tjtr33** [comment]
Hello

here is a screenshot

there are a lot of combination of thge parameters

here are 4

the 1st 2 are th new single linne bar wisgets

one with a png 'thumb'

and one with a python tkinter drawing script

the 1st 2 have pins that ca ve attached to labels to show values

The 4ed is a 'classic; vbar , the min current and max are

displayed centered on the bar

the 4th has data displayed 'e' (east) of the bar

all have a reference mark line struck thru the var

This is different than orig version

which watched changes from 'min'

now user cab display changes about a value of interest

say, the boiling point of waterm or the ideal lumens for some process

I see i font remember how to set fonts, so i didnt touch those parms

and i did not manage to get rangese to work

tho iirc, i did have them working


you can run it yourself using the github rip

halrun

loadusr python -c fred vbar:ine01.xml

and change the values

setp fred.b1 <value between min_ max_ seen in xml>

I hooked them up to siggens once


look at the xml to see how i built the window.

This was all done with a RIO for github about 3 weeks ago,

Other widgets can ve slimmed down too

the 'dial' can be a simple arc and a line

the scale can be like the bar


lemme know what you'd like

tomp

**Comment by hansu** [comment]
>here is a screenshot

The screenshot seems missing...

**Comment by tjtr33** [comment]
sorry

here is teh shot

the halrun window show the pins

that are available for the numbers min max and current

tomp

**Comment by Sigma1912** [comment]
Still no screenshot, I think you may have to add the image directly in the github webpage.
https://github.com/LinuxCNC/linuxcnc/pull/3095

**Comment by tjtr33** [comment]
> You can simply drag the image into the text field. It will be uploaded automatically.

pyvcp_bar_widgets-20240919

i only see text of file name  and opening tyhe url gets me 404
pyvcp_bar_widgets-20240919

or goto imgr to avoid github nonsense
https://ibb.co/309NpsZ

**Pull request merged**
