### PR TITLE
Fix typos in docs subdirectory

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.po,*.pot,*.svg,*.ts,./.git/logs,./share,./docs/man/es,./configs/attic,*_fr.*,*_es.*,README_es,./src/hal/classicladder -L ans,ba,breal,bu,bulle,busses,childs,componentes,currenty,doubleclick,dout,dum,etxt,extint,faktor,fo,fpr,halp,ihs,inout,inport,mot,parm,parms,propertys,ro,seh,ser,smoe,te,tey,trough,ue,ure,wille,wont,wonte`

### CODE REVIEW

**Comment by hansu** [comment]
I guess this PR should go into master? Should I change that?

**Comment by luzpaz** [comment]
I just tried to rebase it onto 2.9 and it was quite nightmarish.

**Comment by hansu** [comment]
Hmm seems that your branch is far away from both branches unfortunately.

**Comment by petterreinholdtsen** [comment]
Yes, the three conflicts need to be resolved before it can go in.  @luzpaz, can you fix it?

**Comment by andypugh** [comment]
Fixed the conflicts.

**Pull request merged**
