### PR TITLE
axis: fix for issue #284

### PR DESCRIPTION
**Pull request by phillc54**
map axes from trajcoordinates rather than assuming xyzabcuvw

Closes: #284 

Signed-off-by: Phillip Carter <phillcarter54@gmail.com>

### CODE REVIEW

**Comment by jepler** [comment]
@pkmcnc can you verify that this fixes your problem

@pkmcnc or @phillc54 does any sample sim configuration have the problem reported in #284 and fixed here?  If not, is there a minimal change I can make to some sample sim config to test?

**Comment by pkmcnc** [comment]
@phillc54 thanks for the fix, I'll test it later today

@jepler the minimal changes are in #284 description:
In sim/axis_mm.ini set
[TRAJ] COORDINATES = X Z A
[KINS] KINEMATICS = trivkins coordinates=xza
Rename [AXIS_ ] sections to X Z A.

**Comment by jepler** [comment]
@pkmcnc that's what I get for posting on bugs first thing in the morning, I see it now.

**Comment by pkmcnc** [comment]
I just tested the fix, it solves the problem
@phillc54 thanks a lot!
@jepler thanks for your help, please merge

**Pull request merged**
