### PR TITLE
Bugfix for stepconf

### PR DESCRIPTION
**Pull request by nicokid**
Resolve some issues on stepconf:
- #86 entry fields blank on stepconf axis pages
- #57 stepconf in 2.7.4 "axis test" popup forgets Velocity and Acceleration settings
- some minor bugfix.

### CODE REVIEW

**Comment by nicokid** [comment]
Fixed the mistake when saving as string the axis values for test. (Sorry).

**Comment by nicokid** [comment]
I changed the code so as to retain the original background color and change it to red only if an error occurs. I think a more efficient way.
Please verify if it works. Thanks.

**Comment by nicokid** [comment]
I forgot to add the style. Sorry I still little familiarity with git.
Nicola.

**Comment by jepler** [comment]
Many of these commits, such as 17f4335, do not follow our signed-off-by policy.  Please create a fresh pull request where all commits follow the policy.

**Comment by nicokid** [comment]
Hi Jeff,
At this time I am confused, I and Git do not agree with each other. This is frustrating...
I tried this command in my local copy:
`git commit --amend --signoff`
And in the end I destroyed my source code...

So I cloned again the copy in my repository:
`git clone https://github.com/nicokid/linuxcnc.git linuxcnc-nicokid`

Now `git branch` report only master.  And `git fetch upstream` report:
fatal: 'upstream' does not appear to be a git repository
fatal: The remote end hung up unexpectedly

I need help. Thanks.
Nicola.

**Comment by nicokid** [comment]
Ok, I got it all right.

**Pull request closed without merging**
