### PR TITLE
Introducing d/watch, d/TODO and d/README.source

### PR DESCRIPTION
**Pull request by smoe**
The README.source describes the steps I am about to take to upload LinuxCNC to Debian. Please comment if you prefer me to do this somehow differently.

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
> W: linuxcnc-uspace-dev: package-name-defined-in-config-h usr/include/linuxcnc/config.h

Seems like we should mangle our `config.h` by prefixing `LINUXCNC_` to every #define that begins with `PACKAGE_`?

**Comment by andypugh** [comment]
> > @smoe , do you know a more standards-compliant technique for having docs in the desktop menu?
> 
> Sorry, no, I don't. If there is any opposition from the FTPmasters to your solution then we go and ask on the debian-devel mailing list. We could ask now :) But maybe that debian/TODO file finds us a volunteer who just knows it and would then stick around for longer.

Perhaps the problem is that we have this:
Exec=xdg-open /usr/share/doc/linuxcnc/LinuxCNC_Documentation.pdf

xdg-open (https://linux.die.net/man/1/xdg-open) does seem like the way to open in the currently installed viewer, but perhaps at the time and place that the build happens either xdg-open is not available, or is not configured. 
FWIW our ISO ships with Atril as pdf viewer, but I don't think that is relevant. 

I actually think we should probably switch to shipping the HTML version of the docs, though that would annoy our one user (Gene) who likes to print out the full docs on to paper.

**Comment by smoe** [comment]
I added xdg-open as a recommendation to the documentation package, so it gets installed by default and not if disk space is an issue. I do not expect the button for the documentation to be of concern to anyone. But, well, I am open for suprises :)

**Comment by SebKuzminsky** [comment]
> I actually think we should probably switch to shipping the HTML version of the docs, though that would annoy our one user (Gene) who likes to print out the full docs on to paper.

I think we should ship both PDF and HTML.

**Comment by smoe** [comment]
> The hardlinks in the deb are created by `dh_movefiles`, which is deprecated and should be replaced with `dh_install`. I'm working on this.

Nice! That also explains why I did not know about dh_movefiles :) From what I oversee, our pre-upload TODO list is then empty. If we have not inadvertently introduced an error, I will then upload. We can upload updates any time.

**Comment by smoe** [comment]
> > The hardlinks in the deb are created by `dh_movefiles`, which is deprecated and should be replaced with `dh_install`. I'm working on this.
> 
> Nice! That also explains why I did not know about dh_movefiles :) From what I oversee, our pre-upload TODO list is then empty. If we have not inadvertently introduced an error, I will then upload. We can upload updates any time.

@SebKuzminsky  - I could give that transition to dh_install a shot, too. Ping me if you want me to continue on some branch of yours.

**Comment by smoe** [comment]
> > [Steffen Möller]
> > @SebKuzminsky - I could give that transition to dh_install a shot, too. Ping me if you want me to continue on some branch of yours.
> > I made a failed attempt at <URL: https://github.com/petterreinholdtsen/linuxcnc/tree/test-dh-install >, and ran out of time to fix it.
> 
> Looks good to me. I'll see what happens and send you a PR.

I am just doing it the very moment and it drove me crazy. This is "crazy enough to remove all *.instatl*  files, have debian/@MAIN_PACKAGE_NAME@ as a destdir and then move files/directory from there, i.e. all in debian/rules.in.

I tend to think that this simplifies everything a lot. If not, well, you will tell me.

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]

> These are the lintian error I get on my system:
> ```
> E: linuxcnc-uspace: library-not-linked-against-libc usr/lib/linuxcnc/modules/bldc.so
> E: linuxcnc-uspace: library-not-linked-against-libc usr/lib/linuxcnc/modules/lineardeltakins.so
> E: linuxcnc-uspace: library-not-linked-against-libc usr/lib/linuxcnc/modules/maxkins.so
> E: linuxcnc-uspace: library-not-linked-against-libc ... use --no-tag-display-limit to see all (or pipe to a file/program)
> ```
> I had a look at one of the modules with ldd and  don't get it:
> ```
> $ find . -name maxkins.so
> ./debian/linuxcnc-uspace/usr/lib/linuxcnc/modules/maxkins.so
> ./rtlib/maxkins.so
> $ ldd ./debian/linuxcnc-uspace/usr/lib/linuxcnc/modules/maxkins.so
>         linux-vdso.so.1 (0x00007ffc8b75b000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fadc4fbd000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fadc4df8000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007fadc512a000)
> ```
> The dependency on libc is clear, so what is the complaint about?
> @petterreinholdtsen - any idea?

No idea.  I had a look at it too, and could not figure out what the
issue was.

> Any low-hanging fruits please address. Otherwise I suggest to just ignore these for now.
> ```
> W: linuxcnc-uspace: appstream-metadata-missing-modalias-provide lib/udev/rules.d/99-xhc-whb04b-6.rules
> W: linuxcnc-uspace: appstream-metadata-missing-modalias-provide lib/udev/rules.d/99-xhc-whb04b-6.rules:2 match rule usb:v10CEpEB93d*
> W: linuxcnc-uspace: appstream-metadata-missing-modalias-provide lib/udev/rules.d/99-xhc.rules
> W: linuxcnc-uspace: appstream-metadata-missing-modalias-provide
> ... use --no-tag-display-limit to see all (or pipe to a file/program)

Already fixed.

> W: linuxcnc source: debian-rules-uses-unnecessary-dh-argument dh
> ... --parallel (line 25)

Ignore.

> W: linuxcnc-uspace: executable-not-elf-or-script
> usr/lib/tcltk/linuxcnc/linuxcnc.tcl

Drop execute bit on file?

> W: linuxcnc-uspace: groff-message usr/share/man/man1/iov2.1.gz (line 1) 188: warning: macro 'HTML' not defined

Sent pull request to drop .HTML.

> W: linuxcnc-uspace: groff-message usr/share/man/man9/toggle.9.gz (line 1) 17: can't open '../man/images/toggle.ps': No such file or directory
> W: linuxcnc-uspace: groff-message usr/share/man/man9/toggle2nist.9.gz (line 1) 26: can't open '../man/images/toggle2nist.ps': No such file or directory

Ignore until a decision for a different man page drawing is made.

> W: linuxcnc-uspace: lacks-unversioned-link-to-shared-library usr/lib/libpyplugin.so.0 usr/lib/libpyplugin.so
> W: linuxcnc source: missing-debian-source-format
> W: linuxcnc-uspace: no-manual-page usr/bin/linuxcnc-python
> W: linuxcnc-uspace: no-manual-page usr/bin/melfagui
> W: linuxcnc-uspace: no-manual-page usr/bin/millturngui
> W: linuxcnc-uspace: no-manual-page ... use --no-tag-display-limit to see all (or pipe to a file/program)

Ignore for now.

> W: linuxcnc-uspace: package-contains-python-dot-directory usr/lib/python3/dist-packages/qtvcp/designer/x86_64/qt5.11/
> W: linuxcnc-uspace: package-contains-python-dot-directory usr/lib/python3/dist-packages/qtvcp/designer/x86_64/qt5.11/libpyqt5_py2.so.tar.gz
> W: linuxcnc-uspace: package-contains-python-dot-directory usr/lib/python3/dist-packages/qtvcp/designer/x86_64/qt5.5/
> W: linuxcnc-uspace: package-contains-python-dot-directory ... use --no-tag-display-limit to see all (or pipe to a file/program)

Suspect these should be overrides.

> W: linuxcnc-uspace-dev: package-name-defined-in-config-h
> usr/include/linuxcnc/config.h

Proposed fix in test-dh-install branch.

> W: linuxcnc-uspace: shared-library-lacks-prerequisites usr/lib/linuxcnc/modules/at_pid.so
> W: linuxcnc-uspace: shared-library-lacks-prerequisites usr/lib/linuxcnc/modules/boss_plc.so
> W: linuxcnc-uspace: shared-library-lacks-prerequisites usr/lib/linuxcnc/modules/charge_pump.so
> W: linuxcnc-uspace: shared-library-lacks-prerequisites ... use --no-tag-display-limit to see all (or pipe to a file/program)
> W: linuxcnc-uspace-dev: unusual-interpreter /usr/bin/python3.9 [usr/bin/halcompile]
> W: linuxcnc source: upstream-metadata-in-native-source

Ignore for now.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Perhaps drop the TODO file and only include the other changes?

**Comment by smoe** [comment]
Rebased and remoted TODO as suggested.

**Comment by SebKuzminsky** [comment]
@smoe this looks great to me, is it ready to merge in your opinion?

**Pull request merged**
