### PR TITLE
Gmoccapy - czech translate

### PR DESCRIPTION
**Pull request by zz912**
I made a translation for Gmoccapy. This is not a literal translation, but a translation that is user friendly. Contains many untranslated phrases.  I am of the opinion that the original text is better than a bad translation.

### CODE REVIEW

**Comment by hansu** [comment]
>I am of the opinion that the original text is better than a bad translation.

I totally agree. 

@petterreinholdtsen, @silopolis Is the following the correct order for adding this new language to Weblate? 

1. Accept this PR
2. Merge 2.8 to master
3. Create a new language on Weblate

Or should the new language created first on Weblate?

**Comment by petterreinholdtsen** [comment]
[Hans]
> @petterreinholdtsen, @silopolis Is the following the correct order for
> adding this new language to Weblate?
>
> 1. Accept this PR
> 2. Merge 2.8 to master
> 3. Create a new language on Weblate
>
> Or should the new language created first on Weblate?

As long as the language is not yet on Weblate, you only need to accept
the PO file into master (via 2.8 if you want), and then pull the new PO
file into Weblate using the 'pull' option.

If the language is already listed on Weblate, this will cause a merge
conflict and the translator should put his texts directly into Weblate
after setting up the new language there.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by zz912** [comment]
If this cs.po file is also added to the main branch, will it be possible to change it directly? I don't know how Weblate works, I'm fine with Poedit, but I don't want to create any problems in the future if I change the cs.po file directly without solving anything with weblate.

**Comment by hansu** [comment]
Thanks Petter!

>If this cs.po file is also added to the main branch, will it be possible to change it directly? I don't know how Weblate works, I'm fine with Poedit, but I don't want to create any problems in the future if I change the cs.po file directly without solving anything with weblate.

If you plan to extend/improve this po file for 2.8 in the next time, we should better postpone this PR.
Once it is in master (and likely in Weblate), direct changes to this file would cause merge conflicts.

When it's in Weblate, it should be only edited there. And getting these changes back to 2.8 would probably cause conflicts as well.

**Comment by petterreinholdtsen** [comment]
[zz912]
> If this cs.po file is also added to the main branch, will it be
> possible to change it directly? I don't know how Weblate works, I'm
> fine with Poedit, but I don't want to create any problems in the
> future if I change the cs.po file directly without solving anything
> with weblate.

Modifying it directly in git after the initial commit will cause
problems in the future.  Modifications both places will cause git
conflicts.  And we get 'drive by translations' on Weblate, random people
showing up to help with the translations unannounced.  The number of
translators have increased 40% since last month already.  This tell me
that it is likely that someone will update the translation on Weblate
too.  I strongly suggest you checkout Weblate as a translation option,
to avoid git conflicts.

-- 
Happy hacking
Peter Reinholdtsen

**Comment by zz912** [comment]
I studied many videos in Youtube aboat git an Github and I am not sure about right working.
I understood that cs.po in 2.8 can be modified directly and then I should make Pull request.
I understood that cs.po in 2.9 must be modified by weblate.

I dont understand:
> And getting these changes back to 2.8 would probably cause conflicts as well.

Exist some automatic proces for merging from master branche to 2.8 branche?
Or did you write this sentence just in case someone thought of it?

I'm not against weblate, but my main goal was to translate for version 2.8

**Comment by zz912** [comment]
Is there any way to split cs.po for version 2.8 and for master version?

**Comment by petterreinholdtsen** [comment]
[zz912]
> Is there any way to split cs.po for version 2.8 and for master
> version?

Are you volunteering to get deep into git, LinuxCNC and Weblate and
maintain cs.po in LinuxCNC using a special system only for this file?  I
am sure there are ways to special case it, but I doubt anyone else will
be volunteering to maintain such system.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by zz912** [comment]
> The only possibility I see is to commit the changes of cs.po to 2.8 and then merge 2.8 immediately to master and select the changes from master on conflicts, so that the file doesn't change on master. But this is a bit risky if someone else does the merge and don't know about this.

I don't want to do anything risky.

I discussed this problem with a Czech-speaking programmer over the phone. The solution could be something like this:

Let's do everything as HansU suggested first. As soon as I make another Pull request for cs.po for the 2.8 branch, I will put in the message:

`Warning: Do not merge with master branch. There may be a conflict with weblate.`

Do you think this is a clean solution?

Currently, HansU has done some bug fixing that affects the cs.po file. Therefore, I would like to ask you to hold this Pull Request until I process all the information that HansU sent me on the forum.

**Comment by hansu** [comment]
If you want to hold back this PR, you can click "Convert to draft" in the upper right corner in the "Reviewers" section, then everybody knows that there is work in progress.

>Let's do everything as HansU suggested first. As soon as I make another Pull request for cs.po for the 2.8 branch, I will put in the message:
>
>`Warning: Do not merge with master branch. There may be a conflict with weblate.`

Better: "Warning: After merging this PR, please merge the 2.8 branch immediately into master and make sure the changes from this file don't go into master"
But I wouldn't call it "clean" :wink: 

Because with your message you cannot prevent that the merge will be done at some time later.

**Comment by smoe** [comment]
Hm. First off: I am very happy for CZ translations - welcome!!! Just, how to get there. I am somewhat confident that all translation work should be done via weblate. And since these strings change in the English all the time, we would have conflicts between 2.8 and 2.9 all the time. Since 2.9 should surface somewhen in the not too far future, I suggest to not touch 2.8 for CZ at all and focus with all your might on 2.9 and getting that out of the door.

**Comment by zz912** [comment]
Hello,

I made last change for translate Gmoccapy for LCNC 2.8. I would like ask you only for merge to Branche 2.8 . I am not sure If I will have enough time for version 2.9 with Weblate. So I don't want to oblige anyone else. 

I made query in forum https://forum.linuxcnc.org/37-international-linuxcnc-users/46703-split-po-files-weblate-manual
about working with Webalte without answer.

**Comment by hansu** [comment]
Nice, I'll merge it later.
Then I will merge 2.8 up to master, and the language will show up on Weblate. Then only the strings have to be checked/translated which changed from 2.8 to 2.9 😉 

>I made query in forum https://forum.linuxcnc.org/37-international-linuxcnc-users/46703-split-po-files-weblate-manual
about working with Weblate without answer.

I answered 😉

**Comment by hansu** [comment]
>@[zz912](https://github.com/zz912) zz912 marked this pull request as draft 2 days ago
@[zz912](https://github.com/zz912) zz912 marked this pull request as ready for review 2 days ago

So ready for merge?

**Comment by zz912** [comment]
Yes, this was my mistake. I uploaded two same files. Now it is correct.

**Comment by hansu** [comment]
The Czech translation is now on Weblate :tada: 
Still at 85%, so 15% of the strings have changed (if it was at 100% before)

https://hosted.weblate.org/projects/linuxcnc/gmocappy/

**Pull request merged**
