### PR TITLE
Add Part Bounding box on Gcode Graphics

### PR DESCRIPTION
**Pull request by satiowadahc**
Replacing #2887, now rebased on master.

### CODE REVIEW

**Comment by satiowadahc** [comment]
Set a default max file size, check with INI for updated value, then add getter/setters?

**Comment by c-morley** [comment]
I'd think just a function to set it would be fine. A GUI then could set it if it's required, I suspect it won't happen often.
What do you think?

**Comment by andypugh** [comment]
I have assigned this to @c-morley to decide whether to merge or not. I don't know enough to decide.

**Comment by c-morley** [comment]
Thank you.

**Pull request merged**
