### PR TITLE
Improved Modbus to Hal docs + man page

### PR DESCRIPTION
**Pull request by hansu**
1. i created a "real" doc  page for MB2HAL instead of only the copy of the Howto.ini: https://hansu.github.io/linuxcnc-doc/drivers/mb2hal.html

2. And also added the Pins to the man page: https://hansu.github.io/linuxcnc-doc/man/man1/mb2hal.1.html
  To keep it short, i didn't write the pin names that are the same for two function codes, like this:

   ```
   fnct_01_read_coils:
   fnct_02_read_discrete_inputs:
       mb2hal.m.n.bit bit out
       mb2hal.m.n.bit-inv bit out
   ```
   Do you think this is clear? In the bash it looks okay, but in the HTML version are is more space between them, that might  be irritating...

### CODE REVIEW

**Comment by silopolis** [comment]
Le sam. 26 févr. 2022 à 16:09, Hans ***@***.***> a écrit :

>
>    1.
>
>    i created a "real" doc page for MB2HAL instead of only the copy of the
>    Howto.ini: https://hansu.github.io/linuxcnc-doc/drivers/mb2hal.html
>    2.
>
>    And also added the Pins to the man page:
>    https://hansu.github.io/linuxcnc-doc/man/man1/mb2hal.1.html
>
>
Maybe these would better be written in AsciiDoc format?



>    1.
>
>
>

**Comment by hansu** [comment]
>Maybe these would better be written in AsciiDoc format?

What exactly do you mean? The doc page (including the pins as well) is obviously written in AsciiDoc...

**Comment by silopolis** [comment]
Hi,

Le dim. 27 févr. 2022 à 19:09, Hans ***@***.***> a écrit :

> Maybe these would better be written in AsciiDoc format?
>
> What exactly do you mean? The doc page (including the pins as well) is
> obviously written in AsciiDoc...
>

Sorry, didn't look at the PR and, as your message mentioned the html files,
this has not been that obvious to me...

**Comment by hansu** [comment]
> Hi, Le dim. 27 févr. 2022 à 19:09, Hans ***@***.***> a écrit :
> Maybe these would better be written in AsciiDoc format? What exactly do you mean? The doc page (including the pins as well) is obviously written in AsciiDoc...
> Sorry, didn't look at the PR and, as your message mentioned the html files, this has not been that obvious to me...

No worries. I just linked to the "readable" output of the AsciiDoc :)
But what do you thing about the primary question now?

**Pull request merged**
