### PR TITLE
docs: small fixes to Master_* files

### PR DESCRIPTION
**Pull request by silopolis**
@hansu could you please merge this before we finish syncing translations ?

Thanks and have a nice day

TY
J

### CODE REVIEW

**Comment by hansu** [comment]
This should still go in master?

**Comment by silopolis** [comment]
Le mar. 12 avr. 2022 à 23:22, Hans ***@***.***> a écrit :

> This should still go in master?
>
Would actually be better merged into docs-devel

**Comment by hansu** [comment]
Ok, is changed But you know that you can change this too?

**Comment by silopolis** [comment]
Le mer. 13 avr. 2022 à 08:05, Hans ***@***.***> a écrit :

> Ok, is changed But you know that you can change this too?
>
I'll handle it. Either rebasing or cherry picking my commits in a new
branch.

**Comment by hansu** [comment]
No need to rebase here.

**Comment by hansu** [comment]
I mean you can if you want a more straight forward history. But with
>Ok, is changed But you know that you can change this too?

I meant the changing of the destination branch of the PR.

**Comment by silopolis** [comment]
Le mer. 13 avr. 2022 à 09:45, Hans ***@***.***> a écrit :

> I mean you can if you want a more straight forward history. But with
>
> Ok, is changed But you know that you can change this too?
>
> I meant the changing of the destination branch of the PR.
>
Now that you say it... ☺️

>

**Comment by hansu** [comment]
Small fixes with big impact: https://github.com/LinuxCNC/linuxcnc/actions/runs/2162539086 :smile:

Probably your idea to rebase it would have avoided it :innocent: 

`po4a.cfg:85: The master file 'src/gui/GStat.adoc' does not exist.`

**Comment by hansu** [comment]
Fix provided in https://github.com/LinuxCNC/linuxcnc/pull/1712

**Pull request merged**
