### PR TITLE
Allow to use float for QSlider

### LINKED ISSUE #1481: qtplasma does not work on qt5 version >=5.15.6
I was trying to run qtplasma on Fedora 35 where we have by default python `3.10` and python3-qt5 `5.15.6`, however it does not work at all. 

Despite I fixed a few simple issues:
 - https://github.com/LinuxCNC/linuxcnc/pull/1478
 - https://github.com/LinuxCNC/linuxcnc/pull/1479
 - https://github.com/LinuxCNC/linuxcnc/pull/1480
 - https://github.com/LinuxCNC/linuxcnc/pull/1482
 - https://github.com/LinuxCNC/linuxcnc/pull/1484

it still crashes for setting QSlider with 'float' argument while 'int' is expected.

Here is the example:
```Traceback (most recent call last):
  File "/home/dw/projects/linuxcnc/bin/qtvcp", line 487, in <module>
    APP = QTVCP()
  File "/home/dw/projects/linuxcnc/bin/qtvcp", line 290, in __init__
    window.handler_instance.initialized__()
  File "/home/dw/projects/linuxcnc/share/qtvcp/screens/qtplasmac_4x3/qtplasmac_4x3_handler.py", line 294, in initialized__
    self.init_widgets()
  File "/home/dw/projects/linuxcnc/share/qtvcp/screens/qtplasmac_4x3/qtplasmac_4x3_handler.py", line 775, in init_widgets
    self.w.jog_slider.setMaximum(INFO.MAX_LINEAR_JOG_VEL)
TypeError: setMaximum(self, int): argument 1 has unexpected type 'float'
```

This is applicable to at least: 
- MIN_LINEAR_JOG_VEL
- MAX_LINEAR_JOG_VEL
- DEFAULT_ANGULAR_JOG_VEL

which all uses 'float' to set value to [QSlider()](https://doc.qt.io/qt-5/qabstractslider.html#value-prop).

### PR DESCRIPTION
**Pull request by dwrobel**
Fixes #1481

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

### CODE REVIEW

**Comment by dwrobel** [comment]
This change allowed me to run `qtplasma` with python `3.10` and python3-qt5 `5.15.6` on X11. `qtplasma` still does not work natively on Wayland, but that seems to be a separate issue.

**Comment by phillc54** [comment]
QtPlasmaC works fine on Debian 11 with Wayland. You may need to run the install script in the repo to install the required Qt dependencies.
lib/python/qtvcp/designer/install_script

**Comment by dwrobel** [comment]
I don't observe any runtime dependencies issues. I cannot run the script for Debian on Fedora, however I've double checked and all minimal requirements are satisfied:

| Debian | Fedora |
| --------- | ----------- |
| python3-opengl | python3-pyopengl-3.1.5-7.fc35.x86_64 |
| python3-opencv | python3-opencv-4.5.3-6.fc35.x86_64 |
| python3-pyqt5 | python3-qt5-5.15.6-1.fc35.x86_64 |
| python3-pyqt5.qsci | python3-qscintilla-qt5-2.13.0-1.fc35.x86_64 |
| python3-pyqt5.qtsvg | qt5-qtsvg-5.15.2-5.fc35.x86_64 |
| python3-pyqt5.qtopengl | python3-qt5-base-5.15.0-13.fc35.x86_64 (despite the name is different it contains all the files listed here https://packages.debian.org/sid/amd64/python3-pyqt5.qtopengl/filelist) |

BTW the list of dependencies doesn't list `xset` utility (used [here](https://github.com/LinuxCNC/linuxcnc/blob/8d8355e104417b044acc9ad016eb191d122a4a70/lib/python/qtvcp/qt_action.py#L692) and [here](https://github.com/LinuxCNC/linuxcnc/blob/8d8355e104417b044acc9ad016eb191d122a4a70/lib/python/qtvcp/qt_action.py#L696)) which, on Fedora, was not installed by default _(Debian can stop installing it at anytime)_ and using it on Wayland wouldn't have any effect. I'll open a separate issue for tracking `qtplasma` issues on Wayland.

**Comment by c-morley** [comment]
Ends up this isn't the right fix. the code in qtplasmac's handler file is unnecessary.
This fix broke other things.
I'm going to revert it and fix the other code.
After that if there is still problems please open an issue.

**Pull request merged**
