### PR TITLE
docs_misc_mac_4

### PR DESCRIPTION
**Pull request by smoe**

### CODE REVIEW

**Comment by smoe** [comment]
@hansu - moved this to 2.9 without creating a new PR - was a reset, stash, checkout of 2.9, local branch removal, check into new branch with same name branching off 2.9, stash pop, push --force.

**Comment by hansu** [comment]
conflicts ... :/

**Comment by smoe** [comment]
> conflicts ... :/

Done?

**Comment by hansu** [comment]
What, only one change left over?

**Comment by smoe** [comment]
Looks a bit minimalistic, indeed :) But so be it. No time to investigate.

**Pull request merged**
