### PR TITLE
2.7:  limit3--fix acceleration

### LINKED ISSUE #378: limit3 constraint violation
We've discovered two glitches in @zultron's new limit3 component.  A new test added in 3eb0a7a1b247aa34bb80549c7b045b56ba1007c6 reproduces both.

The first glitch is when limit3's input abruptly begins to track its output.  This bug was fixed in a0fb2781268ac1c5eec049bf7ea6b4fa2ebf84c3.

The second glitch is an accel constraint violation that seems related to hunting for a constant-velocity input.
limit3-accel-violation

### PR DESCRIPTION
**Pull request by zultron**
These patches address the shortcomings of PR #380, and fix #378, reporting constraint violations in the `limit3` comp.  Take a look at the top commit log for the specifics of what's going on here.

### CODE REVIEW

**Comment by zultron** [comment]
This should now pass all of @SebKuzminsky's tests, including the super-strict "sluggishness" checks.  Thanks for writing those!

@samcoinc said he'd do some testing on this.  My fingers are crossed it all goes well.  Thanks, Sam!

I ended up rewriting this about four times before finally getting here, and as I told @samcoinc, I almost gave up on it three times.   Oh, man.

**Comment by zultron** [comment]
@samcoinc told me about @dngarrett's project to use this code elsewhere, and the need to avoid backing off.  The `smooth-steps` pin can be set to a high value to smooth out acceleration.  Here are some screenshots to show what this does.

A clipped triangle signal from the `limit3/lock-on-input-and-limits` test.
Default (2):
screenshot_2018-01-11_20-48-29-limit3-triangle-smooth-steps-2
`setp limit3.0.smooth-steps 10000`:
screenshot_2018-01-11_20-48-29-limit3-triangle-smooth-steps-10k

A clipped sine signal from the `limit3/min-max-overshoot` test.
Default:
screenshot_2018-01-11_20-48-29-limit3-sine-smooth-steps-2
`setp limit3.0.smooth-steps 10000`:
screenshot_2018-01-11_20-48-29-limit3-sine-smooth-steps-10k

Notice how the higher value cleans up the up and down acceleration spikes and smooths out the curve.

**Comment by SebKuzminsky** [comment]
This looks amazing @zultron !

**Comment by zultron** [comment]
Thanks, @SebKuzminsky!

**Pull request merged**
