### PR TITLE
Gmoccapy: update German translation for 2.9

### PR DESCRIPTION
**Pull request by hansu**
I would like to update the German translations in 2.9.
My plan is to 
1. merge 2.9 into master
2. merge this PR
3. merge 2.9 into master with `-s ours`

This shouldn't cause any merge conflicts in future in master with Weblate, right? @petterreinholdtsen

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I fail to see any update of the 2.9 branch in your recipe.  As far as I know, the merge forward process used by LinuxCNC will cause conflicts if PO files are updated in 2.9 and then merged into master.

**Comment by hansu** [comment]
> I fail to see any update of the 2.9 branch in your recipe.

Done with "2. merge this PR" (into 2.9)

> As far as I know, the merge forward process used by LinuxCNC will cause conflicts if PO files are updated in 2.9 and then merged into master.

Of course it will cause conflicts, therefore the plan is to resolve them with `merge  -s ours 2.9`

**Comment by petterreinholdtsen** [comment]
I do not know the inner workings of git enough to understand how this
will affect the work flow of the merge forward approach used by
linuxcnc.  Personaly, I would not dare doing what you propose, as I do
not know the consequences.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
But why should there appear any merge conflict when merging Weblate's pull request when nothing has changed in master?

**Comment by petterreinholdtsen** [comment]
[Hans Unzner]
> But why should there appear any merge conflict when merging Weblate's
> pull request when nothing has changed in master?

I do not know git enough to know the answer to this one.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request merged**
