### PR TITLE
Document how to run and write tests.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
[Hans Unzner]
> I guess this is meant as a draft and adding it to the TOC etc. you
> have in mind? Otherwise nobody would find it :)

Yes.  I would like to get feeback on what more information is needed and
if there is something incorrect in the text so far.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
I could not make changes or comments to the PR. What I am missing are a series of examples that explain how to test for a HAL component or for some C++ code, and that show how to deal with various forms or input or signal changes. That could become one of the most important parts of the documentation, I guess :)

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> I could not make changes or comments to the PR. What I am missing are
> a series of examples that explain how to test for a HAL component or
> for some C++ code, and that show how to deal with various forms or
> input or signal changes. That could become one of the most important
> parts of the documentation, I guess :)

While it sound like nice ideas, it is hard to generalize to simple
recipes.  I guess we can try to provide some examples, but am unsure how
to write it.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
Nice description, but I was missing some essential points to get started. I took the freedom and put a commit on top of yours to keep it simple. Feel free to remove or correct it.

**Comment by petterreinholdtsen** [comment]
[Hans Unzner]
> Nice description, but I was missing some essential points to get
> started. I took the freedom and put a commit on top of yours to keep
> it simple. Feel free to remove or correct it.

Thank you.  I'll keep adding text to it for a while more. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
I extended with a few examples.  It this now understandable?  I suggest
this edition is merged and those that know more provide patches to
extend it.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
[Petter]
>I extended with a few examples.  It this now understandable?  I suggest
this edition is merged and those that know more provide patches to
extend it.

Yeah I think so :+1:. I am fine with merging this.

**Comment by petterreinholdtsen** [comment]
[Hans Unzner]
> Yeah I think so :+1:. I am fine with merging this.

Very good.  I have rebased and squashed it into one commit, and believe
it is ready to go.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request merged**
