### PR TITLE
axis: allow pyvcp panel at bottom of windows

### PR DESCRIPTION
**Pull request by phillc54**
Allows a PyVCP panel to be at the bottom of the AXIS user interface as an alternative to being at the right side.

### CODE REVIEW

**Comment by c-morley** [comment]
Any reason not to add this to 2.8?

**Comment by phillc54** [comment]
Not that I can think of, it shouldn't break any existing configs.

**Comment by andypugh** [comment]
So, do we merge this request? Or do you want it in 2.8?

**Comment by c-morley** [comment]
I'll cherry-pick later for 2.8

**Pull request merged**
