### PR TITLE
Pncconf: fix all-limit-home config settings

### PR DESCRIPTION
**Pull request by phillc54**
There are multiple commits in this PR:
- 89dc998 - fix all-limit-home config settings
- 1f9eb27 - fix dual mesa card config settings
- 8ae92cd - add a 7i80db and a 7i90hd firmware
- b9a2e379 - rename 7i80 hal name

There is an issue with a couple of print statements in build.INI.py if these get merged to master:
commit 1f9eb27:
`            print >>file, "CARD1=hm2_%s.%d"% (self.d.mesa1_currentfirmwaredata[_PD._BOARDNAME], halnum)`
commit 89dc998:
`                    print >>file, "HOME_IS_SHARED = 1"`
both need converting for the `from __future__ import print_function` function. I am not sure of the correct procedure for this.

Edit: I have created a branch based on master with the four commits in it.
https://github.com/phillc54/linuxcnc/tree/phillc54/pncconf-master

### CODE REVIEW

**Comment by gmoccapy** [comment]
Print is a function, not a command in py3, so command need to be likeprint("HOME_IS_SHARED = 1", fileobject) Norbert -------- Ursprüngliche Nachricht --------Von: Phillip Carter ***@***.***>Datum: So., 4. Juli 2021, 06:45An: LinuxCNC/linuxcnc ***@***.***>Cc: Subscribed ***@***.***>Betreff: [LinuxCNC/linuxcnc] Pncconf: fix all-limit-home config settings (#1202)There are multiple commits in this PR:
89dc998 - fix all-limit-home config settings1f9eb27 - fix dual mesa card config settings8ae92cd - add a 7i80db and a 7i90hd firmwareb9a2e37 - rename 7i80 hal name
There is an issue with a couple of print statements in build.INI.py if these get merged to master:
commit 1f9eb27:
            print >>file, "CARD1=hm2_%s.%d"% (self.d.mesa1_currentfirmwaredata[_PD._BOARDNAME], halnum)
commit 89dc998:
                    print >>file, "HOME_IS_SHARED = 1"
both need converting for the from __future__ import print_function function. I am not sure of the correct procedure for this.



You can view, comment on, or merge this pull request online at:
  https://github.com/LinuxCNC/linuxcnc/pull/1202

Commit Summary
pncconf: fix all-limit-home config settingspncconf: fix dual mesa card config settingspncconf: add a 7i80db and a 7i90hd firmwarepncconf: rename 7i80 hal name

File Changes

    M
    src/emc/usr_intf/pncconf/build_INI.py
    (16)
  
    M
    src/emc/usr_intf/pncconf/pncconf.py
    (95)
  
    M
    src/emc/usr_intf/pncconf/private_data.py
    (100)
  

Patch Links:
https://github.com/LinuxCNC/linuxcnc/pull/1202.patchhttps://github.com/LinuxCNC/linuxcnc/pull/1202.diff

**Comment by phillc54** [comment]
I understand what needs to be changed in the files, I already have the code in my other branch. I am not sure how to achieve the change, do I need to submit a separate PR for master branch or do I fix master branch after 2.8 is merged into it next.

**Comment by andypugh** [comment]
Without github involved, then the process would be to make the change in 2.8, then merge up to master, and then fix the issue. 
So, I think the way here is to make a PR for 2.8, then merge locally in to master, fix the problems, then make another PR that includes the merge. 
I think that git is clever enough to notice if the same commit is being applied twice, and just ignore it, so I don't think we need to worry about timing the two commits.

**Comment by phillc54** [comment]
Thanks Andy, this PR is good for 2.8 so I will do the next two steps tomorrow.

**Comment by phillc54** [comment]
remove this PR and submit separate PRs for 2.8 and master

**Pull request closed without merging**
