### PR TITLE
Fix `merge -s ours`

### PR DESCRIPTION
**Pull request by SebKuzminsky**
This is my attempt at a partial fix for the recent mistaken `git merge -s ours` (1d836df8).

This PR cherry-picks most of the commits from 2.9 between the most recent good merge (d788b67f) and the new, bad merge (1d836df8).  I used `git cherry-pick -x` so that the new commit message includes the SHA of the original commit from 2.9, to help future archaeologists.

Some of the 2.9 commits were already in master (thanks to Chris's 624647fb and Dewey's 3d3bdb72).

I had problems with nearly all the commits that touch the docs: 1c6e3cb5, 245ea867, f2b9835e, ec02e63f, 9d57d998, 28878842, 3df87ab3, 0da277b2, f9d19a4d, 802f497f, 1dfa6e42, 59d94f66, f52eaf62, 2cd49cc3, 2cc3cffd, a9472ef6, a4c68b0d, e404459a.

I skipped those, and would like someone who knows the docs better to handle them.

I also didn't deal with the pncconf conflict in 4de6a4da - it *looked* like a different patch was already in master; Chris, can you take a look at these?

### CODE REVIEW

**Comment by c-morley** [comment]
When I finished my 'repair' yesterday pncconf had no comflicts. (I merged 2.9 to master afterwards.)
Now I'm right back to the same position pncconf is in conflict. :(

How can I break this cycle? AFAICT all code was fixed after I cherry picked and recommitted - what was still broken ?

I can fix my work, even if it means recommitting it.

Also what should be our policy if something like this happens again?

Thank you.

Chris
________________________________
From: Sebastian Kuzminsky ***@***.***>
Sent: January 7, 2023 4:55 PM
To: LinuxCNC/linuxcnc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LinuxCNC/linuxcnc] Fix `merge -s ours` (PR #2250)


This is my attempt at a partial fix for the recent mistaken git merge -s ours (1d836df<https://github.com/LinuxCNC/linuxcnc/commit/1d836df8e191b5083e1742f8f7ff10d12a746991>).

This PR cherry-picks most of the commits from 2.9 between the most recent good merge (d788b67<https://github.com/LinuxCNC/linuxcnc/commit/d788b67f98c241c2b8e624522ecb161b21f296d8>) and the new, bad merge (1d836df<https://github.com/LinuxCNC/linuxcnc/commit/1d836df8e191b5083e1742f8f7ff10d12a746991>). I used git cherry-pick -x so that the new commit message includes the SHA of the original commit from 2.9, to help future archaeologists.

Some of the 2.9 commits were already in master (thanks to Chris's 624647f<https://github.com/LinuxCNC/linuxcnc/commit/624647fb6cd5130955d238084e757975e0368fa5> and Dewey's 3d3bdb7<https://github.com/LinuxCNC/linuxcnc/commit/3d3bdb726a0d76e73b71a971beb619b15b72123c>).

I had problems with nearly all the commits that touch the docs: 1c6e3cb<https://github.com/LinuxCNC/linuxcnc/commit/1c6e3cb5a2a0be6c1b050f4408e3915366ca191a>, 245ea86<https://github.com/LinuxCNC/linuxcnc/commit/245ea8675115be1ec51552be350de22be5ad45b4>, f2b9835<https://github.com/LinuxCNC/linuxcnc/commit/f2b9835ebd0e5884960de1303fa1d99ed7c5c24e>, ec02e63<https://github.com/LinuxCNC/linuxcnc/commit/ec02e63f4ff8457b805c95b697dfb167500254dc>, 9d57d99<https://github.com/LinuxCNC/linuxcnc/commit/9d57d9984bd3cc228cd589eb71e369565f815c3f>, 2887884<https://github.com/LinuxCNC/linuxcnc/commit/28878842893e89b9b5c6bbd11255c712e040cb63>, 3df87ab<https://github.com/LinuxCNC/linuxcnc/commit/3df87ab3f66935273823eb9e2f11babfb3e50501>, 0da277b<https://github.com/LinuxCNC/linuxcnc/commit/0da277b279d020dea82c9f25b99403705c6f589a>, f9d19a4<https://github.com/LinuxCNC/linuxcnc/commit/f9d19a4dac01e7f23941323e71f27c420f143e0a>, 802f497<https://github.com/LinuxCNC/linuxcnc/commit/802f497f198aacd7e439d167a618dadd0456d600>, 1dfa6e4<https://github.com/LinuxCNC/linuxcnc/commit/1dfa6e42c126b1e391b31470b8bba7565c3a02dd>, 59d94f6<https://github.com/LinuxCNC/linuxcnc/commit/59d94f6657ae89029066660539941563227593c3>, f52eaf6<https://github.com/LinuxCNC/linuxcnc/commit/f52eaf62e69779e3cdc6d659df6c9fe4fc193fef>, 2cd49cc<https://github.com/LinuxCNC/linuxcnc/commit/2cd49cc3ccf6966bfb51175e53264c05cd20da28>, 2cc3cff<https://github.com/LinuxCNC/linuxcnc/commit/2cc3cffd907ab93d611d6c48184e85040ae626ff>, a9472ef<https://github.com/LinuxCNC/linuxcnc/commit/a9472ef616c07d9b9e5971b4eddf0206c0e14502>, a4c68b0<https://github.com/LinuxCNC/linuxcnc/commit/a4c68b0d2143588d0de3a177589bef164e3f26fa>, e404459<https://github.com/LinuxCNC/linuxcnc/commit/e404459a6068f53b2056abe73c35f5dcffedcc40>.

I skipped those, and would like someone who knows the docs better to handle them.

I also didn't deal with the pncconf conflict in 4de6a4d<https://github.com/LinuxCNC/linuxcnc/commit/4de6a4da071e789933b62a942e99d1cf9ca1f8f3> - it looked like a different patch was already in master; Chris, can you take a look at these?

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/LinuxCNC/linuxcnc/pull/2250

Commit Summary

  *   9d15462<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/9d15462e14a54d3c89ee40cfba81da52a7e1d390> Fix typo in changelog to quieten Lintian.
  *   c991ed7<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/c991ed77b35495ad57cadeb02e1b180003f037ed> qtdragon/hd -fix deciaml entry on non english locale
  *   1fc33e0<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/1fc33e0f3c9917b3c9f894a596fa17cadbcf813e> docs: misc changes while translating
  *   e27cc37<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/e27cc37ae5389642bdf51ec3f019f5c44a4f5ce7> Update docs/src/gui/gmoccapy.adoc
  *   e9c64ac<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/e9c64ac74c9f4d089a2f684096a7b3052ea2b477> Introduced monospace as requested, more semantic line breaks
  *   22be8b1<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/22be8b1dc770a03f592ab2e2df65c5bcc48ead95> gmoccapy: gmoccapy: adapt button size of side buttons
  *   2a01a12<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/2a01a126c85779fddbc3c3b6be0438b5c933cca3> gmoccapy: change label name & center of "delete MDI" button
  *   5560ffd<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/5560ffda964925e79e018984af231bbc25939dff> gmoccapy: added ability to source a rcfile
  *   099e36b<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/099e36b76ec9ff24f5bbbfe281ed9c2fc7106d32> gmoccapy: add option to use a CSS file
  *   ead878a<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/ead878ad24a087d5ead853aa589700f446b8181e> gmoccapy: left align text in notification messages
  *   bd5bbc5<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/bd5bbc5052ea9ee3737599480899a35dc4510220> gmoccapy_3_4_1: update release notes
  *   3f9aa86<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/3f9aa8618a72a997e04a5de1897599b24d848861> docs: add docs for gmoccapy user command/css file
  *   1f1ccc2<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/1f1ccc2650f9486dcbcdc115bbfa23e039b14f73> docs: more translation-motivated changes
  *   3cbd25b<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/3cbd25b2ef3247709dffc2fbd5fc869dac99b6d7> docs: More smallish translation-triggered changes
  *   a68dc87<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/a68dc877d0f5febc7969acbfe4b391893f27079e> qtvcp -pstat: fix vismach path for installed versions of linuxcnc
  *   cbb020e<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/cbb020e27fe61d9b750230be16b7175c12d99d15> qtdragon/hd: fix input validation code.
  *   ae69322<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/ae69322bf60d2cac20732478500f7af76989b542> qtvcp -camview: fix error when opeb vc library is missing
  *   d6d6cda<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/d6d6cda1dbd064f86d43ff2761c5cb8a927f0410> qtvcp -round_guage: fix errors with new libraries
  *   30900a3<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/30900a3517feac7d26c3851396997664353e59b6> qtvcp -round_prpgress: fix error with new libraries
  *   723807d<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/723807d713de4819b4addeb906bfafd994b3d8f8> glnav.py:GlNavBase:set_viewangle() add forcerotate
  *   6ce184c<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/6ce184c112fa7ebc238f8604558d6b874e0f4f08> rcs_sem_open(): prettier error reporting
  *   0a3a45b<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/0a3a45b858d786c6290a497224d4853bdfd905f9> WIP: uspace rtapi_app: more informative error message
  *   6195228<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/6195228e191cb382c75c0d44ef8490e5f4717959> docs: start updating Updating LinuxCNC for 2.9.0
  *   72624bf<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/72624bf2d488246cf595428d29d93f0b30dcb8ad> document some more methods and variables in `linuxcnc` python module
  *   62b995e<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/62b995ee5b7fa9993ed2369a2c2b75bd988b9736> task: handle pluggable interpreters better
  *   499af6a<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/499af6a135eca43f9b66f72c8dfaef59a418c369> Updating LinuxCNC doc: add info about stricter [TASK]INTERPRETER
  *   a966798<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/a966798ca5e5e29bc390104a5331b7a02e4f7904> clean up handling of canterp
  *   cf98f3c<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/cf98f3cf188e748fb5e1acbf0b555a8265c11c30> Updating LinuxCNC doc: renamed canterp
  *   d589614<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/d5896142cebef10199720aafe4dd94d73983709d> fixup `make install`, don't grab files from subdirectories of ../lib
  *   8046dba<https://github.com/LinuxCNC/linuxcnc/pull/2250/commits/8046dbaf730a9c76bec3c5d8236120c35fe7abf8> new sample config 5axis xyzab_tdr using kins comp

File Changes

(56 files<https://github.com/LinuxCNC/linuxcnc/pull/2250/files>)

  *   M configs/sim/axis/canterp.ini<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-b5221e576cf0c27624d923767a9dddfce6b25bbdc5d214748cc14ec8ea047cfb> (2)
  *   A configs/sim/axis/vismach/5axis/table-dual-rotary/README<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-bb14a4f01187e564d698fdf3ba011c3970d12454da5651b0099de350fb9d8592> (42)
  *   A configs/sim/axis/vismach/5axis/table-dual-rotary/demos/xyzab-tdr-demo.ngc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-eeba234df8cf51b79298a3c9abeba47447762553707807a48fb620fc3d098f22> (49)
  *   A configs/sim/axis/vismach/5axis/table-dual-rotary/remap_subs/428remap.ngc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-007e548ee1ebe3dbfc1947387e307cab5550c04793153bd2e5f464c818cdb014> (24)
  *   A configs/sim/axis/vismach/5axis/table-dual-rotary/remap_subs/429remap.ngc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-651d19e561404673210316b784fb1be1c58b5b985b0f5fdc2a0c0266aa57ca3e> (24)
  *   A configs/sim/axis/vismach/5axis/table-dual-rotary/xyzab-tdr-postgui.hal<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-e1a9ff6a42691c88b9ccab0e7269304950ee325187b859bd19f5c73edcc6281a> (23)
  *   A configs/sim/axis/vismach/5axis/table-dual-rotary/xyzab-tdr.ini<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-a3d9684e6f6faffa590aa39cf912f94a3a3c1b2910e41953607d211653f96bbb> (185)
  *   A configs/sim/axis/vismach/5axis/table-dual-rotary/xyzab-tdr.tbl<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-74038166931eb99e04c1c0800785e1030573117f539e79433199347be4ba15ba> (4)
  *   A configs/sim/axis/vismach/5axis/table-dual-rotary/xyzab-tdr.xml<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-8f1d911ff7ba6c7d812a5c5515cf687198fcb074766883a4d19fe39869df5daa> (325)
  *   M debian/changelog<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-93467241211d3f9d253fb8ad341738fbda5e5d3ade4721326f2bba82525fbaee> (2)
  *   M debian/linuxcnc.lintian-overrides.in<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-373da4ff05ce6942854e6ab99887af6b6e8b2addddebb504e4b860f3b567adcd> (2)
  *   M docs/man/man9/kins.9<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-2b9055ae042442b72fefda090035206bc9d0e3e9ec3113fc37582c9b2a3efe73> (2)
  *   M docs/src/code/building-linuxcnc.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-1f9a932785bdd46c5ccb0273bd6d72eec1d8ba0c7840998fbdba7caf32ba92f3> (61)
  *   M docs/src/drivers/hostmot2.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-1936438ee817a589185f600feacd9d8529369ee3a40c1e6f0548e14503ec42a5> (4)
  *   M docs/src/drivers/mb2hal.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-421b289eeef746ce135e228d98a2aa050bcd00f5e80619b9408944fd627db332> (2)
  *   M docs/src/drivers/shuttle.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-47e21214fb4a17ea074b33fb4c86663595907190f8c2402acb47be0f9f065e3c> (78)
  *   M docs/src/getting-started/updating-linuxcnc.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-e21add623253763c101c1c819b2ba91e6e28017e0b1cc55599768afedb79cab8> (47)
  *   M docs/src/gui/gmoccapy.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-d5938372ecb78bb6670db83e11f02cbc6162ad5dc7202ab28765ef408b533d2c> (679)
  *   M docs/src/gui/pyvcp.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-0833febbcd3077530b315751b9fa71bc201da2d7bd9276575a329fbb6987e508> (5)
  *   M docs/src/gui/qtvcp-widgets.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-63a14587dc019ad71405ecc7d7978d9d610ad0aa566dbb869a012ec61ccde3a9> (10)
  *   M docs/src/hal/components.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-7410ca79900a698580908e783c156c50a2747f8fb65c8e221d2c70f4d0da832f> (6)
  *   M docs/src/hal/tools.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-c4cfaa5f84d3cada74e13e48908af208c8f2fc649c6591bedc8dadb56f551bb6> (5)
  *   M docs/src/plasma/qtplasmac.adoc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-1f95fbfb2ce36083076926bf2aae2eefadc5476b862534483ba135265b072fda> (90)
  *   M lib/python/glnav.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-d2a16c79d3740c42d2a515f841fe48321ed7906e97ee4d8ed3ef8897df91c6e3> (4)
  *   M lib/python/qtvcp/qt_pstat.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-85e6dd032d2cc5cc4153124e8a667f790f1c3113762c8da0535b356fc4d320dc> (5)
  *   M lib/python/qtvcp/widgets/camview_widget.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-cf9cf98e3eb4b87044337c48c7ebf1d99a6af24e05010e1aad59f86f5b6b2366> (4)
  *   M lib/python/qtvcp/widgets/round_gauge.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-9afa008ebeb495e9c924a13ce84582b29892df011578e5bedc30c04ad010a68c> (13)
  *   M lib/python/qtvcp/widgets/round_progress.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-0e227ffec3adec5fe38a15d0ac44764f50e5902d34c4a05a5800d353019a2619> (2)
  *   M lib/python/vismach.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-3f359f39593dfc5335e71049deea6df52cbf13860a6acae797b9bc41b4a75c9d> (2)
  *   M share/qtvcp/screens/qtdragon/qtdragon_handler.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-74fa4deef6aa25f71d9a5e8005127374990dfe7f1f2715f7c8c12b6bb3a7b099> (3)
  *   M share/qtvcp/screens/qtdragon_hd/qtdragon_hd_handler.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-bf6f16af52c313660636e9e82e08e0ea4f24515bd37852409c12644afd3dc787> (3)
  *   M src/Makefile<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-3e2513390df543315686d7c85bd901ca9256268970032298815d2f893a9f0685> (3)
  *   M src/emc/canterp/Submakefile<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-e3c4f1deeb7e92914f5c3349297b7bef61a4b054abed050ef3fa265d103c0c56> (16)
  *   M src/emc/rs274ngc/interp_base.cc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-e4daea21a6d335db374a201d7386d70ef7ba440ee0d87aa462c87a051be68cff> (29)
  *   M src/emc/task/emctask.cc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-6b63c316bf18ff0c5cf5022c93028c8b01a86675d4c297a0db2c2221575040ba> (4)
  *   M src/emc/usr_intf/axis/extensions/emcmodule.cc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-aa7c79e3e8b1ce37096e82dbf66b9185a01ebb81c6348ea599ee1bf5bc557de6> (22)
  *   M src/emc/usr_intf/gmoccapy/getiniinfo.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-ac631ca1682e3880a637d2e9f438f8f56270aca4dc61422881f4ef7e3c693470> (12)
  *   M src/emc/usr_intf/gmoccapy/gmoccapy.glade<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-7caaa22f992ab64a5a8cc300a8651ad65096232baeae42fd6de6fd0757e9c0fb> (255)
  *   M src/emc/usr_intf/gmoccapy/gmoccapy.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-f312cf11426f38ce14f58116be820e007813335ec2fc89eab9bcc7a6913808a9> (76)
  *   M src/emc/usr_intf/gmoccapy/notification.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-bbe282839c7e7f3d54df98b22a354cb796ca38095d9d314f51720b989d9365af> (7)
  *   M src/emc/usr_intf/gmoccapy/release_notes.txt<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-403cb76bb17e7face1f403f138e51a69d7c78aead4e186c2b215a5643a6e60a5> (14)
  *   A src/hal/components/xyzab_tdr_kins.comp<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-dba7f2fd3cbdd283946adf6eff792f6a0243fd1bd8fbb38652b2195cdc52278b> (257)
  *   M src/hal/user_comps/vismach/Submakefile<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-7951ec7e143bdf7fa04c36f92d1c2437f70cd02fee02bfe831a6f1f0d68bd726> (3)
  *   A src/hal/user_comps/vismach/xyzab-tdr-gui.py<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-b64fa0126bff498c11674e696729d0c19b7d2ca5e5bd72d1f77c3487df1928ff> (225)
  *   M src/libnml/os_intf/_sem.c<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-bd581fcf70828458da81a148e85277d737b11c4beac56d78007700c41734cbd6> (2)
  *   M src/rtapi/uspace_rtapi_app.cc<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-68dd48d8bdbf08a8ece3857b0ea4e06c12c57dfed2ad85764cdca5b98bd8d037> (4)
  *   R tests/interp/plug/absolute/canon<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-94d4dfa952c6a31d3fffb27fe353d62de6cce9c87c9905bcbc5936fa10687f69> (0)
  *   R tests/interp/plug/absolute/expected<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-0ec078c017e7cbd1511fd542c9bf69b1626ca67cc82a1c5e46520faf64560de8> (0)
  *   A tests/interp/plug/absolute/test.sh<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-97b38a2bec6a48aea4f1aeb5cdba802fd3e52cb81975ace426e623a9caa69fb6> (3)
  *   A tests/interp/plug/filename/canon<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-d2348290ba38a0517024c877239eef7a2d141ffdcea5df6582a7977249c3402c> (9)
  *   A tests/interp/plug/filename/expected<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-d3e3d6330e1db2f22a76c921a3bfc1726b6803d134c7b2603bdeb3ee48efe06c> (9)
  *   A tests/interp/plug/filename/test.sh<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-923f22fd4e02694e6ac725df559374c19dcada7442943e712a7632e44506a4cd> (3)
  *   A tests/interp/plug/relative/canon<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-7a241fe92384c5548f3a332bc2d5cc55d1433458e5cee7606134c1587ed7db9e> (9)
  *   A tests/interp/plug/relative/expected<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-f05cd036e7e2dae585e24222968fd1826cefac82cea81261b06c3772d1d3f6d9> (9)
  *   A tests/interp/plug/relative/test.sh<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-16a5774e024b6772b0e77f7dd93790dae8c6efb5690243cf29c509cf7dc1ae21> (3)
  *   D tests/interp/plug/test.sh<https://github.com/LinuxCNC/linuxcnc/pull/2250/files#diff-56f147c144f04d9e6e204694a96d07569892a61bee67040dc8cdf57eb9702254> (3)

Patch Links:

  *   https://github.com/LinuxCNC/linuxcnc/pull/2250.patch
  *   https://github.com/LinuxCNC/linuxcnc/pull/2250.diff

**Comment by dngarrett** [comment]
The approach is sensible to me.  I have been confused by docs changes that were in master but not in 2.9 contributing to my big mistake.

**Comment by SebKuzminsky** [comment]
> When I finished my 'repair' yesterday pncconf had no comflicts. (I merged 2.9 to master afterwards.)

Your merge of 2.9 into master was "clean" because git saw that all the conflicting commits in 2.9, i.e. between the most recent good merge (d788b67f) and the bad merge (1d836df8), were already in the history of the master branch, so it did not try to merge them again.  Git does not know that the merge that brought those commits into master (1d836df8) used `-s ours` to *discard* all the changes in those commits, and that therefore the changes of all those commits are not in the master tree.

`git cherry-pick` like I used in this PR makes a new commit that applies the patch of the cherry-picked commit, and doesn't try to optimize out already-present commits like merge does.

**Comment by SebKuzminsky** [comment]
> I have been confused by docs changes that were in master but not in 2.9 contributing to my big mistake.

Yeah, the way we handle docs now makes merging a huge mess, and we have to come up with a sustainable solution quick.  I think the solution should be that any changes to the .adoc files should go in 2.9, and any changes to the .po/.pot files should go in master.

**Comment by c-morley** [comment]
On 2023-01-07 09:16, Sebastian Kuzminsky wrote:
>
>     When I finished my 'repair' yesterday pncconf had no comflicts. (I
>     merged 2.9 to master afterwards.)
>
> Your merge of 2.9 into master was "clean" because git saw that all the 
> conflicting commits in 2.9, i.e. between the most recent good merge 
> (d788b67 
> <https://github.com/LinuxCNC/linuxcnc/commit/d788b67f98c241c2b8e624522ecb161b21f296d8>) 
> and the bad merge (1d836df 
> <https://github.com/LinuxCNC/linuxcnc/commit/1d836df8e191b5083e1742f8f7ff10d12a746991>), 
> were already in the history of the master branch, so it did not try to 
> merge them again. Git does not know that the merge that brought those 
> commits into master (1d836df 
> <https://github.com/LinuxCNC/linuxcnc/commit/1d836df8e191b5083e1742f8f7ff10d12a746991>) 
> used |-s ours| to /discard/ all the changes in those commits, and that 
> therefore the changes of all those commits are not in the master tree.
>
> |git cherry-pick| like I used in this PR makes a new commit that 
> applies the patch of the cherry-picked commit, and doesn't try to 
> optimize out already-present commits like merge does.
>

I Understand why it was a clean merge. - It was my check that I didn't 
create another merge problem with my code.

I guess I'm asking what were you trying to fix? AFAICT all code was 
fixed - what did I miss?

Chris

**Comment by c-morley** [comment]
> > I have been confused by docs changes that were in master but not in 2.9 contributing to my big mistake.
> 
> Yeah, the way we handle docs now makes merging a huge mess, and we have to come up with a sustainable solution quick. I think the solution should be that any changes to the .adoc files should go in 2.9, and any changes to the .po/.pot files should go in master.

This was the type of problem I was referring to in my recent emails about merging.
My gut says making rules about what you change within a branch is asking  for trouble.
I guess we could also pull the docs out to another repo - not a fan of this , but would make the problem smaller.

**Comment by c-morley** [comment]
I' quite confused now - I pulled on 2.9 and master and they are fine as far as my code (pncconf and qtvcp) goes.
I seem to missing something so I'll wait. Sorry for any noise I have created.

**Comment by c-morley** [comment]
Oh I see now - you have created a branch. But again what are we trying to fix? 
Isn't the code right now in 2.9 and master?

**Pull request closed without merging**
