### PR TITLE
Py_Size_t & PEP8 formatting

### PR DESCRIPTION
**Pull request by satiowadahc**
Fixes: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats: self.command.mdi(cmd)

Formatting: 
 qtvcp files closer to pep8 standards

### CODE REVIEW

**Comment by c-morley** [comment]
Hey I'm happy for your work to be added to linuxcnc. One request. In the future, please have PEP8 changes as a separate commit. Otherwise it's difficult to see what you changed code wises vrs formatting wise.

**Comment by c-morley** [comment]
Also - Have you tested these changes with python2? Qtvcp in master currently supports both.

**Comment by satiowadahc** [comment]
Hmm I'll have to set up a VM to test... My mills are currently on python 3. 

Would you like me to separate it for this PR?

**Comment by c-morley** [comment]
I can test python2... if separating PEP8 is easy that would be great.

**Comment by satiowadahc** [comment]
I can't seem to locate all the python2 libraries anymore, so if you can that would be much appreciated.

**Comment by satiowadahc** [comment]
Closing this PR and I'll open a second one with just the necessary edits

**Pull request closed without merging**
