### PR TITLE
More documentation changes (with an increased level of tolerance) (smoe: Docs29 mac 100)

### PR DESCRIPTION
**Pull request by smoe**
No idea about how you all feel about it - I had promised to myself not to do any more formatting changes, and kept this with respect of the monospace+italic combinations, but I anticipate that we will need to apply the automated translations to ship anything for French, Spanish and Chinese again. And for that we need to keep the line breaks in check.

### CODE REVIEW

**Comment by hansu** [comment]
Looks good :+1:

**Comment by hansu** [comment]
This was a bad idea to merge it into master. 
If changes will be made to those files in 2.9, it will probably lead to merge conflicts when merging 2.9 up to master.

**Comment by smoe** [comment]
Aaargh. It was meant to go to 2.9 - can we fix this somehow?

**Comment by smoe** [comment]
Me requesting the same against 2.9, possibly?

**Comment by hansu** [comment]
@SebKuzminsky What would you suggest?

**Comment by petterreinholdtsen** [comment]
[Hans Unzner]
> This was a bad idea to merge it into master. 
> If changes will be made to those files in 2.9, it will probably lead
> to merge conflicts when merging 2.9 up to master.

This argument is true for any change done to master, as long as the
merge forward from "older" brances strategy is in place.  The solution
is to clean up any merge conflicts when merging forward.  The
alternative is to stop doing changes only in master, which I assume you
do not suggest.

What is special about these files compared to any other source file in
the repository?

A workaround is to cherry-pick these changes from master into 2.9, and
merge the commit forward into master to bring the two in line.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
>What is special about these files compared to any other source file in
the repository?

Nothing =) 

>A workaround is to cherry-pick these changes from master into 2.9, and
merge the commit forward into master to bring the two in line.

Yeah that's probably the easiest option. Done :heavy_check_mark: .

**Pull request merged**
