### PR TITLE
Updates for RTAI kernel 4.19 support

### PR DESCRIPTION
**Pull request by NTULINUX**
Signed-off-by: Alec Ari <neotheuser@ymail.com>

### CODE REVIEW

**Comment by NTULINUX** [comment]
Can't say I ever saw this before:

RTAPI: ERROR: could not open shared memory (Bad address)
HAL: ERROR: could not initialize RTAPI
halcmd: hal_init() failed: -22

The RTAI testsuite works just fine, any ideas?

**Comment by NTULINUX** [comment]
Can't say I ever saw this before:

RTAPI: ERROR: could not open shared memory (Bad address)
HAL: ERROR: could not initialize RTAPI
halcmd: hal_init() failed: -22

The RTAI testsuite works just fine, any ideas? The only thing different is the kernel version and that tweak I made to rtapi_get_clocks(). All RTAI code is exactly as it was before.

Kernel 4.14 with RTAI runs fine with LinuxCNC.
Kernel 4.19 with RTAI after this commit keeps giving me that error.

**Comment by andypugh** [comment]
I will try to have a look at it some time today.

**Comment by NTULINUX** [comment]
Thanks Andy, I believe there is an invalid pointer somewhere (EFAULT.) I wish I knew where it's coming from..

**Pull request merged**
