### PR TITLE
Added po4a workarounds to English documentation.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
The po4a system fail to handle some variants of AsciiDoc tables, see
https://bugs.debian.org/1002303 for the details.  This patch
reformat tables to get po4a to parse them correctly.

Also, use full image file name for some under specified file names.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
With the release of po4a 0.66-1 in Debian, the issue worked around here is no longer present in po4a.  So if all building of translated documentation will be done with po4a >= 0.66, this workaround is not needed.  I leave it to others to decide if a more strict po4a dependency is OK or not.

**Comment by smoe** [comment]
I am not sure if po4a is broken or if these blanks at the end of lines are indeed needed. I made quite an effort to remove the blanks at the end of lines about everywhere and feel a bit bad now.

**Comment by petterreinholdtsen** [comment]
Most trailing blanks (all you removed, I suspect) could go, so no need to feel bad.

**Comment by SebKuzminsky** [comment]
Thanks for these fixes, and thanks for your patience and gentle reminders.

**Pull request merged**
