### PR TITLE
Delete README_es.md

### PR DESCRIPTION
**Pull request by smoe**
I do not think we should have other languages singled out. The README.adoc should by some magic be inviting already.

### CODE REVIEW

**Comment by jepler** [comment]
Is the target branch (dh_install) of this PR correct?

**Comment by smoe** [comment]
> Is the target branch (dh_install) of this PR correct?

I messed that up. Wanted to help @SebKuzminsky with the Debian packaging and lost my orientation.

**Comment by jepler** [comment]
Ok, I tried changing the base branch but it still looked wrong. It may be better too close this PR and open a fresh one

**Comment by smoe** [comment]
Maybe @SebKuzminsky accepts it and it goes in via that route - trivial and not urgent. But yes, can also create another PR.

**Pull request closed without merging**
