### PR TITLE
Eleviating handling of man pages from debian/*install

### PR DESCRIPTION
**Pull request by smoe**
Introduced wildcards and introduced debian/linuxcnc.manpages plus a simlink from linuxcnc-uspace.manpages.

I did this for the 2.9.1-2 package uploaded to Debian - a man page that moved from .9 to .3 had triggered the upload failure. The now introduced wild cards make this all somewhat simpler.

### CODE REVIEW

**Comment by havardAasen** [comment]
This fails to install the `linuxcnc-uspace-dev` package because of the changed man-pages. Also noticed in Debian with bug [#1055493](https://bugs.debian.org/1055493). I'm not sure I agree that this is a simplification.

I looked at the 2.9.1-1 package that went into Debian, the original source files with the moved man-page is present https://github.com/LinuxCNC/linuxcnc-gbp/commit/ffef8bb430211ef1adc81a732fa352a74da08b13#diff-57bcf5f1fa05f9832d4bd7f85e1600d0bb8a85d0d0716bf6dcc1ad317f3c8c15

I believe the mistake was that the files in the Debian directory was not generated after that last pull from 'upstream', this step seems to have been forgotten, or perhaps not committed.
https://github.com/LinuxCNC/linuxcnc/blob/9ca1edf4f81fdf163982da3d3d5d16bf0c731524/debian/README.source#L79-L80

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> Yes, I borked.

Steffe, do you have a solution for this issue?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
Hm. The logs are no longer available. I am too busy with too many things to address this for the upcoming days/ next two weeks.

**Comment by andypugh** [comment]
I am going to close this as I don't know how it combines with more recent changes and the tests can't be re-run.

**Comment by petterreinholdtsen** [comment]
[Andy pugh]
> I am going to close this as I don't know how it combines with more
> recent changes and the tests can't be re-run.

I pulled out the relevant bits and put them in
<URL: https://github.com/LinuxCNC/linuxcnc/pull/3017 > for your
consideration.

Note, the tests can be rerun by rebasing the changes on top of the
latest 2.9 branch.  Not sure if only Steffen can do it, or if others can
push to his branch too.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request closed without merging**
