### PR TITLE
AXIS: Add an axisui.error pin

### PR DESCRIPTION
**Pull request by kiall**
Add an `axisui.error` pin, mirroring the behaviour of the gmoccapy error pin exactly. The pin will be set high / True upon error, and will be set low / False when all error notifications have been dismissed by the operator.

This would allow us (https://github.com/linuxcnc-probe-screen/probe-screen-ng) to remove the requirement that users install a `.axisrc` file that injects this behaviour. Here's the `.axisrc` file we currently require users to install: https://github.com/linuxcnc-probe-screen/probe-screen-ng/blob/a00dff94257a8a53c764da400bcfad415fc2b95a/.axisrc

### CODE REVIEW

**Comment by alkabal** [comment]
Whoo thanks a lot for correcting my attempt !

Can you check for add abort pin ?

Br

**Comment by alkabal** [comment]
Abort pin seem to work fine !

**Comment by alkabal** [comment]
Errata error pin seem to work fine !

**Comment by alkabal** [comment]
Imo this work fine for error pin.

Ps: I have see for the other confused Pr about abort pin and i will open a new one soon, thank you.

**Comment by andypugh** [comment]
Let's see what the buildbot makes if it, it looks inoccuous.

**Pull request merged**
