### PR TITLE
update 2.8 from master for xhc-whb04b-6

### PR DESCRIPTION
**Pull request by alkabal**
Im unsure about how you do the "master to 2.8" and "2.8 to master" synchronization so i propose this PR for update xhc-whb04b-6

Feel free to close or ask for close if this is useless.

Br

### CODE REVIEW

**Comment by andypugh** [comment]
Anything that goes in to 2.8 goes in to Master by being merged upstream. 
This isn't automatic, but is fairly routine.

**Comment by andypugh** [comment]
It's probably neater to cherry-pick the original commit in master, to keep the same reference. Is this identical to a commit that was put in Master?

**Comment by alkabal** [comment]
Yes the merge to master is this one

**Comment by alkabal** [comment]
https://github.com/LinuxCNC/linuxcnc/pull/1049/files

**Comment by andypugh** [comment]
It turns out that the cherry-pick was difficult (I am not sure why). 
So I have merged this.

**Comment by alkabal** [comment]
Hi

I apologize to ask but have you forgot to validate the merge ? or other reason ?

> It turns out that the cherry-pick was difficult (I am not sure why).
> So I have merged this.

Best regards

**Comment by andypugh** [comment]
I _think_ that I incorporated the changes from this PR by other means? 
Is this it? 
https://github.com/LinuxCNC/linuxcnc/commit/3a7468023be57c8086f14de2e489ca8dc85d2ab7

**Comment by alkabal** [comment]
Hi

Thanks for reply, i'm a little lost i think you have updated master from some more old PR done to 2.8 ?

something is strange with the date of the master hal.h file but all seem to be correct.

This PR is about push to 2.8 the change i done recently in master.


I really apologize for unclear things.

**Comment by andypugh** [comment]
I am confused too. If you look in this view: https://github.com/LinuxCNC/linuxcnc/commits/2.8
On the 11th of May I merged your changes in to 2.8.

**Comment by andypugh** [comment]
Looking more carefully, it seems that I merged something earlier. Let me have a more careful look.

**Pull request merged**
