### PR TITLE
fix: Commit fa2bfe0cd4eecd1d06d9ca548e4cb852aad67053 kills my build on openSUSE #3154

### PR DESCRIPTION
**Pull request by Eckeneckepen**
1. Interrupt configure if no path is found.
2. Call `sysconfig.get_path()` depending if scheme `deb_system` exists.

### CODE REVIEW

**Comment by Eckeneckepen** [comment]
The bullseye test failed, because the python files are installed to
`install -o root -d -m 0755 /__w/linuxcnc/linuxcnc/debian/tmp/usr/lib/python3.9/site-packages`

but are expected by `debian/linuxcnc.install.in` in `usr/lib/python3`.

Does the test container provide `deb_system`? The installation path seems to be from `posix_prefix`.

The log says that ubuntu is used:
2024-10-16T19:28:48.8051261Z Ubuntu
2024-10-16T19:28:48.8051502Z 24.04.1

Is Ubuntu 24.04.1 compatible to Debian 11?
Do Debian 11 and Ubuntu 24.04.1 support already the scheme `deb_system`?

**Comment by Eckeneckepen** [comment]
Checked the log of commit 062589e control.c: expand clipping of motion.adaptive-feed to +/-MAX_FEED_OVERRIDE
https://github.com/LinuxCNC/linuxcnc/actions/runs/11374046558/job/31641934780

bullseye does not seem to support `deb_system`. Same error i have on suse:

```
2024-10-16T21:23:27.7885271Z checking for site-package location... Traceback (most recent call last):
2024-10-16T21:23:27.7887675Z   File "<string>", line 1, in <module>
2024-10-16T21:23:27.7888769Z   File "/usr/lib/python3.9/sysconfig.py", line 523, in get_path
2024-10-16T21:23:27.7889842Z     return get_paths(scheme, vars, expand)[name]
2024-10-16T21:23:27.7890653Z   File "/usr/lib/python3.9/sysconfig.py", line 513, in get_paths
2024-10-16T21:23:27.7891191Z     return _expand_vars(scheme, vars)
2024-10-16T21:23:27.7891716Z   File "/usr/lib/python3.9/sysconfig.py", line 177, in _expand_vars
2024-10-16T21:23:27.7892316Z     for key, value in _INSTALL_SCHEMES[scheme].items():
2024-10-16T21:23:27.7892847Z KeyError: 'deb_system'
```

**Comment by smoe** [comment]
Looks good to me. No idea what had changed where but our builds now fail without that adaptation. @petterreinholdtsen ?

**Comment by andypugh** [comment]
I have reverted my original attempt to fix the problems caused by deleting distutils. 

Maybe somebody else knows how to do it properly?

**Comment by smoe** [comment]
Maybe we can have debian/configure remove distutils only for the latest versions of Debian?

**Comment by petterreinholdtsen** [comment]
Andy reverted the failed attempts.

I drafted an adjusted approach in
<URL: https://github.com/LinuxCNC/linuxcnc/pull/3158 >.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Thank you for useful ideas.  I am testing some of these ideas in my draft patch now.

**Pull request closed without merging**
