### PR TITLE
Axis: add homing prompt to On/Off button.

### PR DESCRIPTION
**Pull request by DdotLdot**
For enable set HOMING_PROMPT = TRUE in DISPLAY section ini file.

homing_prompt

### CODE REVIEW

**Comment by andypugh** [comment]
There is an existing (though non-obvious) feature that covers this use-case. 
http://linuxcnc.org/docs/stable/html/config/ini-config.html#_joint__lt_num_gt_section
See the option VOLATILE_HOME
If this is set then the machine automatically un-homes when turnd off. 

Does that cover your needs?

**Comment by DdotLdot** [comment]
> There is an existing (though non-obvious) feature that covers this use-case. http://linuxcnc.org/docs/stable/html/config/ini-config.html#_joint__lt_num_gt_section See the option VOLATILE_HOME If this is set then the machine automatically un-homes when turned off.
> 
> Does that cover your needs?

Hi.
This has no effect when the Power Off button is pressed, the prompt message only appears when the Power On button is pressed. This is only a reminder to run homing when turning on the machine. Pressing the "Ok" button in message is equivalent to pressing the "Home all" button. By default this message is disabled.

**Comment by andypugh** [comment]
My point is that is VOLATILE_HOME is set, if you turn off the machine then is un-homes and won't run G-code or MDI until re-homed. Whether it will jog in an unhomed state depends on the machine config. 

However, as you say, it is only displayed of configured on. 

But at the moment there is nothing in the documentation to inform the users of the new INI entry. 

If you add the parameter to the documentation then I will merge the change. 
https://github.com/LinuxCNC/linuxcnc/blob/master/docs/src/config/ini-config.adoc

**Comment by andypugh** [comment]
Thanks, merged

**Comment by DdotLdot** [comment]
Thank you

**Pull request merged**
