### PR TITLE
This fixes https://github.com/LinuxCNC/linuxcnc/issues/178 by adding …

### PR DESCRIPTION
**Pull request by rene-dev**
…BACK_TOOL_LATHE support to axis in the DISPLAY section.

Signed-off-by: Rene Hopf <renehopf@mac.com>

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
This looks good to me, but I don't know Axis that well.

@propcoder, can you confirm that this fixes #178 for you?

**Comment by SebKuzminsky** [comment]
@rene-dev , please add a brief explanation of [DISPLAY]BACK_TOOL_LATHE to `docs/src/config/ini-config.txt`

**Comment by jepler** [comment]
As long as your testing included a mill config and a traditional lathe config and those still work, this is fine by me.

**Comment by rene-dev** [comment]
it did. mill configs are not affected at all. lathe configs include the additional y2 button.
do you have any idea where to look for the tool display issues in y2?

**Comment by rene-dev** [comment]
probably a good idea to include #BACK_TOOL_LATHE = 1 in the lathe sim config...

**Pull request merged**
