### PR TITLE
pncconf: fixes for python3 and board discovery

### PR DESCRIPTION
**Pull request by phillc54**
This seems to work with 7i96 and 7i76e, I have no other boards to test.

### CODE REVIEW

**Comment by phillc54** [comment]
It regularly came back with an error that iocode is None.

**Comment by c-morley** [comment]
Thanks Phill!

**Comment by phillc54** [comment]
One issue I did notice with a 7i76e was sserial channel 0 on i/o connector 1.
This is discovered:
discovered

This is selected from the combobox:
selected

**Comment by c-morley** [comment]
Ya that's one of those hack-it-to-make-it-user-friendly things :) I'll see if i can track down where it does it for 7i76 and see if it's practical to get discovery to do it too.

**Comment by c-morley** [comment]
Looks like around 1138 is the code to auto select.
I bet the strings it looks for are slightly different on discovered boards.
Or else this function is not called at all when using discovery. But it's too late tonight to thread that needle....

**Comment by phillc54** [comment]
Thanks for the hint, this seems to do the trick:
`
                        if boardname in ("5i25","7i92",'7i76e'):
                            if boardname == '7i76e' and 'discovered' in firmname:
                                if tempfunc == "TXDATA0": convertedname = _PD.SS7I76M0
                                else: convertedname = pinconvertsserial[tempfunc]
                            elif "7i77_7i76" in firmname:
`

**Comment by c-morley** [comment]
Glad I could finally help a bit :)
Want me to commit the changes?

**Comment by phillc54** [comment]
Yeah, thanks Chris, that would be good.

**Pull request merged**
