### PR TITLE
[EMCIO] Remove various obsolete references to io and iov2

### PR DESCRIPTION
**Pull request by Sigma1912**
This PR removes obsolete references to 'io' and 'iov2'

Background:
'io' and 'iov2' have been removed and their functionality moved to task:
https://github.com/LinuxCNC/linuxcnc/commit/9d79c2aa23e6e6762dfc32b4ad7c4b7d219e9ea4

Discussion see:
https://github.com/LinuxCNC/linuxcnc/pull/3167

### CODE REVIEW

**Comment by Sigma1912** [comment]
Not sure why some of these tests are failing. Seems build and test just fine on my local machine.

**Comment by andypugh** [comment]
> Not sure why some of these tests are failing. Seems build and test just fine on my local machine.

When I last looked it seemed to be a problem with the Ubuntu VM not finding a Firefox snap to install.

**Comment by Sigma1912** [comment]
Thanks for the comment. It seems to have smoothed itself out now.

**Comment by hansu** [comment]
`iocontrol.1.adoc` can also be removed I think. But we should link `iocontrol` to `io` by adding it to the name section:
```diff
io(1)
NAME
+ io, iocontrol - interacts with HAL or G-code in non-realtime
- io - interacts with HAL or G-code in non-realtime
```

**Comment by hansu** [comment]
>po4a.cfg:170: The master file 'src/man/man1/iocontrol.1.adoc' does not exist.


Sorry you have to remove it from the po4a.cfg as well.

**Comment by Sigma1912** [comment]
Looking at this commit by @rene-dev  makes me think that the [EMCIO] 'CYCLE_TIME = 0.100' entry should also be removed.

**Comment by rene-dev** [comment]
Yes, emcio cycle time can be removed as well.

**Comment by Sigma1912** [comment]
This is ready, as far as I'm concerned.

**Pull request merged**
