### PR TITLE
Fix source typos

### PR DESCRIPTION
**Pull request by luzpaz**
Fix for typos found in source code.

### CODE REVIEW

**Comment by luzpaz** [comment]
CI failed in:   
htmldocs -> Build html documentation -> `ERROR: checklink not found, install w3c-linkchecker for HTML link validation`  
ref: https://github.com/LinuxCNC/linuxcnc/runs/4157929305?check_suite_focus=true#step:5:8767  

I can't ascertain if this PR has caused this. Anybody wish to weigh in?

**Comment by phillc54** [comment]
I think that was fixed a few hours ago:
https://github.com/LinuxCNC/linuxcnc/commit/70ed14fcc792a6073fe210685a9d6b0e37bef579

**Comment by rene-dev** [comment]
you are changing labels and IDs in glade files. did you make sure the code refers to the new names?

**Comment by luzpaz** [comment]
@rene-dev I haven't opened glade and physically checked,  i did a global search for said strings and didn't find matches. For example `hbx_programed_volt` I couldn't find any analogous code.

**Pull request merged**
