### PR TITLE
Fix typos in src/ subdirectory

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.po,*.pot,*.svg,*.ts,./.git/logs,./share,./docs/man/es,./configs/attic,*_fr.*,*_es.*,README_es,./src/hal/classicladder -L ans,ba,breal,bu,bulle,componentes,currenty,doubleclick,dout,dum,extint,faktor,fo,fpr,halp,ihs,inout,inport,mot,parm,parms,propertys,ro,seh,ser,smoe,te,tey,trough,ue,ure,wille,wont,wonte`

Follow-up to #2548

### CODE REVIEW

**Comment by smoe** [comment]
all good!

**Comment by SebKuzminsky** [comment]
These spelling fixes should probably go in 2.9.

**Comment by luzpaz** [comment]
> These spelling fixes should probably go in 2.9.

arghh.. sorry! didn't notice I made the PR against master. Will close and resubmit!

**Comment by luzpaz** [comment]
Superseded by #2560

**Comment by luzpaz** [comment]
@smoe thanks.. i've been burnt before with git. But always room to improve. thanks!

**Pull request closed without merging**
