### PR TITLE
Fix honoring {C,CXX,CPP,LD}FLAGS passed to the 'configure'

### PR DESCRIPTION
**Pull request by dwrobel**
This fixes linking against libreadline v5 in a non standard directory.

On Fedora multiple readline libraries can be installed in parallel.
Old GPL-2 compatible libreadline v5 has its own header and library in the
following directories:

 $ rpm -ql compat-readline5-devel | grep -e 'readline\.h' -e 'libreadline\.so'
 /usr/include/readline5/readline/readline.h
 /usr/lib64/readline5/libreadline.so

As per 'configure --help' the following flags (excerpt) should be supported:
 Some influential environment variables:
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
  CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
              you have headers in a nonstandard directory <include dir>

Despite passing above directories via 'CPPFLAGS' and 'LDFLAGS' to 'configure' the linking
process fails as follows:

 gcc -Wl,-rpath-link,../lib -ltirpc  -o ../bin/halcmd objects/hal/utils/halcmd.o
   objects/hal/utils/halcmd_commands.o objects/hal/utils/halcmd_main.o
   objects/hal/utils/halcmd_completion.o ../lib/liblinuxcncini.so.0
   ../lib/liblinuxcnchal.so.0 -lreadline
 /usr/bin/ld: cannot find -lreadline

This was due to not honoring flags passed to configure.

This also fixes the error of passing C specific compielr option to C++ compiler:
   cc1plus: warning: '-Werror=' argument '-Werror=implicit-function-declaration'
   is not valid for C++

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

### CODE REVIEW

**Comment by dwrobel** [comment]
Comparing with old #751 it adds [ifeq ($(BUILD_SYS),uspace)](https://github.com/LinuxCNC/linuxcnc/pull/850/files#diff-7d087b07875afb09211b54c9cc23c35aR119) guard to make sure that none of the following:
 - CPPFLAGS
 - CXXFLAGS
 - CXXFLAGS
 - CFLAGS
 - LDFLAGS

would affect `RTAI` compilation.

**Comment by dwrobel** [comment]
Should fix https://github.com/LinuxCNC/linuxcnc/issues/846.

**Comment by jepler** [comment]
Thanks, I will submit it to the buildbot CI system before merging.

BTW, do you think that CPPFLAGS is redundant and should be merged into CXXFLAGS?  I could not determine why we have the two variables.  It is nothing to do with flags for the C preprocessor, sometimes called cpp, as far as I can tell.

**Comment by dwrobel** [comment]
> I could not determine why we have the two variables.

It's almost self explanatory, see what `configure` print outs:
```
$ ./configure --help | grep CPPFLAGS
  CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
```
so, basically `CPPFLAGS`  is not compiler specific, while `CXXFLAGS`:
```
$ ./configure --help | grep CXXFLAGS
  CXXFLAGS    C++ compiler flags
```
is only for `c++`. In other words if you would like to specify location for the `readline5` headers _(e.g. -I/usr/include/readline5)_ it's useful to just pass it using `CPPFLAGS` as this way all compilers will pick up this parameter.

**Comment by jepler** [comment]
Thanks!

**Pull request merged**
