### PR TITLE
Add example and more info on parameter to logic(9) manual page.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I also replaced the default synopsis with one explaining each available parameter.  As the 'names' parameter did not work, I dropped it from the list of available parameters.

**Comment by dngarrett** [comment]
$ halrun
halcmd: loadrt logic names=abc,def,ghi personality=0x1,0x2,0x3
Note: Using POSIX realtime
halcmd: show pin
Component Pins:
Owner   Type  Dir         Value  Name
     4  bit   IN          FALSE  abc.in-00
     4  s32   OUT             0  abc.time
     4  bit   IN          FALSE  def.in-00
     4  bit   IN          FALSE  def.in-01
     4  s32   OUT             0  def.time
     4  bit   IN          FALSE  ghi.in-00
     4  bit   IN          FALSE  ghi.in-01
     4  bit   IN          FALSE  ghi.in-02
     4  s32   OUT             0  ghi.time

halcmd: unloadrt logic
halcmd: loadrt logic count=3 personality=0x1,0x2,0x3
Note: Using POSIX realtime
halcmd: show pin
Component Pins:
Owner   Type  Dir         Value  Name
     4  bit   IN          FALSE  logic.0.in-00
     4  s32   OUT             0  logic.0.time
     4  bit   IN          FALSE  logic.1.in-00
     4  bit   IN          FALSE  logic.1.in-01
     4  s32   OUT             0  logic.1.time
     4  bit   IN          FALSE  logic.2.in-00
     4  bit   IN          FALSE  logic.2.in-01
     4  bit   IN          FALSE  logic.2.in-02
     4  s32   OUT             0  logic.2.time

halcmd:

**Comment by petterreinholdtsen** [comment]
[Dewey Garrett]
> $ halrun
> halcmd: loadrt logic names=abc,def,ghi personality=0x1,0x2,0x3
> Note: Using POSIX realtime
> halcmd: show pin
> Component Pins:

Interesting.  Did not work when I tested it the other day.  Must have
been a mistanke on my end.  Very good.  I'll update the document.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
If #1797 is accepted first, I'll update this patch to use the new 'examples' declaration.

**Comment by andypugh** [comment]
Did you add the "examples" declaration?

**Comment by petterreinholdtsen** [comment]
Thank you for the proof reading.  Updated commit with the corrections.

As for the examples declaration, it is already in master since the
85749b800bb6348299783bc38148253af7caa2a5 commit.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request merged**
