### PR TITLE
Correcting typos. gardenweazel

### PR DESCRIPTION
**Pull request by 6XoCtujg2C0gne**
Correcting typos in code.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
The changes look good, but something is broken with the tests.

**Comment by 6XoCtujg2C0gne** [comment]
I may have clobbered the first try. This was my first time submitting.

--Andy L.

**Comment by andypugh** [comment]
I am not sure why the checks are failing, I am pretty sure that it isn't your PR.

**Comment by andypugh** [comment]
I don't think it is the tests, 

```
E: Invalid archive signature
E: Internal error, could not locate member control.tar{.zst,.lz4,.gz,.xz,.bz2,.lzma,}
Reading package lists...
E: Could not read meta data from /__w/linuxcnc/linuxcnc/po4a_0.67-2_all.deb
E: The package lists or status file could not be parsed or opened.
```

**Comment by rmu75** [comment]
for whatever reason the download of po4a_0.67-2_all.deb failed without saying so, it got only 279 bytes instead of 2146k. rip-and-test-clang did work, so maybe intermittend failure of the debian mirror -- running the test again will probably succeed.

**Comment by petterreinholdtsen** [comment]
[Robert Schöftner]
> for whatever reason the download of po4a_0.67-2_all.deb failed without
> saying so, it got only 279 bytes instead of 2146k. rip-and-test-clang
> did work, so maybe intermittend failure of the debian mirror --
> running the test again will probably succeed.

Did github introduce some network limitations blocking the download,
perhaps.  Not sure how to debug it.  The failing tests are definitely
not related to this pull request.

I guess a ugly workaround would be to commit a po4a deb to git and
install from there instead...

-- 
Happy hacking
Petter Reinholdtsen

**Comment by andypugh** [comment]
First of all, apologies to the original requestor. We will get round to your PR. 
I would have just merged it after inspection, but you have changed the text of a debug output, so I want to see the test suite pass first. It is possible that a test is looking at that text. (though unlikely) 

What does "Invalid Archive Signature" mean?

**Comment by rmu75** [comment]
> What does "Invalid Archive Signature" mean?

debian .deb files are ar(1) archives, so i guess the file contains something like a 404 error message and therefor is not a valid ar archive.

**Comment by andypugh** [comment]
The CI might be fixed, it might not, I don't care any more. 

It's certainly not a reason to decline this PR. Thanks.

**Pull request merged**
