### PR TITLE
Proposed rewrite of Stepper Information doc

### PR DESCRIPTION
**Pull request by ascurtis**
Proposed rewrite of Stepper Information document. PDF attached for easier reading.
[LinuxCNC Stepper Information - AC Rewrite.pdf](https://github.com/LinuxCNC/linuxcnc/files/2247847/LinuxCNC.Stepper.Information.-.AC.Rewrite.pdf)

Removed first person writing style, re-worded for better clarity, added new section on Closed/Open Loop Steppers, deleted redundant information and calculations, removed dead external links.

Uploaded 3x new page images for inclusion in new asciidoc. Deleted 2x redundant page images from old Stepper Information page.

### CODE REVIEW

**Comment by ascurtis** [comment]
Just realised that my pull request also wants to include my sync of the fork I did yesterday. For the record, this PR is only concerning the modifications to stepper.txt, adding 3x new .png's and deleting 2x old .png's.

**Comment by andypugh** [comment]
Can you try to re-submit without the merge? I don't think that the interface lets us merge only parts of a pull request.

**Comment by c-morley** [comment]
Ok I did this manually - I also squashed your commits down to one.
Thanks for the work.

**Comment by ascurtis** [comment]
@c-morley, thanks for your assistance.

For future reference, is my approach to this correct or do I need to refine my usage of forks and pull requests to prevent unneccessary clutter in the commit history? My concern is that I'm generating more work than I shoud be for such simple changes, particularly if my mods are starting to fall significantly behind where the master repo is at.

**Comment by c-morley** [comment]
I'll hope others give you the best answer as I don't use pull requests, but I'd guess one fork per pulll request would be cleanest.

**Comment by KurtJacobson** [comment]
@ascurtis You should create a new **branch** for each set of changes you plan to open a PR for. Name the branch something that is descriptive of the changes. That way your commits will be separate from the master branch. That will make it so you can update/pull master etc. without affecting commits included in the PR, and also allows you to work on multiple things at a time. If an individual branch falls behind and you would like to update it, then you can rebase the whole branch ontop of the updated master.

If you have any problems I am almost always on the [#linuxcnc](https://webchat.freenode.net/?channels=linuxcnc) IRC channel as hazzy and will try to help.

Thanks for the excellent doc improvements!

Cheers,
Kurt

**Comment by SebKuzminsky** [comment]
The normal github workflow for contributors is something like this (simplified):

### Make a personal fork of the upstream project, and a local clone to work in
1. On github, make a fork of the project you want to contribute to.
2. Your local development machine, clone of your fork.
3. In your local clone, add the upstream project you forked from as a 'remote' in your local clone: `git remote add upstream https://github.com/linuxcnc/linuxcnc`

Note: you only do this once, and you keep using your one personal fork of the upstream project as long as you hack on that project.

### Make your PR
1. Make sure your clone of upstream is up to date: `git fetch upstream`
2. Create a local branch for your new PR, based on the upstream branch that you want the PR to be merged into eventually (in this case master, sometimes 2.7): `git branch my-pr upstream/master`
3. Check out your local branch for your PR: `git checkout my-pr`
4. Hack, build, test, commit, push to *your* github fork, etc.
5. When you're ready to submit your PR, open a PR in the LinuxCNC github repo, from the branch you're working on in your repo, to the upstream branch you started from.

Note: You can repeat this process as often as you like, with different local branches, in your one local clone.

**Comment by ascurtis** [comment]
Thanks chaps, will log that away for the next one.

**Pull request closed without merging**
