### PR TITLE
Hostmot2: Improve I/O pin state in startup error conditions

### PR DESCRIPTION
**Pull request by jepler**
Now, the following GTAGs will have their pins stay in input mode until the first time the "write" function is initialized, AFTER the watchdog is written:
 * STEPGEN
 * ENCODER
 * PWMGEN
 * TPPWM
 * MUXED_ENCODER (note MUXED_ENCODER_SEL is still set promptly)
 * HM2_DPLL (which doesn't have pins as such?)
 * SSR
 * XYMOD
 * INMUX
 * INM

Other GTAGs are set to outputs promptly:
 * SSI
 * BISS
 * FABS
 * RESOLVER
 * BSPI
 * UART_RX
 * UART_TX
 * PKTUART_RX
 * PKTUART_TX
 * SMARTSERIAL
 * MUXED_ENCODER_SEL

Testing performed:

With a 7i92 board, watch the state of the "direction" pin.  It is 5V normally (pulled up), and 0V after "halcmd start" until "halcmd unload all".  If "halcmd start" is never run before "halcmd unload all", it never leaves the 5V (pulled-up) state.

Initially (#723) this was recognized as a problem with hm2_eth not tristating FPGA outputs on error exit, so there's a second change which ensures that this happens.  However, this was not the full problem, and with the late DDR initialization it is more difficult to see the difference this commit makes.

### CODE REVIEW

**Comment by rene-dev** [comment]
should maybe go in 2.8? @andypugh

**Comment by andypugh** [comment]
I think it probably should, as a bugfix. 
But only if it definitely works. :-)

I should be able to test it, I have the hardware

**Comment by andypugh** [comment]
c-morley: Did that commit really belong in this PR?

**Comment by c-morley** [comment]
the qtvcp commit has no connection to the Pr's intent - and it should already be in master anyways.

**Comment by jepler** [comment]
Rebased.  Take another look @andypugh @pcw-mesa  please

**Comment by andypugh** [comment]
This fails runtests and makes xy2mod.c incompatible, fix below:

From 808063d8b49669845dbf31296897989a163a4016 Mon Sep 17 00:00:00 2001
From: andypugh <andy@bodgesoc.org>
Date: Sun, 10 May 2020 16:01:30 +0100
Subject: [PATCH 4/4] hostmot2: Fix the tests to be compatible with the safe
 startup state patch

Also fix xy2mod.c to work with the patch.

Signed-off-by: andypugh <andy@bodgesoc.org>
---
 src/hal/drivers/mesa-hostmot2/xy2mod.c | 2 +-
 tests/hm2-idrom/expected               | 4 ++--
 tests/hm2-idrom/test.sh                | 4 ++--
 3 files changed, 5 insertions(+), 5 deletions(-)

diff --git a/src/hal/drivers/mesa-hostmot2/xy2mod.c b/src/hal/drivers/mesa-hostmot2/xy2mod.c
index 0275e0797..63f1bb9b4 100644
--- a/src/hal/drivers/mesa-hostmot2/xy2mod.c
+++ b/src/hal/drivers/mesa-hostmot2/xy2mod.c
@@ -352,7 +352,7 @@ void hm2_xy2mod_allocate_pins(hostmot2_t *hm2) {
 
         hm2_set_pin_source(hm2, i, HM2_PIN_SOURCE_IS_SECONDARY);
         if (hm2->pin[i].sec_pin & 0x80){
-            hm2_set_pin_direction(hm2, i, HM2_PIN_DIR_IS_OUTPUT);
+            hm2_set_pin_direction_at_start(hm2, i, HM2_PIN_DIR_IS_OUTPUT);
         }
     }
     HM2_PRINT("allocate pins exit");
diff --git a/tests/hm2-idrom/expected b/tests/hm2-idrom/expected
index 8d8720b7a..7043bc9d3 100644
--- a/tests/hm2-idrom/expected
+++ b/tests/hm2-idrom/expected
@@ -10,6 +10,6 @@ hm2/hm2_test\.0: IDROM IOPorts is \d+ but llio num_ioport_connectors is \d+
 hm2/hm2_test\.0: IDROM ClockLow is \d+, that's too low
 hm2/hm2_test\.0: IDROM ClockHigh is \d+, that's too low
 hm2/hm2_test\.0: pin 0 primary tag is 0 \(end-of-list sentinel\), expected 144 pins!
-hm2/hm2_test\.0: hm2_set_pin_direction: invalid pin number 0
+hm2/hm2_test\.0: hm2_set_pin_direction_immediate: invalid pin number 0
 hm2/hm2_test\.0: invalid IDROM PortWidth 24, this board has 5 pins per connector, aborting load
-hm2/hm2_test\.0: IDROM IOPorts is 0 but llio num_ioport_connectors is \d+
+hm2/hm2_test\.0: IDROM IOPorts is \d+ but llio num_ioport_connectors is \d+, driver and firmware are inconsistent, aborting driver load
diff --git a/tests/hm2-idrom/test.sh b/tests/hm2-idrom/test.sh
index 8834f7ed9..0085dfd2d 100755
--- a/tests/hm2-idrom/test.sh
+++ b/tests/hm2-idrom/test.sh
@@ -12,9 +12,9 @@ Error[8]="hm2/hm2_test\.0: IDROM IOPorts is \d+ but llio num_ioport_connectors i
 Error[9]="hm2/hm2_test\.0: IDROM ClockLow is \d+, that's too low"
 Error[10]="hm2/hm2_test\.0: IDROM ClockHigh is \d+, that's too low"
 Error[11]="hm2/hm2_test\.0: pin 0 primary tag is 0 \(end-of-list sentinel\), expected 144 pins!"
-Error[12]="hm2/hm2_test\.0: hm2_set_pin_direction: invalid pin number 0"
+Error[12]="hm2/hm2_test\.0: hm2_set_pin_direction_immediate: invalid pin number 0"
 Error[13]="hm2/hm2_test\.0: invalid IDROM PortWidth 24, this board has 5 pins per connector, aborting load"
-Error[14]="hm2/hm2_test\.0: IDROM IOPorts is 0 but llio num_ioport_connectors is \d+"
+Error[14]="hm2/hm2_test\.0: IDROM IOPorts is \d+ but llio num_ioport_connectors is \d+, driver and firmware are inconsistent, aborting driver load"
 
 result=0
 
-- 
2.20.1

**Comment by jepler** [comment]
Test fixed, thanks.

**Pull request merged**
