### PR TITLE
fix build debian packages python 3

### PR DESCRIPTION
**Pull request by TurBoss**
small change that allows building debian packages with python 3 support

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
This PR breaks packaging on platforms that don't have python3 installed, such as Debian Stretch.

**Comment by rene-dev** [comment]
the python version needs to be moved down to the os specific part. or even better should be specified, some OS versions can build with both versions.

**Comment by rene-dev** [comment]
This is included in the gtk3 branch, which defaults to python3, and also does packaging.
https://github.com/LinuxCNC/linuxcnc/pull/1164

**Comment by TurBoss** [comment]
Thanks!

**Pull request closed without merging**
