### PR TITLE
Added new component safety_latch from MachineKit

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
This component is one of several currently only in MachineKit.  It is simply copied from the https://github.com/machinekit/machinekit-hal repo.

### CODE REVIEW

**Comment by smoe** [comment]
We need a place for these new components in tje documentarion, still. Just from skimming though the source code I can kind of guess what these componets are providing, but I yet lack an idea about how to best use them.

**Comment by smoe** [comment]
Does this need a larger discussion on the mailing list / the next Open Mike meeting? My only complaint is that that we have no changes to the documentation for this component.

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> Does this need a larger discussion on the mailing list / the next Open
> Mike meeting?

No idea how to understand the silence.:(

> My only complaint is that that we have no changes to the documentation
> for this component.

A man page will get an automatically generated from the component
description.  I thought that was enough, while we wait for the
automatically generated list of components?
--
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
>> [Steffen Möller]
>> Does this need a larger discussion on the mailing list / the next Open Mike meeting?

> No idea how to understand the silence.:(

I can understand that HAL should not be bloated with its and pieces nobody wants. And we should likely decide if we want to have some compatibility with MachineKit HAL or if we just like what they are having.

>> My only complaint is that that we have no changes to the documentation for this component.

> A man page will get an automatically generated from the component description. I thought that was enough, while we wait for the automatically generated list of components?

I had not thought about the auto-documentation. Fine with me.

**Comment by silopolis** [comment]
Le dim. 9 oct. 2022 à 18:26, Steffen Möller ***@***.***> a
écrit :

> [Steffen Möller]
> Does this need a larger discussion on the mailing list / the next Open
> Mike meeting?
>
> No idea how to understand the silence.:(
>
> I can understand that HAL should not be bloated with its and pieces nobody
> wants. And we should likely decide if we want to have some compatibility
> with MachineKit HAL or if we just like what they are having.
>
I tend to think that if someone wrote it, then there's a use case, so we
should pull/keep it.
To my knowledge, MK only has enriched HAL and furthermore has taken the
burden of making it an independent app. I'm keeping hope on this last
point...
HAL has the potential to be a common component from LinuxCNC, to MK, ROS,
OpenPLC, as well as being used alone on its own.

**Comment by smoe** [comment]
I don't think there is too much of a complaint about the number of files in a directory. It is more that all those little functional units cannot be tested manually. One possible answer could be that those new developments would be preferably allowed in that have some sort of automated tests in place.

**Comment by SebKuzminsky** [comment]
I have not heard a request for the type of functionality implemented by this component, but I may well have missed something somewhere.

I share @smoe's desire to not add components that are not useful - we have so many components already that it can be overwhelming to search for some piece of functionality one wants.

@petterreinholdtsen would this be useful to you or to anyone you know of, or is this PR from a desire to preemptively incorporate this component in case someone in the future finds it useful?

**Comment by petterreinholdtsen** [comment]
[Sebastian Kuzminsky]
> @petterreinholdtsen would this be useful to you or to anyone you know
> of, or is this PR from a desire to preemptively incorporate this
> component in case someone in the future finds it useful?

My motivation was to merge stuff from Machinekit to LinuxCNC, to reduce
the difference between the code bases, in the belief that stuff added to
Machinekit was added because someone found it useful enough to spend
time implementing the feature.  I have no idea if this is true.

I do not have a use case for it and do not know anyone who asked for
the safety_latch feature.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by SebKuzminsky** [comment]
> My motivation was to merge stuff from Machinekit to LinuxCNC, to reduce the difference between the code bases

As I'm sure you know, the difficulty with that will not be in specific components added on one side or the other, but in the build system and any changes to the core code. 

I will not object if you want to merge this component.

**Comment by smoe** [comment]
How about we add the information on why a particular HAL module was added to the self-documentation of that module? I suggest a sentence like "This module is a backport from the LinuxCNC fork 'MachineKit'. Please help the documentation with a description of its use cases.".

**Comment by hansu** [comment]
@smoe But why should we spend our time documenting things nobody seems to need?

**Comment by smoe** [comment]
We do not know if nobody needs it. Most likely someone somewhere needed this for Machine Kit (or thought that this fills some gap). I would add it in and ask for a PR describing its use - if nothing is coming up then it shall be marked deprecated and removed again.

**Pull request merged**
