### PR TITLE
pncconf: Avoid using hardcoded number of pins (24)

### PR DESCRIPTION
**Pull request by dwrobel**
Avoid using hardcoded number of pins per connector
which results in rising IndexError exception
on lines where 24 is hardcoded, like the following
example:

 firmptype,compnum = self.d["mesa%d_currentfirmwaredata"% boardnum][_PD._STARTOFDATA+pin+(concount*24)]
 IndexError: list index out of range

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

### CODE REVIEW

**Comment by c-morley** [comment]
Is your idea to allow cards with more then 24 pins? That would be a big change.

**Comment by dwrobel** [comment]
> Is your idea to allow cards with more then 24 pins?

No, rather the opposite, with `17` pins. I've tested it with my `7i92` firmware _(see my [private_data.py](https://github.com/dwrobel/linuxcnc/commit/11feed4d06b2fc52eb8ad31fc8886dfd4aeb9baf))_ and the original `pncconf` didn't work at all.
With this change I didn't encountered any `IndexError` exceptions so far. My assumption is that this change should be transparent to existing configurations and should be helpful in case you have a different [breakout](https://www.amazon.com/Breakout-optical-coupler-Stepper-Driver/dp/B00WN4T23W) card.

**Comment by c-morley** [comment]
pncconf functions all assume 24 pin data. Cards with less padded the firmware data.
Your data doesn't look like it padded the data - that is why you got the error.

I'm not against this change in principle.
This needs to be tested careful - that breaking the assumption doesn't create corner case problems.

**Comment by c-morley** [comment]
Please open again, if this is really needed. Thanks

**Pull request closed without merging**
