### PR TITLE
removed unused amplifier enable and disable cmd

### PR DESCRIPTION
**Pull request by rene-dev**
am I missing something here, or is this all unused code and commands?

### CODE REVIEW

**Comment by c-morley** [comment]
What controls the amplifier HAL pins at the moment?

**Comment by rene-dev** [comment]
EMCMOT_JOINT_ACTIVATE and EMCMOT_JOINT_DEACTIVATE set SET_JOINT_ACTIVE_FLAG which sets SET_JOINT_ENABLE_FLAG which sets the hal pin.

**Comment by rene-dev** [comment]
I will resolve the conflicts and merge this.

**Comment by rene-dev** [comment]
fixed by https://github.com/LinuxCNC/linuxcnc/commit/58135a99c68c80c57fcb948cdacec35fab446590

**Pull request closed without merging**
