### PR TITLE
Update 9_axis.glade, update axis.tcl

### PR DESCRIPTION
**Pull request by tseufl**
wrong path indication, all images are not displayed in the skin

edited: Signed-off-by: Thoren Seufl t_seufl@gmx.de

### CODE REVIEW

**Comment by jepler** [comment]
@tseufl thanks for your contribution!  this commit lacks a "signed-off-by" in the commit message.  Please review the documentation about "signed-off-by": http://www.linuxcnc.org/docs/html//code/contributing-to-linuxcnc.html#_signed_off_by_policy

In the case of a single commit on its own branch, you can typically add the signed-off-by with "git commit --amend -CHEAD -s" and push it with "git push -f".

Besides that, I can't comment on the correctness of the patch.  @c-morley can you?

Thanks to both of you!

**Comment by SebKuzminsky** [comment]
The glade image path changes look right to me.  The current image paths are wrong for both rip and packaged, and this fixes  them.

However, the problem is present in both master and 2.7.  This PR should be rebased to 2.7 and applied there, and merged up to master.

**Comment by jepler** [comment]
@tseufl any idea why github says "unknown repository":
~~~~
tseufl wants to merge 9 commits into LinuxCNC:master from unknown repository 
~~~~
it breaks my normal workflow for fetching PRs locally (or at least I'm guessing the two are related)

**Comment by jepler** [comment]
@tseufl  Not all commits are signed off, so this is rejected by our git server:
~~~~
remote: The following commits are not signed-off.  By policy, all commits
remote: after October 1, 2014 must be signed-off.  For more information, see
remote: http://git.linuxcnc.org/gitweb?p=linuxcnc.git;a=blob;f=docs/SubmittingPatches
remote: 
remote: [on branch refs/heads/master]
remote: b4623be Update 9_axis.glade
remote: 0958ad7 Update axis.tcl
remote: 4f589c7 Update README
~~~~

**Comment by tseufl** [comment]
I close the open request.
Excuse me for the circumstances.

**Comment by jepler** [comment]
Feel free to open additional pull requests at any time.  Thank you for working to improve linuxcnc.

**Pull request closed without merging**
