### PR TITLE
Add simple autopkgtest check for the Debian package.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I am not sure it will work as it stands, as tests seem to assume they got write access to the directory with the source, which I believe is not the case when the tests are running.

If we get this test working, linuxcnc will use much less time to migrate from unstable to testing in Debian.

**Comment by silopolis** [comment]
Le mer. 27 juil. 2022 à 16:48, petterreinholdtsen ***@***.***>
a écrit :

> If we get this test working, linuxcnc will use much less time to migrate
> from unstable to testing in Debian.
>
Very much worth trying then 👍

**Comment by petterreinholdtsen** [comment]
I rewrote runtests to write into $TMPDIR instad of the source directory, and suspect this should work now.

**Comment by smoe** [comment]
Debian performs tests on reverse dependencies when libraries etc are updated in the system. It is in our very interest to have some basic functionality, say a couple of HAL scripts to then be informed when something breaks when a dependency of ours is updated.

**Pull request merged**
