### PR TITLE
gscreen: add setting of log levels, fix Vte terminal

### PR DESCRIPTION
**Pull request by c-morley**
draft for gscreen logging. I think others are doing gscreen work so don't want to create merge problems.
Can be used as a guide or I can do this later.

### CODE REVIEW

**Comment by phillc54** [comment]
I applied this patch to my current gscreen branch and there were only a few conflicts.
One conflict was the Vte terminal as I had done that as well but with spawn_async rather than spawn_sync.

I changed the "Gmoccapy"  in the following line to "Gscreen"
`LOG = logger.initBaseLogger('Gmoccapy', log_file=None, log_level=logger.WARNING)`

I was getting an error with `LOG.exception()` so I changed it to `LOG.error(e)`

I moved all the logging initialization up near the top so it would be available for the audio and desktop notification setup.

I added several LOG commands and it all seems to work well.

**Comment by c-morley** [comment]
If you move the logging initialization to the top then you can't set the logging level on the gladevcp libraries - they will always be at warning level.
spawn_asynch is the newest code, I noticed that too late :)
What was the error with log.exception ? I started using it in qtvcp, it formats errors nicer with better info - has the newest libraries changed again? Thanks for feed back.

**Comment by phillc54** [comment]
> If you move the logging initialization to the top then you can't set the logging level on the gladevcp libraries - they will always be at warning level.

So should we move the notify and audio test down the bottom below logging?

> spawn_asynch is the newest code, I noticed that too late :)

Yeah, I had almost completed sync and then noticed the change.

> What was the error with log.exception ? I started using it in qtvcp, it formats errors nicer with better info - has the newest libraries changed again?

Oh, it was just missing the argument 'e'

**Comment by c-morley** [comment]
> > If you move the logging initialization to the top then you can't set the logging level on the gladevcp libraries - they will always be at warning level.
> 
> So should we move the notify and audio test down the bottom below logging?

yes 
> 
> > spawn_asynch is the newest code, I noticed that too late :)
> 
> Yeah, I had almost completed sync and then noticed the change.
> 
> > What was the error with log.exception ? I started using it in qtvcp, it formats errors nicer with better info - has the newest libraries changed again?
> 
> Oh, it was just missing the argument 'e'

lol of course! Nice catch.
It's supposed to be used only with try - exception code. 
It prints at the ERROR log level but prints more exception-like details.
The levels are (in order)  VERBOSE, DEBUG, INFO, WARNING, ERROR (and exception) and finally CRITICAL

**Comment by phillc54** [comment]
The more I look at logging the more I like it...

I just tried by adding all six levels of logging in the __init__ function of gladevcp/hal_mdihistory.py and the global level setting seems to work whethe the logging setup code is at the top or the bottom of gscreen.py.

**Comment by c-morley** [comment]
Maybe I need to look at your code to understand.

The loglevel set by code such as
logger.setGlobalLevel(logger.INFO)
must be set before any file that uses logging is imported

at the same time that  etGlobalLevel line must be called after the sys args can be read (to see the -i,-d etc)

Yes logging is really nice and can improve performance - printing a lot is expensive.

I'm off for sleep.. happy coding.

**Comment by phillc54** [comment]
Attached is what I tested with. This goes on top of the current 2.9 branch.
I tested with sims/gscreen/gscreen ini using -v then -d  then -i then -q and the global log level seems to work.

I also noticed that gladevcp/iconview.py has no comment in front of LOG.setlevel.
 
[gscreen_logging_test.patch](https://github.com/LinuxCNC/linuxcnc/files/10790616/gscreen_logging_test.patch)

**Comment by c-morley** [comment]
Well Phill that is great!
I never thought sys.arg was valid at that time.
That is way nicer way to lay it out.
It's amazing what one can do - when one doesn't know they can't!

Chris
________________________________

**Comment by phillc54** [comment]
> It's amazing what one can do - when one doesn't know they can't!

I find that out often and mostly accidently.

**Comment by c-morley** [comment]
Closing this do to Phill's pull request supersedes it.

**Pull request closed without merging**
