### PR TITLE
Interp:  Clear `offset_map` on subroutine return in MDI

### PR DESCRIPTION
**Pull request by zultron**
This is a test reproducing #455.  After CI is done failing, patch will follow.

### CODE REVIEW

**Comment by zultron** [comment]
Test from 94f0ebe failed, as expected:
https://travis-ci.org/LinuxCNC/linuxcnc/builds/487343199

**Comment by zultron** [comment]
Ok, this one's not passing because of an unrelated weird bug, I think.  I'll investigate and file a separate issue.

**Comment by zultron** [comment]
Ok, after a few tries, these are the results I was looking for:
- [Failure][1] in 8a943f5, the test reproducing the bug
- [Success][2] in a4488d0, the bug fix

Tests pass, ready for review.  Thanks!

[1]: https://travis-ci.org/LinuxCNC/linuxcnc/builds/487403640
[2]: https://travis-ci.org/LinuxCNC/linuxcnc/builds/487406774

**Comment by andypugh** [comment]
Thanks

**Pull request merged**
