### PR TITLE
Renamed documentation's .txt files to .adoc

### PR DESCRIPTION
**Pull request by smoe**
This follows the advise on best practives from the asciidoc documentation on
https://asciidoctor.org/docs/asciidoc-recommended-practices/

I came up with that rename while skimming through the asciidoc documentation to address the reproducible builds from PR #1342 and learned that github recognizes the .adoc files. I gave it a try and am impressed (see https://github.com/smoe/linuxcnc/blob/Rename_Documentation_txt_to_adoc/docs/src/gcode/coordinates.adoc) as Google even incorporates the graphics. This should give the documentation quite a boost since now those who want to perform changes to the documentation can just use the web interface of Github to edit their files.

### CODE REVIEW

**Comment by smoe** [comment]
Have this fixed locally. This happens when you have LinuxCNC compiling too often on the same machine already and hoped to use the build test to help out with resources :/

**Comment by smoe** [comment]
@SebKuzminsky  - you should love this. If tests pass in this round (like me not having omitted files in my commit again) then I suggest you give this a spin. Conflicts are easy since all that was done is the git mv .txt .adoc.

**Comment by smoe** [comment]
This fails now. The error is
```
```
but there is no .svg in the archive:
```
steffen@wurzel:~/Github/linuxcnc2$ find . -name homing*
./src/emc/motion/homing.c
./src/emc/motion/homing.h
./src/emc/motion/homing.dot
./src/objects/rtemc/motion/homing.d
./src/objects/rtemc/motion/homing.o
./docs/src/code/homing.dot
./docs/src/code/homing_es.dot
./docs/src/code/homing_es.svg
```
Isn't it that the .dot file generates the .svg ? But we have the spanish .svg in the archive, which seems wrong?
```
$ git log ./docs/src/code/homing_es.svg
commit 3ba5819e671d3219c11f84f7c4d23f18b953626c
Author: j.m. garcia <jmgardeto@gmail.com>
Date:   Sat Jul 18 11:48:49 2020 +0200

    added doc/src/code *_es.*
$ git log ./docs/src/code/homing.svg
fatal: ambiguous argument './docs/src/code/homing.svg': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
No idea how this is now triggered - it built fine locally. Will try again. Did a rebase to master but ... ?

**Comment by smoe** [comment]
Ah, ok, the package works, just the html documentation is unhappy. I now removed those redundant spanish .svg files and added $(DOTFILES:.dot=.svg) as a dependency for the failing html-image target.

**Comment by smoe** [comment]
@SebKuzminsky It took more turns than expected but the rename of the asciidoc .txt files to .adoc now seems completed and working. What I do not get is why I had to challenge the Makefile with extra dependencies. In part this likely is because of the Makefile being incomplete (and hence the redundant .svg in the archive that I remove with this patch), but there may be more that I miss.

**Comment by andypugh** [comment]
I don't know why I didn't think of doing this. I had already noticed that things work a lot more neatly on github with .adoc than ,txt. 
I have already done this for some projects of my own as it means that the docs can "live" on github, for example: https://github.com/rene-dev/stmbl/blob/master/docs/src/Getting%20Started.adoc

**Comment by smoe** [comment]
> I don't know why I didn't think of doing this. I had already noticed that things work a lot more neatly on github with .adoc than ,txt.

Great to hear you like this. It was the first look at the Linuxcnc documentation for me (beyond a quick check if the date is fixed on a local PDF from another branch :o) ) .  I am mostly after the extra eyeballs for the project.

> I have already done this for some projects of my own as it means that the docs can "live" on github, for example: https://github.com/rene-dev/stmbl/blob/master/docs/src/Getting%20Started.adoc

You got me immediately side-tracked :)  This reads much like a mini-LinuxCNC project on its own. I understand that https://tracker.debian.org/pkg/dfu-util is outdated (0.9 instead of 0.11) which could be helped. Stlink has moved to https://github.com/stlink-org/stlink and is in Debian as https://tracker.debian.org/pkg/stlink .  Ping me as you see fit.

**Comment by petterreinholdtsen** [comment]
This would make the build rules for po4a based translations easier too, which is a patch I am working on.  Note, this change will invalidate #1346, which need to be updated to modify the adoc files instead of the txt files.  I am happy to do the modification if this change is accepted first.

**Comment by SebKuzminsky** [comment]
I approve whole-heartedly of this change, but I just made a change to master that messed this PR up - sorry.  I removed unused, misnamed spanish translation files, and standardized all our translations to use "_<lang>" filename suffixes, instead of a mix of "-<lang>" and "_<lang>".  Please rebase to incorporate those changes and I'll merge it.

**Comment by smoe** [comment]
Had another look and also renamed *-vi* to *_vn* - not a typo (https://laendercode.net/en/country/vn). Should we add a respective package for the Vietnamese documentation?

**Comment by SebKuzminsky** [comment]
> Had another look and also renamed _-vi_ to __vn_ - not a typo (https://laendercode.net/en/country/vn). Should we add a respective package for the Vietnamese documentation?

Good catch on the vi/vn bug!  I think there's only one document translated to Vietnamese, the gcode overview, and imo that is not enough to warrant it's own package.

**Comment by smoe** [comment]
@SebKuzminsky Seems like I got this .adoc transition back into shape.

**Comment by petterreinholdtsen** [comment]
I created a new edition of this branch rebased on the current master, available as https://github.com/petterreinholdtsen/linuxcnc/tree/Rename_Documentation_txt_to_adoc-rebased-2021-11-03 .  Had to handle some - -> _ renames.

**Comment by SebKuzminsky** [comment]
> https://github.com/petterreinholdtsen/linuxcnc/tree/Rename_Documentation_txt_to_adoc-rebased-2021-11-03

That branch doesn't build for me on bullseye:
`make[1]: *** No rule to make target 'depends/Master_Getting_Started_fr.d', needed by 'Makefile'.  Stop.`

@smoe's branch (that this PR proposes) does build, but can't be merged with master due merge conflicts from minor drift in master.

**Comment by smoe** [comment]
@SebKuzminsky  No problem to merge the "Rename-txt-adoc" branch on my end. Happy :)

**Comment by petterreinholdtsen** [comment]
[Sebastian Kuzminsky]
>> https://github.com/petterreinholdtsen/linuxcnc/tree/Rename_Documentation_txt_to_adoc-rebased-2021-11-03
>
> That branch doesn't build for me on bullseye:
> `make[1]: *** No rule to make target
> 'depends/Master_Getting_Started_fr.d', needed by 'Makefile'.  Stop.`

My mistake.  Did not have time to test the patch.  Updated it and got it
working.

> @smoe's branch (that this PR proposes) does build, but can't be merged
> with master due merge conflicts from minor drift in master.

I hope he can use my rebase to save some time.  I suspect the set of
changes should be squashed a bit.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
Let's hope this builds. I lost oversight a bit about what we are still missing to do prior to the upload to Debian. I tend to think that this .adoc  branch is basically a confirmation that we ran out of the most pressing things to address and we should upload. The basic PR #https://github.com/LinuxCNC/linuxcnc/pull/1291 is still out, PR #https://github.com/LinuxCNC/linuxcnc/pull/1327 there is which may be good enough to also cover https://github.com/LinuxCNC/linuxcnc/pull/1318.

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> Let's hope this builds. I lost oversight a bit about what we are still
> missing to do prior to the upload to Debian.

I believe only the d/rules patch to switch to dh and fix a lot of
lintian issues along the way would be great to include in the upload,
but it is not required.  We can upload that fix later, while keeping the
position in the NEW queue.

> I tend to think that this .adoc  branch is basically a confirmation
> that we ran out of the most pressing things to address and we should
> upload. The basic PR #https://github.com/LinuxCNC/linuxcnc/pull/1291
> is still out, PR #https://github.com/LinuxCNC/linuxcnc/pull/1327 there
> is which may be good enough to also cover
> https://github.com/LinuxCNC/linuxcnc/pull/1318.

Suspect #1291 and #1327 should be kept and #1318 dropped for the short
term, as there seem to be no consensus on changing the python shebang
for the entire project.

Perhaps do the final coordination on IRC, #linuxcnc-devel?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
>> [Steffen Möller]
>> Let's hope this builds. I lost oversight a bit about what we are still missing to do prior to the upload to Debian.

> [Petter]
> I believe only the d/rules patch to switch to dh and fix a lot of lintian issues along the way would be great to include in the upload, but it is not required. We can upload that fix later, while keeping the position in the NEW queue.

Actually, I think we lose positions with a new upload. Not that the position matters much anyway.

>> I tend to think that this .adoc branch is basically a confirmation that we ran out of the most pressing things to address and we should upload. The basic PR ##1291 is still out, PR ##1327 there is which may be good enough to also cover #1318.

> Suspect #1291 and #1327 should be kept and #1318 dropped for the short term, as there seem to be no consensus on changing the python shebang for the entire project.

I have just rebased #1291 and #1327 to master and squashed. Let's see if this still builds.

Fine with me.

> Perhaps do the final coordination on IRC, #linuxcnc-devel?

Somehow IRC and me never became friends. But I very much like to involve the LinuxCNC community about it all, to the degree that anyone wants to be involved. My hopes are on the documentation. This is quite a visible change, I tend to think.

Best,
Steffen

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> Actually, I think we lose positions with a new upload. Not that the
> position matters much anyway.

We do not loose the position with a new upload.  My source is the
ftpmasters themself.  The order on
<URL: https://ftp-master.debian.org/new.html > is not the order presented
to the ftp-masters when they work on the QUEUE.

> I have just rebased #1291 and #1327 to master and squashed. Let's see
> if this still builds.

Great. :)

> Somehow IRC and me never became friends. But I very much like to
> involve the LinuxCNC community about it all, to the degree that anyone
> wants to be involved. My hopes are on the documentation. This is quite
> a visible change, I tend to think.

OK.  Me and Sebastian is in the channel. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by SebKuzminsky** [comment]
I fixed a couple of little issues with @petterreinholdtsen's Rename_Documentation_txt_to_adoc-rebased-2021-11-03 branch, it now builds, and the PDFs look the same before and after the branch.

I've pushed it to https://github.com/LinuxCNC/linuxcnc/commits/Rename_Documentation_txt_to_adoc-rebased-2021-11-03

If it gets past the github actions and the buildbot i'll merge it in the morning.

**Comment by petterreinholdtsen** [comment]
[Sebastian Kuzminsky]
> I fixed a couple of little issues with @petterreinholdtsen's
> Rename_Documentation_txt_to_adoc-rebased-2021-11-03 branch, it now
> builds, and the PDFs look the same before and after the branch.

Great. :)

> I've pushed it to
> https://github.com/LinuxCNC/linuxcnc/commits/Rename_Documentation_txt_to_adoc-rebased-2021-11-03

I've merged it into my branch.

> If it gets past the github actions and the buildbot i'll merge it in
> the morning.

I discovered a small inconvenience that I seem to have introduced in my
rebase, fixed by this patch:

diff --git a/docs/src/Submakefile b/docs/src/Submakefile
index 40a938455..7600a9a6d 100644
--- a/docs/src/Submakefile
+++ b/docs/src/Submakefile
@@ -752,7 +752,7 @@ docclean:
        -rm -f $(DOC_TARGETS_HTML) $(DOC_DIR)/html/xref*.html $(DOC_DIR)/html/index*.html $(DOC_DIR)/*.png $(DOC_DIR)/man/*.png
        -rm -f .htmldoc-stamp
        -rm -f .html-images-stamp
-       rm -r $(DOTFILES:.dot=.svg)
+       -rm -f $(DOTFILES:.dot=.svg)
 
 
 MAN_DEPS := $(patsubst $(DOC_DIR)/man/%, depends/%.d, $(MAN_SRCS))

The code from Steffen used 'rm -f', so no idea how the 'rm -r' sneaked
in there.  With this in place, 'make distclean' work also if some of the
svgs are not generated. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by SebKuzminsky** [comment]
> `- rm -r $(DOTFILES:.dot=.svg)`
> `+ -rm -f $(DOTFILES:.dot=.svg)`

Good catch, I missed that!  I've applied this patch in my branch, doing one last build & check now.

**Comment by SebKuzminsky** [comment]
I merged a version of this branch into master.  Thanks for all the work @smoe and @petterreinholdtsen !

**Pull request closed without merging**
