### PR TITLE
remove buggy limit check from axis.py

### PR DESCRIPTION
**Pull request by Sigma1912**
This is with regard to this issue:
https://github.com/LinuxCNC/linuxcnc/issues/2646

### CODE REVIEW

**Comment by andypugh** [comment]
I would _much_ rather make the check not-buggy. I am sure that it used to work OK, possibly before JA changes? 

Does the tool length even belong in the calculation, if the system is simply logging the max and min joint positions as the code executes?

**Comment by Sigma1912** [comment]
> I am sure that it used to work OK, possibly before JA changes?

I don't know that was before my time. 

> Does the tool length even belong in the calculation, if the system is simply logging the max and min joint positions as the code executes?

That is a good question, I'll investigate.

**Comment by Sigma1912** [comment]
So I had a look at the values o.canon. calculates:
```
    for i in range(3): # Does not enforce angle limits
        print('# canon.max_extents_notool, machine_limit_max: ',i, ',', o.canon.max_extents_notool[i],',',machine_limit_max[i])
        print('# canon.min_extents_notool, machine_limit_min: ',i, ',', o.canon.min_extents_notool[i],',',machine_limit_min[i])

```
Running the preloaded Splash-gcode gives these values for X(0), Y(1) and Z(2) that seem sensible:

# canon.max_extents_notool, machine_limit_max:  0 , 5.373785039370079 , 10.0
# canon.min_extents_notool, machine_limit_min:  0 , 0.06920511811023623 , -10.0
# canon.max_extents_notool, machine_limit_max:  1 , 0.8222350393700788 , 10.0
# canon.min_extents_notool, machine_limit_min:  1 , 0.005690157480314961 , -10.0
# canon.max_extents_notool, machine_limit_max:  2 , -4.747889763779528 , 0.0
# canon.min_extents_notool, machine_limit_min:  2 , -4.944740157480315 , -12.598425196850394


However running this gcode: 

`G17 G21 G54 G80 G90  

G0 Z-10
G0 X10
G0 Y10
G0 X0Y0Z0 

M2
`
gives me this: 
# canon.max_extents_notool, machine_limit_max:  0 , -9e+99 , 10.0
# canon.min_extents_notool, machine_limit_min:  0 , 9e+99 , -10.0
# canon.max_extents_notool, machine_limit_max:  1 , -9e+99 , 10.0
# canon.min_extents_notool, machine_limit_min:  1 , 9e+99 , -10.0
# canon.max_extents_notool, machine_limit_max:  2 , -9e+99 , 0.0
# canon.min_extents_notool, machine_limit_min:  2 , 9e+99 , -12.598425196850394

So I get the impression that maybe canon extents calculation is somehow fragile.

**Comment by Sigma1912** [comment]
Ok so it seems that if the gcode includes only rapid moves then the calculation does not work because if I change gcode to this:

`G17 G21 G54 G80 G90  

G0 Z-10
G1 X10 F100
G0 Y10
G0 X0Y0Z0 

M2`

Then I get better results:

 canon.max_extents_notool, machine_limit_max:  0 , 0.3937007874015748 , 10.0
 canon.min_extents_notool, machine_limit_min:  0 , 0.0 , -10.0
 canon.max_extents_notool, machine_limit_max:  1 , 0.3937007874015748 , 10.0
 canon.min_extents_notool, machine_limit_min:  1 , 0.0 , -10.0
 canon.max_extents_notool, machine_limit_max:  2 , -4.8660000000000005 , 0.0
 canon.min_extents_notool, machine_limit_min:  2 , -5.2597007874015755 , -12.598425196850394

**Comment by andypugh** [comment]
Are these examples with a tool loaded? The numbers don't appear to match the G-code. 
Or perhaps these are home offsets?

**Comment by Sigma1912** [comment]
No tool offset but with a G54 of -123.596mm (-4.86598 in)

**Comment by Sigma1912** [comment]
So one fundamental problem seems to be that the method axis uses to calculate limit violations disregards tool changes in the gcode.

Example:
G54 of -40mm (-0.1969 in) and  tool loaded (TLO=20 -> 0.7874in):

gcode:

G17 G21 G54 G80 G90  
T10 M6 G43 (TLO = 10mm)
G0 Z25
G1 Z-10 F300
G0 Z0 
M2
 
Axis will calculate for the z axis:
 canon.max_extents_notool, machine_limit_max, last tool offset:  2 ,  -0.19685039370078744 ,  0.0 ,  0.7874015748031497
 canon.min_extents_notool, machine_limit_min, last tool offset:  2 ,  -1.5748031496062993 ,  -12.598425196850394 ,  0.7874015748031497
Program exceeds machine maximum on axis Z

Which is wrong. This gcode runs just fine because the tool is changed before any axis movement happens.

**Comment by Sigma1912** [comment]
In my opinion this method cannot produce reliable limit checking because the calculation has no information about which tool offset is active for a particular move. If I understand the 'calc_extents' function right then it has no information about tool offsets at all.

line 209 glcanon.py:

    def calc_extents(self):
        self.min_extents, self.max_extents, self.min_extents_notool, self.max_extents_notool = gcode.calc_extents(self.arcfeed, self.feed, self.traverse)


If this ever worked correctly then I don't see how it did it for more than the tool loaded on start.

**Comment by gmoccapy** [comment]
according to @andypugh this can be closed. https://github.com/LinuxCNC/linuxcnc/commit/5c9a79d186ea5e8b64772c71694debaddb0005bb

**Pull request closed without merging**
