### PR TITLE
docs: Weblate punctuation checks

### PR DESCRIPTION
**Pull request by smoe**
Went through the "any checks" warnings of weblate, which turned out to be mostly changes to the punctuation that have not been committed.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
This one look good to me.  The only think I am unsure about is the &thinsp; stuff, not sure what the conclusion was there.  I assume it will not cause any problems.

**Comment by hansu** [comment]
[Petter]
You mean the `&thinsp;` stuff?

I am also unsure because these characters generate a lot of warnings. Not sure how we could get rid of warnings like this:
```
../docs/html/tooldatabase/tooldatabase.html:195: parser error : Entity 'thinsp' not defined
to the 6&thinsp;mm endmill with the fewest operating hours.  Then, when a
```

**Comment by smoe** [comment]
How does this affect the PDF? I happily stop introducing those special spaces for now. And, obviously, they are easily sed-ed out should the need arise.

**Comment by hansu** [comment]
It's no problem with the PDF's.

I did some investigation.
First, the warnings can be avoided by using `&#8201;` instead iof `&thinsp;`.
But this doesn't promote the readability of the asciidoc sources. 

Changing  `&thinsp;` to `&#8201;` would be the easiest fix to avoid the warnings. Better to find the root of it, but I have no idea where these warnings come from. If I run only asciidoc to format them as HTMl, I don't get theses warnings.

Second, I did a comparison about different spaces between value and unit (just for fun)

1. No space (no option, I know)
2. Hair space `&#8202;`
3. Thin Space `&#8201;`
4. Normal space

(PDF)
grafik

**Comment by smoe** [comment]
So, for slim numbers like "1" we would want to use half and for wide numbers it would be thin?!? Easy.

**Comment by hansu** [comment]
> So, for slim numbers like "1" we would want to use half and for wide numbers it would be thin?!? Easy.

Yes, we could do that.
But I have another proposal. I think it's the best solution to insert the unicode character as unicode into the source files.
E.g. just copy and paste it from a site like [this](https://www.compart.com/en/unicode/U+2009).
It has two advantages:
- better readable sources
- no warnings

**Comment by hansu** [comment]
>But I have another proposal. I think it's the best solution to insert the unicode character as unicode into the source files.

@smoe any objections regarding this?

**Comment by smoe** [comment]
> > But I have another proposal. I think it's the best solution to insert the unicode character as unicode into the source files.
> 
> @smoe any objections regarding this?

I think I would just want to ignore those number-unit-distances for the time being and just finish those translations. I can live with a few warnings. And if those warnings are wrong then I prefer to fix what is wrong over investing extra work to circumvent the problem.

**Comment by hansu** [comment]
42 warnings which can be eliminated with a simple a replace action, a work wich is quicker done than discussing about it.
But it was more meant if you have objections to insert unicode characters in this way. But seems not. So I go for it?

**Comment by smoe** [comment]
Go for it. That would be done in a separate branch? I would just go and rebase this one to master then.

**Comment by hansu** [comment]
>Go for it. That would be done in a separate branch? I would just go and rebase this one to master then.

Maybe I'll do it after the merge.
But weird that it fails.

**Pull request merged**
